docs/CNAME
Switching CNAME back to github.io for now until we are ready to deploy with polaris.io
=> Switch back to default GitHub pages URL

docs/CNAME
Reverts polaris-catalog/polaris#6 
We're ready for polaris.io to get setup so reverting this PR to get CNAME records back in there!
=> Revert "Switch back to default GitHub pages URL"

.github/pull_request_template.md
Relative links doesn't work while raising the PR as it will be from github pull request page. So, need to use the absolute links.
* Hardware:
* Toolchain:
* SDK:
=> Update pull_request_template.md to use absolute links

build.gradle
Some tests are locale dependent. For instance `PolarisServiceImplIntegrationTest` is failing if `user.language` is not `en`.
Fixes #11 
This PR actually fixes the tests when `Locale` is not `US`.
=> Force user.language as some tests are locale dependent

polaris-core/src/main/java/io/polaris/core/storage/PolarisStorageConfigurationInfo.java
Tiny fix for users in a Locale which has a lower case Capital I. This would make FILE into fıle.
No tests, this is a pretty common fix. We could run the whole test suite in Turkish but that's probably a waste. 
- [X ] I have performed a self-review of my code
- [X ] New and existing unit tests pass locally with my changes
- [X ] I have signed and submitted the [ICLA](https://github.com/polaris-catalog/polaris/blob/main/ICLA.md) and if needed, the [CCLA](https://github.com/polaris-catalog/polaris/blob/main/CCLA.md). See [Contributing](https://github.com/polaris-catalog/polaris/blob/main/CONTRIBUTING.md) for details.
=> Use toLowerCase(Locale.ROOT) to avoid lowercase capital I

build.gradle, extension/persistence/eclipselink/build.gradle, gradle/libs.versions.toml, polaris-core/build.gradle, polaris-service/build.gradle
Introduces Gradle version catalogs (toml files), also bump a couple dependencies to recent versions.
Version catalogs as a central place to declare dependencies are easier to manage. Tools like renovate(bot) and dependabot can use these.
=> Use Gradle version catalog

docs/command-line-interface.md, docs/entities.md, docs/quickstart.md, polaris, regtests/Dockerfile, regtests/client/python/cli/command/__init__.py, regtests/client/python/cli/command/catalog_roles.py, regtests/client/python/cli/command/catalogs.py, regtests/client/python/cli/command/namespaces.py, regtests/client/python/cli/command/principal_roles.py, regtests/client/python/cli/command/principals.py, regtests/client/python/cli/command/privileges.py, regtests/client/python/cli/constants.py, regtests/client/python/cli/options/option_tree.py, regtests/client/python/cli/options/parser.py, regtests/client/python/cli/polaris_cli.py, regtests/client/python/test/test_cli_parsing.py, regtests/polaris, regtests/t_cli/src/test_cli.py
This PR covers various improvements to the Polaris CLI. Changes here include:
* Added the `namespaces` command for creating, listing, and dropping namespaces with the CLI
* Refactored error handling to reduce the proliferation of string literals
* Added support for the `FILE` storage type
* Added end-to-end regression tests for the CLI
* Various usability and bug fixes
* Support for the `CLIENT_ID` and `CLIENT_SECRET` environment variables
* CLI documentation
Added new test `test_cli.py` and updated existing CLI test
=> Improvements to the Polaris CLI

README.md
Readme doc updated with gradle command to build while skipping tests. 
NA. Doc changes
=> Minor: Modified readme with gradle command to build and skip tests.

.github/CODEOWNERS
The CODEOWNERS setting is not currently applying correctly on this repository. This change applies a general rule attributing all files in this repo by default to @polaris-catalog/polaris dev team. 
How CODEOWNERS files work is documented [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
=> [BUG FIX] CODEOWNERS scope

README.md
In case you have (configured) multiple "default" Docker repositories, as it's the case for most podman setups, you have to choose the "right" one here. This change prevents this manual intervention.
=> README: add `docker.io/` qualifier for podman

polaris-core/src/test/java/io/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/io/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java, polaris-core/src/test/java/io/polaris/service/storage/azure/AzureLocationTest.java, polaris-core/src/test/java/io/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java
PolarisObjectMapperUtilTest already uses AssertJ. 
AssertJ provides more helpful messages than JUnit when failed. 
* Hardware:
* Toolchain:
* SDK:
=> Use AssertJ assertions in tests

README.md
Add README note about default (in-memory) credentials
This is to help users to get started with source builds.
Manual execution of the related README instructions.
=> Add README note about default (in-memory) credentials

README.md
=> Suggest docker version

polaris-service/src/main/java/io/polaris/service/PolarisApplication.java
Per the [docs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/client/builder/SdkClientBuilder.html), this `...Builder` class is probably not thread safe:
> Implementations of this interface are mutable and not thread-safe.
Without this fix:
```
ARN  [2024-08-02 20:16:37,178 - 3816146] [pool-3-thread-24 - POST /api/catalog/v1/zfab-test-1/namespaces/abc/tables] [] org.apache.iceberg.util.Tasks: Retrying task after failure: Encountered a null value when resolving configuration attributes. This is commonly caused by concurrent modifications to non-thread-safe types. Ensure you're synchronizing access to all non-thread-safe types. 
java.lang.NullPointerException: Encountered a null value when resolving configuration …
```
=> Don't re-use STS Client Builder across threads

build.gradle, polaris-core/build.gradle, polaris-service/build.gradle
* configure-on-demand
* replace usages of deprecated Gradle APIs
=> Gradle tweaks

docker-compose.yml
This PR fixes the following issue when running docker-compose:
failed to solve: granting entitlement network.host is not allowed by build daemon configuration
Using the host network is not required anyway, as the build is able to finish without it.
Manually by running:
```shell
docker compose -f docker-compose.yml up --build
```
=> Docker compose: remove host network requirement when building

regtests/run_spark_sql.sh, regtests/t_spark_sql/src/spark_sql_azure_blob.sh, regtests/t_spark_sql/src/spark_sql_azure_dfs.sh, regtests/t_spark_sql/src/spark_sql_basic.sh, regtests/t_spark_sql/src/spark_sql_gcp.sh, regtests/t_spark_sql/src/spark_sql_s3.sh, regtests/t_spark_sql/src/spark_sql_s3_cross_region.sh, regtests/t_spark_sql/src/spark_sql_views.sh
Scripts in `regtests` running `curl` command specifies header as Accepts, whereas the proper header should be Accept
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
I don’t believe this will have any functional impact.
Fixes #92
* Hardware:
* Toolchain:
* SDK:
=> Set the correct HTTP Header, `Accept` not `Accepts`

polaris-core/src/main/java/io/polaris/core/persistence/ResolvedPolarisEntity.java, polaris-core/src/main/java/io/polaris/core/persistence/resolver/PolarisResolutionManifest.java, polaris-service/src/main/java/io/polaris/service/catalog/BasePolarisCatalog.java
=> Minor: Fix possible NPE.

Dockerfile, regtests/Dockerfile
Update the `Dockerfile` to use the ubi9 openjdk 21 runtime image for both the build and final image.
Pulling from `docker.io` is subject to aggressive request rate limiting and bandwidth shaping.
=> Dockerfile: use non-`docker.io` registry

polaris-core/src/main/java/io/polaris/core/PolarisConfiguration.java, polaris-core/src/main/java/io/polaris/core/PolarisConfigurationStore.java, polaris-core/src/main/java/io/polaris/core/auth/PolarisAuthorizer.java, polaris-core/src/main/java/io/polaris/core/storage/PolarisStorageConfigurationInfo.java, polaris-service/src/main/java/io/polaris/service/admin/PolarisAdminService.java, polaris-service/src/main/java/io/polaris/service/catalog/BasePolarisCatalog.java, polaris-service/src/main/java/io/polaris/service/config/DefaultConfigurationStore.java, polaris-service/src/test/java/io/polaris/service/admin/PolarisAuthzTestBase.java, polaris-service/src/test/java/io/polaris/service/catalog/BasePolarisCatalogTest.java, polaris-service/src/test/java/io/polaris/service/catalog/BasePolarisCatalogViewTest.java, polaris-service/src/test/java/io/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java, polaris-service/src/test/java/io/polaris/service/catalog/PolarisRestCatalogViewIntegrationTest.java
I've had a hard time working with PolarisConfiguration and ran into various casting issues during testing. Before we have too many configurations, let's impose some structure on these and make it easier to get values out of configs.
I've also unified the catalog-level and service-level configs here, and added a description for each config.
=> Improvements to PolarisConfiguration

.github/workflows/gradle.yml
The setup-gradle action fails, if the wrapper is not using the right version, is not present. Our `gradlew` validates the integrity of the `gradle-wrapper.jar`, so it's safe to disable this.
=> CI: `setup-gradle` action, no `validate-wrappers`

regtests/client/python/cli/polaris_cli.py
When an end-user use env variables for `client-id` and `client-secret` for polaris cli, the value of  `client-id` and `client-secret` are not being used:
- [ x] Bug fix (non-breaking change which fixes an issue)
Verify `client-id` and `client-secret` are indeed being used:
```
./polaris --client-id xxxxx --client-secret xxxxx catalogs list
```
Then tried the same with env variables route:
```
export CLIENT_ID=xxxxx
export CLIENT_SECRET=xxxxx
./polaris catalogs list
```
Without the purposed code change, the catalogs list operation will failed due to the following line of code as it will try to load the `client-id` and `client-secret` from command line arguments regardless (https://github.com/MonkeyCanCode/polaris/blob/main/regtests/client/python/ …
=> Fix cli where env variables are not getting used

extension/persistence/eclipselink/src/main/java/io/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, extension/persistence/eclipselink/src/test/java/io/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreTest.java
Add the logging and also move the PolarisEclipseLinkMetaStoreTest.java since it's in incorrect package.
Fixes #45 
* Hardware:
* Toolchain:
* SDK:
=> Add logging and move test to the right package

README.md, k8/deployment.yaml
Add a mini k8s deployment for running polaris.
Fixes # [[DOC] Directions to run mini-deployment reference k8 directory that does not exist
](https://github.com/polaris-catalog/polaris/issues/99)
Here are all of the resources that got deployed with this deployment:
```
kubectl get all -n polaris
NAME                                      READY   STATUS    RESTARTS   AGE
pod/polaris-deployment-5b8457d65d-dhp5r   1/1     Running   0          108s
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/polaris-service   ClusterIP   10.96.173.228   <none>        8181/TCP   108s
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/polaris-deployment   1/1     1            1 …
```
=> Add mini k8s deployment

Dockerfile, build-logic/src/main/kotlin/polaris-client.gradle.kts, build-logic/src/main/kotlin/polaris-java.gradle.kts, gradle/libs.versions.toml, polaris-core/build.gradle.kts, polaris-core/src/main/java/io/polaris/core/persistence/PolarisResolvedPathWrapper.java, polaris-core/src/main/java/io/polaris/core/persistence/cache/EntityCacheEntry.java, polaris-core/src/main/java/io/polaris/core/persistence/resolver/PolarisResolutionManifest.java, polaris-core/src/main/java/io/polaris/core/persistence/resolver/Resolver.java, polaris-core/src/main/java/io/polaris/core/storage/PolarisStorageConfigurationInfo.java, polaris-core/src/test/java/io/polaris/core/persistence/EntityCacheTest.java, polaris-core/src/test/java/io/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/io/polaris/service/storage/aws/AwsCredentialsStorageIntegrationTest.java, polaris-core/src/test/java/io/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java, polaris-core/src/test/resources/io/polaris/service/storage/gcp/gcp-testGenerateAccessBoundary.json, polaris-core/src/test/resources/io/polaris/service/storage/gcp/gcp-testGenerateAccessBoundaryWithMultipleBuckets.json, polaris-core/src/test/resources/io/polaris/service/storage/gcp/gcp-testGenerateAccessBoundaryWithoutList.json, polaris-core/src/test/resources/io/polaris/service/storage/gcp/gcp-testGenerateAccessBoundaryWithoutWrites.json, polaris-core/src/testFixtures/java/io/polaris/core/persistence/PolarisMetaStoreManagerTest.java
According to the discussion #100, this change enforces Java release 21 for server code and 11 for client consumable code.
Using Java 11 requires some changes to `:polaris-core`. One new BSD-3-Clause licensed test dependency `org.threeten:threeten-extra` was added to provide a mutable clock to replace `java.time.InstantSource`.
Fixes #76
Discussed in #100
=> Server code on Java 21, client code on Java 11

build.gradle.kts
There's a typo in top level gradle build script preventing gradle plugin indexing in IDE (intellij).
Indexing the project in Intellij.
* Hardware:
* Toolchain:
* SDK:
* IDE version: IntelliJ IDEA 2024.1.1 (Community Edition)
=> [Typo] Tope level gradle build script

build-logic/src/main/kotlin/polaris-java.gradle.kts, extension/persistence/eclipselink/src/main/java/io/polaris/extension/persistence/impl/eclipselink/EclipseLinkPolarisMetaStoreManagerFactory.java, extension/persistence/eclipselink/src/main/java/io/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, polaris-core/src/main/java/io/polaris/core/PolarisDefaultDiagServiceImpl.java, polaris-core/src/main/java/io/polaris/core/context/CallContext.java, polaris-core/src/main/java/io/polaris/core/entity/CatalogEntity.java, polaris-core/src/main/java/io/polaris/core/entity/CatalogRoleEntity.java, polaris-core/src/main/java/io/polaris/core/entity/NamespaceEntity.java, polaris-core/src/main/java/io/polaris/core/entity/PolarisEntity.java, polaris-core/src/main/java/io/polaris/core/entity/PrincipalEntity.java, polaris-core/src/main/java/io/polaris/core/entity/PrincipalRoleEntity.java, polaris-core/src/main/java/io/polaris/core/entity/TableLikeEntity.java, polaris-core/src/main/java/io/polaris/core/entity/TaskEntity.java, polaris-core/src/main/java/io/polaris/core/persistence/PolarisMetaStoreManagerImpl.java, polaris-core/src/main/java/io/polaris/core/persistence/PolarisTreeMapMetaStoreSessionImpl.java, polaris-service/src/main/java/io/polaris/service/auth/BasePolarisAuthenticator.java, polaris-service/src/main/java/io/polaris/service/auth/DefaultOAuth2ApiService.java, polaris-service/src/main/java/io/polaris/service/auth/JWTBroker.java, polaris-service/src/main/java/io/polaris/service/auth/TokenInfoExchangeResponse.java, polaris-service/src/test/java/io/polaris/service/catalog/BasePolarisCatalogTest.java
Enable ErrorProne [MissingOverride](https://errorprone.info/bugpattern/MissingOverride)
* Hardware:
* Toolchain:
* SDK:
=> Enable ErrorProne MissingOverride

polaris-service/src/test/java/io/polaris/service/PolarisApplicationIntegrationTest.java, polaris-service/src/test/java/io/polaris/service/auth/JWTRSAKeyPairTest.java
Remove redundant catch block from tests
* Hardware:
* Toolchain:
* SDK:
=> Remove redundant catch block from tests

README.md, run.sh
"setup" can be misunderstood as build-related. Rename the script to avoid confusion. Also add a line of comment what the script does for readers who didn't read (or didn't remember) all of the README.
=> Rename setup.sh to run.sh

README.md, k8/deployment.yaml
With the original README.md, it indicated the k8s manifest will spin up 2 pods and we will have k8s svc on top. However, this is bad as the default backend metastore is in-memory. Thus, each pod will have their own credential thus the svc became unpredictable (unless we want to do headless one then have user point to each pod implicitly). Thus I reduced the replica to 1 and updated the doc to reflect the same. Along with that, I exposed one more port (8182) that is supported by the catalog to expose jmx metrics as well as healthcheck endpoint. 
```sh
kubectl port-forward svc/polaris-service -n polaris 8182:8182
$ curl -s localhost:8182/healthcheck | jq
{
"deadlocks": {
"healthy": true,
"duration": 0,
"timestamp": "2024-08-08T23:16:11.064Z"
}, …
```
=> Reduce k8s deployment replica and add metrics endpoints

polaris-service/src/test/java/io/polaris/service/PolarisApplicationIntegrationTest.java
Replace fail with assertThatThrownBy
* Hardware:
* Toolchain:
* SDK:
=> Replace fail with assertThatThrownBy

build.gradle.kts
Polaris cli will generate a dir named `polaris-venv`, which fails the RAT check. We need to exclude it.
The command `./gradlew build` passed after the fix
=> Exclude the dir polaris-venv to avoid rat failure

build.gradle.kts, polaris-core/src/main/java/io/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java
Fix the error introduced by #59
```
/app/polaris-core/src/main/java/io/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java:177: error: cannot find symbol
#12 95.94       logger.error("\n\n {} \n\n", overrideMessage);
```
=> Fix the compilation failure

polaris-core/src/test/java/io/polaris/core/storage/cache/StorageCredentialCacheTest.java, polaris-service/src/test/java/io/polaris/service/PolarisApplicationIntegrationTest.java
It's useful to assert on the test's expected exception's message to verify
- that the exception is indeed the one being expected (and not some different exception of the same class),
- that the user-visible error message is understandable.
=> Assert on expected exception's message

regtests/client/python/cli/command/catalogs.py, regtests/client/python/test/test_cli_parsing.py
When using the `gcs` storage type, the CLI should correctly use the `storage-account` option instead of `tenant-id` and `multi-tenant-app-name`.
Fixes #133 
Added a test to `test_cli_parsing.py`
=> CLI should pass through GCS service account

polaris-core/src/main/java/io/polaris/core/PolarisConfigurationStore.java
The logger field was made public for technical reasons, but it is possible to hide it with a help of a private method (an interface cannot have private fields, but it can have private methods).
=> Remove LOGGER from PolarisConfigurationStore interface

.github/workflows/check-md-link-config.json
The project web site is not up yet, so disabling link checking for it.
=> Temporarily disable external link checking

.github/workflows/check-md-link.yml
The `Check Markdown links` CI job currently lists all checked links, even successful checks. Only listing errors makes it easier to find mistakes.
=> Link-check CI: only list errors

.github/CODEOWNERS
Preparing to move this repo into the /apache github org https://issues.apache.org/jira/browse/INFRA-26049 
We will lose our GitHub team from the Polaris-Catalog org, so updating code owners with individual humans. 
=> Update codeowners to individual handles to prepare for move

gradle/libs.versions.toml
The shadow-plugin repo has been moved, so has the plugin ID. See [release notes](https://github.com/GradleUp/shadow/releases/tag/8.3.0) for reference.
=> Bump shadow plugin to 8.3.0, use new plugin ID

.github/CODEOWNERS
These's a mistake in the `CODEOWNERS` file: `hivivo` is not in the PPMC list of the proposal.
=> Cleanup CODEOWNERS according to the PolarisProposal

regtests/README.md, regtests/run.sh, regtests/run_spark_sql.sh, regtests/setup.sh
Spark-3.5.1 distribution isn't there anymore. The download always failed. 
Run the regtest run.sh locally to download missing spark distribution
=> Update Spark version for regression tests

polaris-core/build.gradle.kts, polaris-service/build.gradle.kts
The `GenerateTask` doesn't clean the output before it runs. This change deletes the output directory before the generation actually starts.
=> Clean the openapi-code-generation target

polaris-service/src/test/java/io/polaris/service/PolarisApplicationIntegrationTest.java, polaris-service/src/test/java/io/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java, polaris-service/src/test/java/io/polaris/service/catalog/PolarisRestCatalogViewIntegrationTest.java, polaris-service/src/test/java/io/polaris/service/catalog/PolarisSparkIntegrationTest.java, polaris-service/src/test/java/io/polaris/service/task/TestSnapshot.java
This also makes some LOGGER declarations static.
=> Mark final fields as such

README.md
`run_spark_sql.sh` should be the fastest way for any first-timer to try Polaris with a familiar tool like Spark sql. Any beginner can get start with Polaris + Spark SQL in 5 mins. We should promote it in the front page. 
Test  the run_spark_sql.sh locally, which passed.
Here is the screenshot:
=> Add a faster way to try Polaris

build.gradle.kts
When working without network/internet access, the logo download might fail the whole build. This change makes the logo download rather optional and don't even attempt, if Gradle's used in "offline" mode.
Tested locally in some variations.
=> Don't fail IntelliJ import for Polaris logo download

regtests/Dockerfile
This change works around a file-permissions issue when running regtests via `podman compose up --build --exit-code-from regtest` (not Docker). CI is happy without this change.
Generally speaking, a `chmod -R go+rwx` is not good, however, it is only for tests running in a container.
```
[regtest] | t_cli/src/test_cli.py ....                                               [ 94%]
[regtest] | t_pyspark/src/test_spark_sql_s3_with_privileges.py ssssssssssss          [100%]
[regtest] |
[regtest] | =============================== warnings summary ===============================
[regtest] | ../polaris-venv/lib/python3.8/site-packages/_pytest/cacheprovider.py:479
[regtest] |   /home/spark/polaris-venv/lib/python3.8/site-packages/_pytest/cacheprovider.py:479: PytestCacheWarning: could not create …
```
=> regtests: mitigate file permissions issue with `podman compose`

polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java
This change lets the tests that require secrets not pass but mark those as "skipped".
Also a nit-ish change (suppress-warning).
=> Use `assumeThat` to GCP/Azure ITs that need secrets

README.md, docs/build
Add `docs/build` command so that we can execute the command more easily.
=> Add docs/build command with `--rm` option

regtests/setup.sh
The warehouse name will always be overwritten by individual test cases.
=> Remove unnecessary catalog warehouse config in setup.sh

polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageConfigurationInfo.java, polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, polaris-service/src/test/java/org/apache/polaris/service/PolarisApplicationIntegrationTest.java, regtests/t_pyspark/src/test_spark_sql_s3_with_privileges.py
Custom `write.data.path` and `write.metadata.path` are currently blocked, preventing users from following the guidelines in https://iceberg.apache.org/docs/1.5.1/aws/#object-store-file-layout . This updates the blocking to allow for customized write paths with the existing `ALLOW_UNSTRUCTURED_TABLE_LOCATION` configuration flag. This also adds a test using the object store location provider feature.
Fixes https://github.com/apache/polaris/issues/113
New pytest for S3
* Hardware:
* Toolchain:
* SDK:
=> Add support for customer write.data.path and write.metadata.path with test for object store location provider

regtests/setup.sh
This will cleanup derby home dir for `regtest/setup.sh`.
Fixes [217](https://github.com/apache/polaris/issues/217)
Manually corrupted the derby home dir after a successful run. After derby home got corrupted, user won't be able to rerun the script until derby home is getting cleanup. With this fix, it will cleanup the derby home dir before running the script.
=> Cleanup derby home dir

regtests/run_spark_sql.sh
This is to support catalog backed by s3 in run_spark_sql.sh
Tested locally with s3 and local file system. Both passed.
=> Support catalog backed by s3 in run_spark_sql.sh

build.gradle.kts
`.env` files are used to store environment variables for docker and docker-compose runs. A user may have multiple `.env` files to run against different environments, such as `.env.qa` or `.env.prod`. This excludes those files from the rat checks, since they are missing license headers.
Ran the `gradle build` locally with multiple `.env` files present
* Hardware:
* Toolchain:
* SDK:
=> Exclude .env file from rat checks

LICENSE
Build is failing when property `eclipseLink` is true:
```text
./gradlew clean build -PeclipseLink=true
> Task :polaris-service:generateLicenseReport FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':polaris-service:generateLicenseReport'.
> License information for the following artifacts is missing in the root LICENSE file: 
```
=> License: add missing notices related to eclipselink

polaris-core/src/main/java/org/apache/polaris/core/entity/TableLikeEntity.java, polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/BasePolarisCatalogTest.java, spec/rest-catalog-open-api.yaml
UPDATE/CREATE notifications will be rejected if the timestamp is older than the latest processed for the table.
DROP notifications won't be affected since messing up the order of DROPs is acceptable as they are idempotent.
Update the notification API spec to clarify that the API caller should ensure the correct order of timestamps for a sequence of notifications. Also added the description for 409 conflict error.
* Hardware:
* Toolchain:
* SDK:
=> Notification API reject out of order notifications

.gitignore
After running `./polaris ...`:
```
$ git st
On branch main
Your branch is up to date with 'origin/main'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
poetry.lock
polaris-venv/
pyproject.toml
```
Excluding python-related auxiliary files from source control.
=> Add python aux files to .gitignore

polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, regtests/t_pyspark/src/test_spark_sql_s3_with_privileges.py
Currently, our generated subscoped policy for S3 and GCS restrict the vended credentials to the `/metadata` and `/data` subdirectories of the table base location. This causes issues, e.g., for Trino, which expects to be able to list files and directories in the table base location.
Update regression test to verify changed policy restrictions
* Hardware:
* Toolchain:
* SDK:
=> Remove /metadata and /data subdirectory locations from generated subscoped policy

polaris-core/src/main/java/org/apache/polaris/core/storage/StorageUtil.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/gcp/GcpCredentialsStorageIntegration.java, polaris-core/src/test/java/org/apache/polaris/core/storage/StorageUtilTest.java, polaris-service/src/main/java/org/apache/polaris/service/storage/PolarisStorageIntegrationProviderImpl.java
Currently, we are using `URI.getHost` to extract the bucket from paths, which can return `null` unexpectedly when the bucket contains an underscore. [This seems to be](https://stackoverflow.com/questions/25993225/uri-gethost-returns-null-why) a [known issue](https://stackoverflow.com/questions/28568188/java-net-uri-get-host-with-underscores).
This PR introduces a thin new utility for extracting the path and adds a test for it.
Fixes #262 
Added a new suite, `StorageUtilTest`.
=> Support buckets containing underscore

gradle/wrapper/gradle-wrapper.properties
Gradle 8.10.1 brings:
- support JDK23
- faster configuration cache
- better configuration cache reports
For more details see https://docs.gradle.org/8.10.1/release-notes.html
=> Upgrade to Gradle 8.10.1

gradle/libs.versions.toml, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java
=> Upgrade to Apache Iceberg 1.6.1

extension/persistence/eclipselink/build.gradle.kts
When ECLIPSELINK arg is set to true during build, we will get the following build error:
```
77.81 All projects evaluated.
77.81 
77.81 FAILURE: Build failed with an exception.
77.81 
77.81 * What went wrong:
77.81 10 actionable tasks: 10 executed
77.81 Circular dependency between the following tasks:
77.81 :polaris-service:jar
77.81 \--- :polaris-service:shadowJar
77.81      \--- :polaris-service:jar (*)
77.81 
77.81 (*) - details omitted (listed previously)
77.81 
77.81 
77.81 * Try:
77.81 > Run with --stacktrace option to get the stack trace.
77.81 > Run with --debug option to get more log output.
77.81 > Run with --scan to get full insights.
77.81 > Get more help at https://help.gradle.org.
```
This is introduced as part of https://github.com/apache/polaris/commit/e81a2c40edf37cf78fedd …
=> Fix circular dependency when ECLIPSELINK arg is set to true during build  

polaris-service/build.gradle.kts, polaris-service/src/test/java/org/apache/polaris/service/PolarisApplicationIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisOverlappingCatalogTest.java, polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisOverlappingTableTest.java, polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisServiceImplIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisSparkIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/test/PolarisConnectionExtension.java, polaris-service/src/test/java/org/apache/polaris/service/test/PolarisRealm.java
Generates a new build artifact with the test sources. This lets you re-use test utils and extend entire test classes. For example, if you have a project that includes Polaris, you can now write your own lightweight wrapper test to run the Polaris tests with your own config/environment.
When testing this end-to-end with a class that extends a Polaris test, I ran into an issue where PolarisConnectionExtension and the test classes decided on a different realm identifier, which meant that credentials were created in a different realm than the test ran in. This happened because the realm name was derived from the class names but the class name is tricky to fetch when using inheritance. I changed the test classes to just re-use the same realm name from PolarisConnectionExtension.
Tested the JAR …
=> Enable re-using polaris-service tests

build.gradle.kts
Exclude "logs/**" from license check. When you run `java -jar polaris-service/build/libs/polaris-service-999-SNAPSHOT.jar server `, logs are generated in logs/ folder and the build would fail.
Fixes #299 
* Hardware:
* Toolchain:
* SDK:
=> Exclude "logs/**" from Rat license check

notebooks/SparkPolaris.ipynb, regtests/t_pyspark/src/iceberg_spark.py
As part of https://github.com/apache/polaris/pull/235, we had changed scala version used by spark from 2.13 to 2.12. This PR applied the missing change on jupyter notebook.
Test locally by reran the jupyter notebook.
=> Change scala from 2.13 to 2.12 and iceberg runtime from 1.5.0 to 1.5.2

docs/configuring-polaris-for-production.md, docs/metastores.md, extension/persistence/eclipselink/build.gradle.kts, extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, polaris-service/build.gradle.kts
This is to document how to configure metastore through EclipseLink for H2 database and Postgres.
- H2 dependency is removed from the build and the user can explicitly add database dependencies during the build. 
Fixes #230 
* Hardware:
* Toolchain:
* SDK:
=> Add the doc on how to configure Postgres as the backend database

Dockerfile
https://github.com/apache/polaris/pull/285 adds support for passing EclipseLink dependencies to gradle.
This PR builds on that enhancement to allow passing such dependencies via the Dockerfile
```
$ docker build -t polaris  .
```
```
$ docker build -t polaris --build-arg ECLIPSELINK=true  .
```
```
$ docker build -t polaris --build-arg ECLIPSELINK=true --build-arg ECLIPSELINK_DEPS=org.postgresql:postgresql:42.7.4 .
```
=> Dockerfile: Add build arg for eclipselink dependencies

.github/workflows/check-md-link-config.json, .github/workflows/check-md-link.yml
This PR cleans up config for the "Check md link" Github Action
* Revert #178 now that [polaris.apache.org](polaris.apache.org)is active
* Use `use-quiet-mode: 'yes'` as described in [doc](https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file#custom-variables) (See https://github.com/apache/polaris/pull/181#issuecomment-2304692624)
* Enable check for all MD files in repo (See https://github.com/apache/polaris/pull/141#discussion_r1726148135)
* Run Github Action without filtering on specific paths
* …
=> Cleanup "Check md link" config

polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java
It looks like the jakarta flavor inadvertently got added by someone's IDE and now there's a needless mix of jakarta/iceberg BadRequestException
* Hardware:
* Toolchain:
* SDK:
=> Refactor BasePolarisCatalog to use Iceberg's BadRequestException instead of jakarta

.github/CODEOWNERS
Looks like the 1st pattern (`* @jbonofre ...`) is ignored after https://github.com/apache/polaris/pull/314
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> If you want to match two or more code owners with the same pattern, all the code owners must be on the same line. If the code owners are not on the same line, the pattern matches only the last mentioned code owner.
* Hardware:
* Toolchain:
* SDK:
=> Unwrap global rule in CODEOWNERS

polaris-service/src/test/resources/polaris-server-integrationtest.yml
At 10 per second, PolarisRestCatalogIntegrationTest takes about 2m50s. At 20 per second, it takes about 1m25s.
At 50 per second, it takes about 30s.
At 100 per second it takes about 19s.
At 200 per second it takes about 19s.
=> Bump up the default integration-test requests-per-second to 9999 vs 10

polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, polaris-service/src/main/java/org/apache/polaris/service/types/NotificationType.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/BasePolarisCatalogTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapperAuthzTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java, spec/rest-catalog-open-api.yaml
If a remote catalog or manual caller wants to ensure that permissions, paths, etc., are configured correctly to receive CREATE/UPDATE notifications before deciding to actually create a table in the remote catalog, sending a VALIDATE notification with the prospective table metadata path can pre-validate basic setup. In a VALIDATE call, no actual entities will be mutated or created.
* Hardware:
* Toolchain:
* SDK:
=> Add NotificationType.VALIDATE which can serve as a dry-run of a CREATE without a metadata file

site/content/in-dev/unreleased/entities.md, site/layouts/shortcodes/github-polaris.html
The links in `entities.md` point to files that are _outside_ of the site's `content` directory and inaccessible by Hugo (even a symlink doesn't work). This change updates the links to point to the Polaris GitHub repo, either targeting the `main` branch or a release tag.
=> Site: fix links in `entities.md`

.asf.yaml
All current PR workflow jobs become a strict requirement (must pass) before a PR can be merged.
=> CI: Make all PR workflow jobs required

polaris-core/src/main/java/org/apache/polaris/core/PolarisConfigurationStore.java, polaris-core/src/test/java/org/apache/polaris/service/storage/PolarisConfigurationStoreTest.java
Implementations of PolarisConfigurationStore may return strings regardless of the config type. In particular, one place where this happens when specifying a ConfigOverride in a test.
Currently, the interface checks the expected type for booleans and Lists and casts them to the correct config type. Whether this is a pattern we should proliferate or not is up for debate, but this PR simply extends the existing logic to work for other types, and it adds tests to ensure the different castings work. Without this PR, the test fails.
=> Enable casting config values of most types

helm/polaris/templates/ingress.yaml
There is no `service.port` field defined in the chart.
=> Helm chart: remove undefined field reference

polaris-service/src/main/java/org/apache/polaris/service/catalog/io/WasbTranslatingFileIO.java
Azure SAS tokens are tied to a specific endpoint type (dfs/blob), so the fileIO shouldn't force every path to be translated to `dfs.core.windows.net`, otherwise if a user provides a blob endpoint and Polaris acquires a token for that, the fileIO that tries to read/write with the dfs endpoint would fail to authenticate with the token.
* Hardware:
* Toolchain:
* SDK:
=> WasbTranslatingFileIO to preserve endpoint on translation

polaris-service/src/main/java/org/apache/polaris/service/ratelimiter/TokenBucketRateLimiter.java
```
.../polaris-service/src/main/java/org/apache/polaris/service/ratelimiter/TokenBucketRateLimiter.java:47: warning: invalid input: '&'
* @return whether a token was successfully acquired & spent
^
```
=> Nit: fix javadoc error

polaris-core/src/main/java/org/apache/polaris/core/storage/StorageLocation.java, polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureLocation.java, polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureLocationTest.java
The `AzureLocation.isChildOf` method is currently broken if the parent path points to the root of the container (e.g. `abfss://container@acc.blob.core.windows.net` or `abfss://container@acc.blob.core.windows.net/`). The `filePath` of the path in this case would be parsed as `/` since we always add a "trailing slash". Now if the comparing child path looks something like `abfss://container@acc.blob.core.windows.net/some/file/path/metadata`, the `filePath` would be parsed as `some/file/path/metadata/` after applying the trailing slash, leading to the failure of the `childFilePath.startsWith(parentFilePath)` check since the childFilePath doesn't start with a slash.
Fix is to always ensure a leading slash on top of ensuring a trailing slash.
Please …
=> Fix Azure path comparison when filePath is root ("/")

.github/workflows/helm.yml, helm/polaris/templates/deployment.yaml, helm/polaris/tests/deployment_test.yaml
This PR introduces [helm-unit](https://github.com/helm-unittest/helm-unittest) to facilitate testing the Helm chart.
It also introduces some first unit tests targeting the `deployment.yaml` template. If this PR is accepted and the new feature deemed useful, we could introduce more tests later for other templates in the chart.
New tests for existing features.
In CI.
=> Helm chart: add tests with helm-unit

spec/polaris-management-service.yml
Even though VIEW_CREATE is "about" views, as a privilege it's only applicable to NAMESPACE or CATALOG since views are created under namespaces (and at the catalog-level it means inheriting that for all child namespaces). This will be consistent with how TABLE_CREATE is already declared.
Remove VIEW_READ_PROPERTIES from the TablePrivilege enum; this appears to have been a simple typo.
**Test …
=> Remove a couple non-applicable VIEW privileges from type-specific enums

Dockerfile
Our current Java seems to be vulnerable to [CVE-2023-22025](https://nvd.nist.gov/vuln/detail/CVE-2023-22025). I pulled the latest version from [here](https://catalog.redhat.com/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f).
=> Update Java for CVE-2023-22025

polaris-service/src/test/java/org/apache/polaris/service/catalog/io/FileIOIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/io/TestFileIO.java
TestFileIOs could be forced to throw an exception when calling getLength. Unfortunately this is hard to use because TestFileIOs also contain functionality for measuring file sizes. This meant that any supplied getLength exception would result in the construction of an InputFile to immediately fail instead of the exception being deferred to later.
This PR makes the TestFileIO use the non-exception-throwing-InputFile for measurement. Unfortunately the previous tests were relying on getLength being called at some point during the workloads but Iceberg seems to rarely call getLength, thus I just wrote a separate test to validate the functionality.
=> Fix a slight usability issue with TestFileIO

polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewAwsIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewAzureIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewFileIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewGcpIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/TestUtil.java
Test-only change that refactors the PolarisRestCatalogViewIntegrationTest, which runs the Iceberg REST Catalog test suite, into 1 test per cloud provider. There doesn't seem to be a way to do this in 1 file because we inherit the test methods from a superclass. 
I'm also interested in doing this for other tests but would like to first gather feedback on this one.
=> Refactor PolarisRestCatalogViewIntegrationTest into per cloud provider tests

site/content/community/meetings/_index.adoc
In order to be able to record the meeting, we created a new Google Meet invite.
This PR updates website with the new Polaris Community Sync invite.
=> Update Polaris Community Sync invite

polaris-service/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java
Instead of "is not supported", phrase it as "is not enabled", and provide the catalog config key the user can look up to decide whether to enable the feature for their catalog.
* Hardware:
* Toolchain:
* SDK:
=> Improve the error message in the exception thrown for credential-vending enablement

regtests/client/python/polaris/management/models/aws_storage_config_info.py, regtests/client/python/polaris/management/models/azure_storage_config_info.py, regtests/client/python/polaris/management/models/gcp_storage_config_info.py, regtests/t_cli/src/test_cli.py
Fields like externalId, userArn for AWS, tenantId for Azure, gcsServiceAccount were getting clobbered when parsing a JSON response due to the autogenerated model classes not correctly pulling in subtype properties from the API spec.
This caused types with "required" subfields like Azure's tenantId to completely fail parsing when trying to get or update a catalog.
Less noticeable but also bad was that these subtype properties were effectively invisible.
=> Fix Azure catalog update in CLI by explicitly adding StorageConfigInfo subtype properties

build-logic/settings.gradle.kts
Addressing #265 by reverting to the default mode of `PREFER_PROJECT`
Fixes #265 
Full build and test
* Hardware:
* Toolchain:
* SDK:
=> Setting repositoriesMode back to its default

polaris-core/build.gradle.kts, polaris-service/build.gradle.kts
Hadoop dependencies are not required in `polaris-core`, but `WasbTranslatingFileIOFactory` still needs them for Iceberg FileIO
Gradle-based tests
=> Move hadoop deps from core to `polaris-service`

polaris-service/src/test/java/org/apache/polaris/service/PolarisApplicationIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/TestUtil.java, polaris-service/src/test/java/org/apache/polaris/service/test/SnowmanCredentialsExtension.java, polaris-service/src/test/java/org/apache/polaris/service/test/TestEnvironment.java, polaris-service/src/test/java/org/apache/polaris/service/test/TestEnvironmentExtension.java
Adds a unique ID to the TestEnvironment and uses it for the Snowman Principal/PrincipalRole name and the PolarisRestCatalogViewIntegrationTest catalog name. In subsequent PRs we should use the ID in more places to ensure unique resource names, especially when running tests in parallel and/or against an external Polaris deployment.
=> Add unique ID to TestEnvironment

polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, polaris-service/src/main/java/org/apache/polaris/service/exception/IcebergExceptionMapper.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/BasePolarisCatalogTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/io/FileIOIntegrationTest.java
In a previous change I took a stab at transforming some cloud-provider-specific 403s into Polaris 403s. I don't think the hints were fully accurate as I'm seeing AWS errors that don't mention "access denied". Rather than trying to chase down the exact error messages per cloud provider, I went with reasonable catch-alls. We still only apply this to cloud-provider-specific exception types such as S3Exception so this should be fine.
- [X I have commented my code, particularly in hard-to-understand areas
=> Fix 403 error message hints

.asf.yaml
@flyrain as discussed together, this should "relax" the non-owner contributor's PR workflow approval.
=> Relax non-owner PR workflow approval

version.txt
As ASF incubator project, Polaris version has to contain `-incubating`.
=> Fix Polaris version by adding incubating in preparation for the release

build-logic/src/main/kotlin/polaris-java.gradle.kts, polaris-core/src/main/java/org/apache/polaris/core/monitor/PolarisMetricRegistry.java, polaris-service/src/main/java/org/apache/polaris/service/TimedApplicationEventListener.java, polaris-service/src/test/java/org/apache/polaris/service/TimedApplicationEventListenerTest.java, polaris-service/src/test/java/org/apache/polaris/service/ratelimiter/RateLimiterFilterTest.java, polaris-service/src/test/java/org/apache/polaris/service/test/TestMetricsUtil.java
Currently we emit metrics with the API name in the metric name, for example `polaris.principals.getPrincipal`. This is difficult to query in i.e. Grafana; metric names are not intended to be "dynamic".
This PR adds a new equivalent metric `polaris.TimedApi` with the `API_NAME` tag.
=> Create a new singleton metric with an API_NAME tag

version.txt
As I created the `0.9.x` branch for the `0.9.0` release, I bump `main` to the next release cycle e.g. `1.0.0`.
=> Bump main to 1.0.0-incubating-SNAPSHOT

polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisGrantManager.java, polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisSecretsManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/BaseResult.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/MetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/TransactionWorkspaceMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/cache/EntityCache.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/cache/PolarisRemoteCache.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisCredentialVendor.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheEntry.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java, polaris-service/src/main/java/org/apache/polaris/service/BootstrapRealmsCommand.java, polaris-service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, polaris-service/src/main/java/org/apache/polaris/service/auth/TestOAuth2ApiService.java, polaris-service/src/main/java/org/apache/polaris/service/auth/TokenBroker.java, polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, polaris-service/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java, polaris-service/src/test/java/org/apache/polaris/service/auth/JWTRSAKeyPairTest.java, polaris-service/src/test/java/org/apache/polaris/service/auth/JWTSymmetricKeyGeneratorTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/BasePolarisCatalogTest.java
`PolarisMetaStoreManager` is a monolithic interface that captures persistence, storage credential vending, remote cache, and grant management. This makes it easy to tie together many things that shouldn't be tied together - for example, the authorizer has dependencies on the cache types, so that it's impossible to make authorization pluggable using different grant rules.
This change strictly splits up the interface into multiple interfaces, but the single `PolarisMetaStoreManager` is still an extension of the others. Where it is possible to refer to specific interfaces, (e.g., the Resolver and the EntityCache), the references are changed, but we don't have factory types to generate realm-specific implementations of all interfaces and the PR was growing far too large when I started on that …
=> Refactor PolarisMetaStoreManager interface into multiple interfaces

polaris-service/src/main/java/org/apache/polaris/service/config/RealmEntityManagerFactory.java
`RealmEntityManagerFactory` is an application-scoped bean and as such is expected to be accessed by multiple threads concurrently; but its `getOrCreateEntityManager` method is not thread-safe: it exhibits a non-synchronized check-then-act sequence involving a non-thread-safe map implementation.
Manually as it is difficult to bring evidence of thread-safety issues in a unit test.
=> Make RealmEntityManagerFactory thread-safe

polaris-service/src/test/java/org/apache/polaris/service/catalog/io/FileIOIntegrationTest.java
The feature configuration `MAX_FILE_IO_READ_BYTES` does not seem to exist.
=> Remove non-existent feature configuration in FileIOIntegrationTest

polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java
Minor fix: the realm context in `CallContext` does not match the realm context used to create the metastore manager and the entity manager.
=> Fix wrong realm context in PolarisAuthzTestBase

.github/workflows/gradle.yml
Gradle's `check` is literally all checks, not just formatting - rename the step in the GH workflow.
=> Nit: name CI step to what it does

.github/workflows/gradle.yml
Running `./gradlew test` after `./gradlew check` is useless.
=> Remove duplicate step in Gradle CI job

polaris-service/src/test/resources/polaris-server-integrationtest.yml
The `RESTSessionCatalog` logger is only used to warn about the token endpoint being deprecated. Since there isn't much we can do about this in Polaris for now, reducing its verbosity in tests at least avoid printing the deprecation warning hundreds of times.
=> Reduce RESTSessionCatalog logger verbosity during tests

build-logic/src/main/kotlin/polaris-root.gradle.kts, build-logic/src/main/kotlin/publishing/PublishingHelperExtension.kt, build-logic/src/main/kotlin/publishing/configurePom.kt, build-logic/src/main/kotlin/publishing/rootProject.kt, build-logic/src/main/kotlin/publishing/util.kt
Removes usage of `https://projects.apache.org/json/foundation/people.json` in favor of `https://whimsy.apache.org/public/`.
Also remove the need to manually specify people and their roles for podlings, but added the special champion as a role.
Fixes #476
=> Refactor Apache project info retrieval to use whimsey

.github/workflows/gradle.yml
This way, Gradle will exercise all check tasks and not fail early, for example not skip tests, if spotless complains.
=> CI/Gradle-check: add `--continue` to let Gradle continue and fail at the end

.asf.yaml
Currently, we require a PR to be up to date with `main` before merging. This is annoying as it's impossible to merge if the PR is not up to date and we keep on clicking on "Update branch".
This change "relax" this.
=> Not requiring the PR to be up to date before merging

polaris-service/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java
According to https://polaris.apache.org/in-dev/unreleased/polaris-management-service and https://polaris.apache.org/in-dev/unreleased/rest-catalog-open-api, there are couple endpoints where their success status is 204 instead of 200 (not all of them). As reported by https://github.com/apache/polaris/issues/471, check table existed is one of them where the target status code on success should be 204 instead of 200. While going through IcebergCatalogAdapter.java, I noticed we have couple places where we are using the wrong status code. This PR updated those to reflect the right status code.
Also, there are many places where we are using the following to get status code:
```
Response.ok(Response.Status.NO_CONTENT).build();
```
With above, it will always be 200 instead of 204, thus, I changed …
=> Fix 471: wrong status code on success

build-logic/src/main/kotlin/publishing/MemoizedGitInfo.kt
Changing the output stream for `ExecSpec` as currently done for `MemoizedGitInfo` doesn't work, this change fixes this.
=> Fix MemoizedGitInfo

build-logic/src/main/kotlin/publishing/configurePom.kt, build-logic/src/main/kotlin/publishing/util.kt
Add up to 4 retries to `parseJson()`, which takes a URL as a string, with a 1 second sleep.
Also refactor the return type to be non-`null`.
=> Build/CI: more resilient URL fetches

polaris-service/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java, polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisServiceImplIntegrationTest.java, polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java
This is follow up on https://github.com/apache/polaris/pull/472 which fixed https://github.com/apache/polaris/pull/471. This PR added the missing test cases for success status code.
```sh
➜  polaris git:(status_code_test_cases) ./gradlew test
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
> Task :polaris-service:generatePolarisService
user-defined server variable support is experimental.
################################################################################
################################################################################
Successfully generated code to /Users/yong/Desktop/git/polaris/polaris-service/build/generated
> Task :polaris-core:generatePolarisService …
```
=> Fix 471: add status code test cases

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/EclipseLinkPolarisMetaStoreManagerFactory.java, extension/persistence/eclipselink/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable, polaris-core/build.gradle.kts, polaris-core/src/main/java/org/apache/polaris/core/persistence/MetaStoreManagerFactory.java, polaris-service/build.gradle.kts, polaris-service/src/main/java/org/apache/polaris/service/PolarisApplication.java, polaris-service/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java, polaris-service/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable, polaris-service/src/test/java/org/apache/polaris/service/PolarisApplicationConfigurationTest.java
This is a simplification / cleanup. The dependency does not appear to be required in `polaris-core`
Add custom code to `PolarisApplication` find classes directly listed in the `Discoverable` service descriptor and register them with the ObjectMapper. This approach to finding sub-types is consistent both with the java service descriptors (listed types actually implement the service interface) and at the same time allows moving the Dropwizard `Discoverable` dependencies to the polaris-service module that actually integrates with Dropwizard.
Move leaf metastore classes to the `Discoverable` service descriptor in their respective module.
Note: this fixes the cross-jar leak of EclipseLinkPolarisMetaStoreManagerFactory in service descriptors.
=> Remove dropwizard-jackson dep from core

polaris-core/src/main/java/org/apache/polaris/core/monitor/PolarisMetricRegistry.java, polaris-service/src/test/java/org/apache/polaris/service/TimedApplicationEventListenerTest.java
* Add `@Deprecated` to `PolarisMetricRegistry` to fix `warning: [dep-ann] deprecated item is not annotated with @Deprecated`
* Suppress warnings on usage of those deprecated fields in test classes via `@SuppressWarnings`
=> chore: Fix deprecation warnings (in build and IDE)

polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisServiceImplIntegrationTest.java
The tests were passing because a `Bearer Bearer` token is always invalid :-)
=> Fix wrong Authorization header in token tests

.github/workflows/check-md-link.yml
We are using gaurav-nelson/github-action-markdown-link-check@v1 to perform md link check. According to https://github.com/gaurav-nelson/github-action-markdown-link-check/tree/v1, the max depth by default is set to -1 which  means check all levels. Thus, when a duplicate dir levels are provided, it will actually cause duplicate check on the same files multiple times.
Here is the current behavior:
```
➜  find regtests regtests/client/python/docs regtests/client/python .github build-logic polaris-core polaris-service extension spec k8 getting-started -name '*.md' -not -path './node_modules/*' -exec markdown-link-check '{}' --config .github/workflows/check-md-link-config.json -q ';'
➜  find regtests regtests/client/python/docs regtests/client/python .github build-logic polaris-core …
```
=> Reduce duplicate md link check

polaris-core/src/main/java/org/apache/polaris/core/storage/StorageLocation.java, polaris-core/src/test/java/org/apache/polaris/service/storage/StorageLocationTest.java
Ensure matching file prefixes when using polaris instance with FILE based storage.
We encountered a bug when attempting to register tables to a file-based instance of Polaris for testing. Through logging, we discovered an inconsistent file naming convention when comparing file:/// to /. This inconsistency caused the system to fail to recognize paths that were actually children as child paths, resulting in the isChildOf method failing every time.
This change ensures that when comparing file paths in the isChildOf method, we use a consistent prefix. Additionally, this change enhances the robustness of the method by ensuring that comparisons are made between paths with similar prefixes, whether they start with / or file:///.
Please describe the tests that you ran to verify …
=> Fix matching file prefixes for FILE based catalogs

polaris-service/build.gradle.kts, spec/rest-catalog-open-api.yaml
This commit brings some of the recent REST spec changes to Polaris:
* Config endpoint: added endpoints field
* Added Load Credentials endpoint
* TrueExpression and FalseExpression
* TableMetadata: renamed fields statistics and partition-statistics
* Added RemovePartitionSpecsUpdate
* Minor documentation updates
This commit does NOT bring the Scan API types into Polaris.
=> REST spec: upgrade to Iceberg 1.7.1

extension/persistence/eclipselink/build.gradle.kts, gradle/libs.versions.toml, polaris-core/build.gradle.kts, polaris-service/build.gradle.kts
"Smallrye" is a whole bunch of projects, this change updates the dependency name to match the actual artifact.
=> Properly name dependency smallrye-common-annotation

extension/persistence/eclipselink/src/test/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreManagerTest.java, extension/persistence/jpa-model/src/main/java/org/apache/polaris/jpa/models/ModelPrincipalSecrets.java
Clear text secrets must never be persisted, hence the attributes in `ModelPrincipalSecrets` needs to be removed.
=> Eliminate persistence of secrets entirely

extension/persistence/jpa-model/build.gradle.kts
Building the affected module breaks with Java > 21, this change fixes it
=> Fix build w/ Java > 21

build-logic/src/main/kotlin/polaris-shadow-jar.gradle.kts, dropwizard/service/build.gradle.kts
The `test` task for modules producing a `shadowJar` artifact currently depend on the `shadowJar` task. This isn't necessary to run the tests.
This change removes the dependency of `test` on that task (via `jar`), letting tests in affected modules start much faster, because `shadowJar` isn't running.
Also removing related duplicated configurations in `polaris-dropwizard-service`.
=> Don't let `test` depend on `shadowJar`

dropwizard/service/src/main/resources/META-INF/hk2-locator/default, dropwizard/service/src/test/java/org/apache/polaris/service/PolarisApplicationIntegrationTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/TimedApplicationEventListenerTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/admin/PolarisOverlappingCatalogTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/admin/PolarisOverlappingTableTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/admin/PolarisRealmEntityCacheTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/admin/PolarisServiceImplIntegrationTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/auth/TokenUtils.java, dropwizard/service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogIntegrationTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/catalog/PolarisRestCatalogViewIntegrationTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/catalog/PolarisSparkIntegrationTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/catalog/TestUtil.java, dropwizard/service/src/test/java/org/apache/polaris/service/ratelimiter/TestUtil.java, dropwizard/service/src/test/java/org/apache/polaris/service/test/PolarisConnectionExtension.java, dropwizard/service/src/test/java/org/apache/polaris/service/test/SnowmanCredentialsExtension.java, service/common/src/main/java/org/apache/polaris/service/context/DefaultCallContextResolver.java, service/common/src/main/java/org/apache/polaris/service/context/DefaultRealmContextResolver.java
This refactoring is a no-op in terms of functionality.
This is required as `RealmContext` and `CallContext` may be treated differently in the future (e.g. different scopes).
=> Split DefaultContextResolver in 2 beans

.github/ISSUE_TEMPLATE/1-bug_report.yml, .github/ISSUE_TEMPLATE/2-feature_request.yml, .github/pull_request_template.md
The current PR template contains a lot of overly detailed textual information. This change moves the relevant parts into a _comment_ which does not "leak" into PR descriptions, leaving the whole description field for developer-provided information.
Also removes the "security issue" checkbox, but highlight the fact.
=> Update GitHub templates + remove checkbox from bug-report template

CHAT_BYLAWS.md, CONTRIBUTING.md, site/content/community/_index.adoc
The Slack invitation link is easier for people to join with any email address.
=> Use the Slack invitation link to allow all email addresses to join

dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/PolarisApplication.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/BasePolarisCatalogTest.java, polaris-core/src/main/java/org/apache/polaris/core/PolarisConfiguration.java, service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, service/common/src/main/java/org/apache/polaris/service/task/TaskFileIOSupplier.java
Fixes [#379](https://github.com/apache/polaris/issues/379)
=> pass skip_credential_subscoping_indirection param to TaskFileIOSupplier

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/TestUtil.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java
1. In `catalogOverlapsWithExistingCatalog`, the `listCatalogsUnsafe` method would first call the persistence layer to list all the catalogs under the current account. It would then load each returned catalog to ensure the catalog has not been purged, etc. If the catalog could not be loaded, that catalog in the catalog list would be replaced with NULL, which would cause the subsequent [.map(CatalogEntity::new)](https://github.com/apache/polaris/blob/b7fa1f47ad9f52055c30a69c09c140cd2ec08417/service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java#L521) to throw NPE. This PR adds a filter on the stream to remove NULL entries from the list.
2. Improve debuggability for `TestUtil.createSnowmanManagedCatalog` by printing the response body when response codes don't …
=> Fix NPE in catalogOverlapsWithExistingCatalog() occurring when a listed catalog could not be loaded correctly

dropwizard/service/build.gradle.kts, gradle/libs.versions.toml
This is due to https://github.com/dnsjava/dnsjava/issues/329
That issue is closed as of 18 Dec 2024, but the fix in 3.6.2 does not appear to be effective for java 21.
The DNS lookup error can happen with JDBC persistence like PosgreSQL.
=> Downgrade dnsjava to 3.5.3

build.gradle.kts, tools/version/build.gradle.kts, tools/version/src/jarTest/java/org/apache/polaris/version/TestPolarisVersion.java, tools/version/src/jarTest/resources/META-INF/FAKE_MANIFEST.MF, tools/version/src/main/java/org/apache/polaris/version/PolarisVersion.java, tools/version/src/main/version/polaris-version.properties
Utility artifact that provides static resources containing the version and NOTICE + LICENSE* files, which can be directly served by Quarkus as static web resources, for example `http://127.0.0.1:19120/apache-polaris/NOTICE.txt`.
Utility class that provides above mentioned resources programmatically, plus information for release-builds like the Git tag, Git commit ID, build system.
Fixes #557
=> Add `polaris-version` artifact

dropwizard/service/build.gradle.kts
Fixes #542. 
The main issue was that the "main" `startScripts` task was configured for the shaded jar, but it shouldn't have: this task produces scripts suitable for the "main" distribution; the shadow jar plugin comes with its own task, `startShadowScripts` that produces scripts for the "shaded" distribution.
I manually verified that both distributions contain the required jars, that both contain scripts called `polaris-service`, and that the scripts work.
This PR also switches the docker layout to "main" (exploded jars) instead of "shadow" (uber-jar). I manually verified that images built with this layout work.
Finally, this PR also fixes the fact that the shadow distribution was missing the LICENSE and NOTICE files.
=> Fix startup failures in polaris-service distributions

build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/publishing/MemoizedGitInfo.kt
Adds the following attributes to built jar manifests:
```
Implementation-Title: Apache Polaris(TM) (incubating)
Implementation-Vendor: Apache Software Foundation
Implementation-URL: https://polaris.apache.org/
```
For release builds, if run with `-Prelease` or `-PjarWithGitInfo`, also adds
```
Implementation-Version: <version-string>
```
in addition to the various `Apache-Polaris-*` manifest attributes.
The `Implementation-*` attributes can be retrieved via Java reflection using the `Class.getPackage().getImplementation*()` functions. NB: Only the `Implementation-Title/Vendor/Version` and `Specification-Title/Vendor/Version` attributes are accessible from `Package`, not other manifest attributes.
=> Add `Implementation-*` attributes to jar manifest

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/PolarisApplicationIntegrationTest.java
add test to verify that there are zero errors in the dropwizard application log
Github Actions CI
=> verify dropwizard application log

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisEntityManager.java
=> Add nonnull annotations for `PolarisEntityManager` public constructor

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/TestServices.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisOverlappingCatalogTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisOverlappingTableTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/io/FileIOExceptionsTest.java
These test cases validate the logic of applying proper table location overlaps checks based on various config permutations. As such, running these test on a full Polaris Server is an overkill in terms of resources.
This PR constructs in-memory services local to each test case for exercising the same call paths as before.
=> Convert "location overlap" tests to unit tests

helm/polaris/README.md, helm/polaris/templates/job.yaml, helm/polaris/tests/job_test.yaml, helm/polaris/values.yaml
This passes down the `extraEnv` values to the bootstrapping job as well. This is needed in order to set initial bootstrapping credentials via `POLARIS_BOOTSTRAP_DEFAULT-REALM_ROOT_CLIENT_ID` and `POLARIS_BOOTSTRAP_DEFAULT-REALM_ROOT_CLIENT_SECRET`. In contrast to the ad-hoc bootstrapping of the application (when in in-memory mode), the initial credentials are not printed to stdout, so they cannot be used if not explicitly set via these variables.
=> Helm: add `bootstrapExtraEnv` for bootstrapping job

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisServiceImplIntegrationTest.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsStorageConfigurationInfo.java, polaris-core/src/test/java/org/apache/polaris/core/storage/InMemoryStorageIntegrationTest.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java
Regarding https://github.com/apache/polaris/issues/582, we’re currently unable to update the AWS roleARN associated with a catalog. This is problematic because it prevents users from renaming their AWS role, which is something similar checks don’t restrict in the case of Azure tenant ID and external ID for AWS. It makes sense to block changes when the AWS account ID is also being modified, but if the AWS account ID remains the same, there's no reason we should prevent users from renaming the role.
=> Allow update of AWS roleArn associated with catalog when the AWS account IDs are same

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/ManagementServiceTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisServiceImplIntegrationTest.java
Test that validate the handling of various config permutations are an overkill for integration tests.
This PR makes `testUpdateCatalogWithDisallowedStorageConfig()` and `testCreateCatalogWithDisallowedStorageConfig()` proper unit tests leveraging on-demand in-memory service instances.
=> Move disallowed storage config test cases to unit tests

service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java
We could have NPEs in BasePolarisCatalog.resolveLocationForPath() today. This PR adds log lines to help debug in these situations.
=> Add log lines to help debug NPE in resolveLocationForPath

site/content/in-dev/unreleased/configuring-polaris-for-production.md
Current documentation site doesn't say anything about where to get creds for root principal when using production (Postgres) metastore backend. Which leads to a successful bootstrap w/o an ability to use the server.
I've spent a couple hours figuring out how to control root principal credentials at bootstrap stage and finally found [this](https://github.com/apache/polaris/blob/50ef1bca3a2f32d79829fda313e71f62e8f2633a/polaris-core/src/main/java/org/apache/polaris/core/persistence/PrincipalSecretsGenerator.java#L69-L85) code piece, which answered my question, but let's update the docs as well!
NB: this is a documentation-only change.
=> Clarify setting credentials for root principals when bootstrapping

extension/persistence/eclipselink/src/test/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreManagerTest.java
Apparently `testCreateStoreSession` can fail under certain OS or build configs, because the classpath resources are not file URLs but Jar URLs. The solution is to copy the classpath resources to temporary files.
=> EclipseLink: make test resilient to non-file classpath URLs

dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/config/PolarisApplicationConfig.java, dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/config/TokenBrokerConfig.java, dropwizard/service/src/main/resources/META-INF/hk2-locator/default, service/common/src/main/java/org/apache/polaris/service/auth/JWTRSAKeyPairFactory.java, service/common/src/main/java/org/apache/polaris/service/auth/JWTSymmetricKeyFactory.java, service/common/src/main/java/org/apache/polaris/service/auth/NoneTokenBrokerFactory.java, service/common/src/main/java/org/apache/polaris/service/auth/TokenBrokerFactoryConfig.java
* Detach `TokenBrokerFactory` sub-classes from Jackson-based config parsing logic.
* Add a new unified `TokenBrokerConfig` under DW to hold JWT config data.
* Resolve JWT factories through HK2 named service lookup, using the type name from `TokenBrokerConfig`
* Add dedicated class `NoneTokenBrokerFactory` for the default do-nothing token broker implementation.
* Yaml config (`polaris-server.yml`) is not affected
=> Make JWT brokers injectable

helm/polaris/templates/deployment.yaml, helm/polaris/templates/job.yaml, helm/polaris/tests/deployment_test.yaml, helm/polaris/tests/job_test.yaml
Some/most production environments enforce pod and container security contexts via admission controllers. If they are not compliant, the manifests won't be accepted. The current helm chart only sets the security context of the containers, but not the initContainers. This MR uses the same config for the initContainers as for the containers.
=> Helm: add `securityContext` to initContainers

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/PolarisApplicationIntegrationTest.java
Remove unnecessary Mockito Spies. Overriding token expiry time is not necessary for these tests.
Use normal `AuthConfig` builder for setting the OAuth2 URI.
=> Fix token refresh test case in PolarisApplicationIntegrationTest

dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/throttling/StreamReadConstraintsExceptionMapper.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/PolarisApplicationIntegrationTest.java
The 413 status code seems to be more appropriate than
400 (Bad Request) in this case.
=> Use HTTP status code 413 for exceedingly large payloads

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisCredentialsBootstrap.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PrincipalSecretsGenerator.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisCredentialsBootstrapTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PrincipalSecretsGeneratorTest.java, site/content/in-dev/unreleased/configuring-polaris-for-production.md
I know there has been some back and forth on this topic, so apologies to bring it up again.
I would like to propose a simplification of the environment variables needed to bootstrap credentials, for a few reasons:
1. It currently requires too many variables;
2. Encoding the realm and the principal name in the variable names is error prone.
3. It currently does not take system properties also into account;
Instead I'm proposing to use just one system property or environment variable that contains all the data we need.
=> Simplify the environment variables needed for credential bootstrapping

build-logic/src/main/kotlin/publishing/PublishingHelperPlugin.kt
The build-logic code checked for the _existence_ of the `ShadowExtension`, replacing with a check against the `ShadowPlugin`, yielding the same results.
=> Fix deprecation warning for `ShadowExtension`

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisServiceImplIntegrationTest.java
Remove assertion on too specific JSON parsing error message. The exact message text may vary in different server builds.
=> Make testCreateCatalogWithUnparsableJson() more generic

api/iceberg-service/build.gradle.kts, build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/polaris-license-report.gradle.kts, build-logic/src/main/kotlin/publishing/MemoizedGitInfo.kt, build-logic/src/main/kotlin/publishing/configurePom.kt, build-logic/src/main/kotlin/publishing/rootProject.kt, build-logic/src/main/kotlin/publishing/shadowPub.kt, build-logic/src/main/kotlin/publishing/util.kt, build.gradle.kts, gradle/baselibs.versions.toml, gradle/libs.versions.toml, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageIntegrationProvider.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java, service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, service/common/src/main/java/org/apache/polaris/service/storage/PolarisStorageIntegrationProviderImpl.java
spotless v7 fails on Gradle with some `SerializationException`, moving the `callable` works around this issue (as [mentioned here](https://github.com/diffplug/spotless/issues/2387)).
Also removing the unnecessary `buildscript.dependencies` and the implied 2nd spotless version definition.
Supersedes #680 + #686
=> Bump spotless to v7

dropwizard/service/build.gradle.kts, dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/PolarisApplication.java, dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/auth/PolarisPrincipalAuthenticator.java, dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/auth/PolarisPrincipalRoleSecurityContextProvider.java, dropwizard/service/src/main/java/org/apache/polaris/service/dropwizard/config/PolarisApplicationConfig.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisAdminServiceAuthzTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/admin/PolarisAuthzTestBase.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/BasePolarisCatalogTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/BasePolarisCatalogViewTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/PolarisCatalogHandlerWrapperAuthzTest.java, dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/catalog/PolarisPassthroughResolutionView.java, polaris-core/build.gradle.kts, polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisGrantManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisEntityManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/PolarisResolutionManifest.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/ResolverTest.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java, service/common/src/main/java/org/apache/polaris/service/auth/ActiveRolesProvider.java, service/common/src/main/java/org/apache/polaris/service/auth/DefaultActiveRolesProvider.java, service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java, service/common/src/main/java/org/apache/polaris/service/context/CallContextCatalogFactory.java, service/common/src/main/java/org/apache/polaris/service/context/PolarisCallContextCatalogFactory.java
Currently, the `Resolver` checks the PrincipalRole usage grants available for a Principal entity when determining which roles are active for a request. These roles are then passed on to the `PolarisAuthorizer` so that authorization can be done on the operation and target object.
This PR changes the `Resolver` to instead rely on the `SecurityContext` to determine which roles the principal has access to. A request filter populates the `SecurityContext` using an `ActiveRolesProvider`. The default implementation still looks up the principal role usage grants, but now the filter can be replaced by new implementations that determine role membership in other ways (e.g., by checking an authentication token or delegating to a third party identity provider).
=> Change authentication workflow to lookup principal roles using security context

site/assets/scss/_variables_project.scss, site/hugo.yaml, site/layouts/partials/head.html
The Polaris website fetches a few resources from external sources. This does not compliy w/ the [ASF data policy](https://privacy.apache.org/policies/website-policy.html).
The offending resources are:
* Google Fonts
* jQuery JS
* Lunr JS (search)
This change disables the use of Google fonts and embeds the two JS resources into the Polaris site.
At least Firefox no longer reports any externally loaded content.
Other violations  of the _ASF data policy_ like cookies, direct embeddings of external content or analytics were not present, so no other changes are needed.
=> Adopt site to comply w/ ASF data privacy policy

site/bin/_hugo-docker-include.sh
Podman, if installed, requires some custom arguments. The scripts to run Hugo in a container locally are already prepared for Podman, but fail in case compatibility scripts are installed (aka: `docker-compose` wrapping `podman-compose`). This leads to errors like "no permission to create /hugo/cache/site".
This change reverts the Podman/Docker detection to prefer Podman.
=> Site-run: prefer `podman*` over `docker*` binaries

service/common/build.gradle.kts, service/common/src/main/java/org/apache/polaris/service/auth/BasePolarisAuthenticator.java, service/common/src/test/java/org/apache/polaris/service/auth/BasePolarisAuthenticatorTest.java
In cases when the persistence store in unavailable or experiencing errors, the authenticator catches exceptions and causes the service to incorrectly return `401`. These exceptions are almost never retried by upstream clients or reverse proxies, so intermittent failures will cause clients to simply shut down. This correctly throws ServiceFailureExceptions in these cases and adds a unit test specifically for the `BasePolarisAuthenticator`
=> Fix BasePolarisAuthenticator to throw service exception during persistence errors

site/content/in-dev/unreleased/quickstart.md
This is to fix https://github.com/apache/polaris/issues/625 where when no default region is set, spark won't be able to perform write.
=> Add default region to spark client for quick start guide

build-logic/src/main/kotlin/polaris-root.gradle.kts
When editing `.gitignore`, IntelliJ warns about a couple directories being ignored but not excluded from being indexed and searched. This change ignores the mentioned directories, except the one for DW, which is going away with #469.
=> IntelliJ: exclude some directories from being indexed

build-logic/src/main/kotlin/polaris-java.gradle.kts, dropwizard/service/build.gradle.kts, extension/persistence/eclipselink/build.gradle.kts, gradle/libs.versions.toml, polaris-core/build.gradle.kts, service/common/build.gradle.kts, tools/config-docs/annotations/build.gradle.kts, tools/config-docs/generator/build.gradle.kts, tools/version/build.gradle.kts
Reduce the amount of dependency declarations in all projects by adding adding the dependencies logback-classic (runtimeOnly) and assertj+mockito (implementation) to all test sources. test-fixtures get junit-jupiter+assertj+mockito as implementation dependencies.
Also ensures that `useJUnitJupiter` is called with the correct version (it implicitly adds the jupiter runtime).
logback-classic is needed at test runtime to actually get logs during test executions, logback-core is a dependency of logback-classic that provides the logback implementation.
=> Build/testing: add `java-test-fixtures` to every Java project & reduce repeated dependency declarations

extension/persistence/eclipselink/build.gradle.kts
```
Reason: Task ':polaris-eclipselink:compileJava' uses this output of task ':polaris-eclipselink:compileQuarkusGeneratedSourcesJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
=> Build: Fix task dependency

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java
These two tests are still failing randomly:
```
jakarta.ws.rs.ProcessingException: java.io.IOException: Connection was closed
at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$4.handle(ClientSendRequestHandler.java:394)
at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$4.handle(ClientSendRequestHandler.java:385)
```
As I don't want to spend a ton of time on these, let's just catch the exception and move on.
=> Fix testRequestBodyTooLarge and testRequestHeaderTooLarge

regtests/run.sh, regtests/t_cli/src/test_cli.py
This PR fixed two problems:
1. Duplicate pytest due to references to non-exist variable (which cause full test to run for each iteration within the every loop)
2. Set default `POLARIS_HOST` to `localhost` (matched to all other test cases as well as avoid one extra set of setting polaris host when running test on local
=> Fix local test environment

quarkus/service/build.gradle.kts
Example stack trace from Java 23:
```
getSubject is supported only if a security manager is allowed
java.lang.UnsupportedOperationException: getSubject is supported only if a security manager is allowed
at java.base/javax.security.auth.Subject.getSubject(Subject.java:347)
at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:588)
at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3888)
at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3878)
at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3666)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:557)
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:366)
at org.apache.iceberg.hadoop.Util.getFs(Util.java:56)
at …
```
=> Make tests work with Java 23

quarkus/service/src/main/resources/application.properties, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/TimedApplicationEventListenerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/TokenUtils.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/TestUtil.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/ratelimiter/TestUtil.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/test/PolarisIntegrationTestFixture.java, service/common/src/main/java/org/apache/polaris/service/context/DefaultRealmContextResolver.java, service/common/src/main/java/org/apache/polaris/service/context/RealmContextConfiguration.java, service/common/src/main/java/org/apache/polaris/service/context/TestRealmContextResolver.java
Now ready for review.
This PR fixes #541 by preventing unknown realms to proceed. 
It's probably not the definitive way of declaring realms, but given that we don't have an API yet to manage realms, the best solution is to declare known realms upfront in the configuration.
This PR also introduces a `TestRealmContextResolver` that is basically the old realm context resolver, and which is used in tests only.
=> Prevent DoS attacks by rejecting unknown realms

gradle/projects.main.properties, tools/container-spec-helper/build.gradle.kts, tools/container-spec-helper/src/main/java/org/apache/polaris/containerspec/ContainerSpecHelper.java
Helper functionality when using testcontainers to resolve the "full" docker image name (name and tag) via a {@code Dockerfile}, which is kept up to date using Renovate.
=> Testing: lookup image version / integration with renovate

quarkus/server/build.gradle.kts
It is highly recommended to enforce the Quarkus platform dependencies. We cannot use `enforcedPlatform()` everywhere else for the Quarkus platform BOM, because that clashes with Spark integration tests, see #727.
=> Enforce Quarkus platform for `:polaris-quarkus-server`

tools/config-docs/generator/src/main/java/org/apache/polaris/docs/generator/SmallRyeConfigs.java, tools/config-docs/site/build.gradle.kts
... also fixes an issue when resolving _inner_ classes leading to `$` to be replaced with `.` (not 100% conformant, but works).
The generated docs can currently only be inspected after running `./gradlew :polaris-config-docs-site:generateDocs` in `tools/config-docs/site/build/markdown-docs`.
=> Generate docs for Quarkus configs

quarkus/admin/README.md, quarkus/admin/build.gradle.kts, quarkus/admin/src/main/java/org/apache/polaris/admintool/BaseCommand.java, quarkus/admin/src/main/java/org/apache/polaris/admintool/BootstrapCommand.java, quarkus/admin/src/main/java/org/apache/polaris/admintool/PolarisAdminTool.java, quarkus/admin/src/main/java/org/apache/polaris/admintool/PolarisVersionProvider.java, quarkus/admin/src/main/java/org/apache/polaris/admintool/PurgeCommand.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/BootstrapCommandTest.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/PurgeCommandTest.java
Small leftovers from #605:
* The root package wasn't accurate (could be confused with packages in `polaris-quarkus-service`)
* The binary distribution wasn't being generated.
=> Admin tool: change root package and create binary distributions

quarkus/service/build.gradle.kts
When starting Polaris with the command:
```bash
./gradlew :polaris-quarkus-service:quarkusRun
```
a `java.lang.ClassNotFoundException: io.opentelemetry.sdk.metrics.internal.export.CardinalityLimitSelector` is encountered.
=> Fix CardinalityLimitSelector ClassNotFoundException when starting Polaris

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisManagementServiceIntegrationTest.java
A few tests were still creating catalog names "manually". Depending on the order of test execution, you could see test failures, e.g. in `ManagementServiceIntegrationTest#testListCatalogs()`:
```
expected:
[]
but was:
[...]
```
Because some catalogs created in previous tests weren't deleted.
=> Fix catalog names in integration tests

quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/ratelimiter/QuarkusRateLimiterFilterConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/ratelimiter/QuarkusTokenBucketConfiguration.java, quarkus/service/src/main/resources/application.properties, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/ratelimiter/RateLimiterFilterTest.java, service/common/src/main/java/org/apache/polaris/service/ratelimiter/DefaultTokenBucketFactory.java, service/common/src/main/java/org/apache/polaris/service/ratelimiter/RateLimiterFilter.java, service/common/src/main/java/org/apache/polaris/service/ratelimiter/TokenBucketConfiguration.java
The filter itself was missing some important annotations.
Its configuration has been simplified slightly as well.
=> Fix RateLimiterFilter configuration

quarkus/server/README.md, quarkus/server/build.gradle.kts, quarkus/server/src/main/java/org/apache/polaris/server/quarkus/package-info.java
Also adds a task named `polarisServerRun` to make it easier to run a Polaris server with Gradle. Note: the server is started with `prod` profile.
Also adds a note about the binary distribution and how to unpack and run it.
=> Ability to run quarkusRun on polaris-quarkus-server

integration-tests/src/main/java/org/apache/polaris/service/it/env/IcebergTokenAccessManager.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisClient.java, integration-tests/src/main/java/org/apache/polaris/service/it/ext/PolarisAccessManager.java, integration-tests/src/main/java/org/apache/polaris/service/it/ext/PolarisServerManager.java
Polaris allows running the integration test suite against an external (managed) server.
This change further enables customizing access tokens for these tests according to the test env. needs.
=> Allow custom access token generation in integration test env

build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/polaris-quarkus.gradle.kts, quarkus/admin/build.gradle.kts, quarkus/server/build.gradle.kts, quarkus/service/build.gradle.kts
This change adds a `polaris-quarkus` build-plugin based on `polaris-server`. It has the specialties for Quarkus based projects, like the implicit `intTest` suite.
This has the nice side effect of not having an unused `intTest` test suite in every project, and removes a bunch of `if`s.
=> Add specialized `polaris-quarkus` build-plugin

integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisClient.java, integration-tests/src/main/java/org/apache/polaris/service/it/ext/PolarisServerManager.java
This was due to the fact that each token fetch created a new client, and the client wasn't closed.
The typical stack trace is:
```
failed to open a new selector
io.netty.channel.ChannelException: failed to open a new selector
at app//io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:179)
...
at app//org.apache.polaris.service.it.ext.PolarisServerManager.createClient(PolarisServerManager.java:64)
at app//org.apache.polaris.service.it.ext.PolarisServerManager.accessManager(PolarisServerManager.java:55)
at app//org.apache.polaris.service.it.env.PolarisClient.obtainToken(PolarisClient.java:118)
at app//org.apache.polaris.service.it.env.PolarisClient.managementApi(PolarisClient.java:88)
at app//org.apache.polaris.service.it.env.PolarisClient.cleanUp(PolarisClient.java:126)
... …
```
=> Fix "too many open files" error when running integration tests

service/common/src/main/java/org/apache/polaris/service/context/RealmContextConfiguration.java
Using a `Set` yields unpredictable results.
=> nit: fix RealmContextConfiguration.defaultRealm

quarkus/service/build.gradle.kts, quarkus/service/src/main/resources/application.properties
This is basically the same issue as #723, just via `@QuarkusIntegrationTest`s, which spawn a separate process. The (JVM) arguments for this need to be specified in a different way.
This also simplifies the Quarksu service build file a little.
=> Make `@QuarkusIntegrationTest`s also work with Java 23

quarkus/service/src/testFixtures/java/org/apache/polaris/service/quarkus/it/QuarkusServerManager.java, service/common/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java
...and not just the default one. This way if the user has many realms, credentials for all of them are printed.
=> Bootstrap all configured realms on startup for in-memory metastore

gradle.properties, settings.gradle.kts
When adding an included build to the Polaris main repo, the (Maven) group ID _must_ be different. This change allows sharing (symling) the `gradle.properties` file with an included build (#785 in this case).
=> Allow Gradle included builds to use a different group ID

quarkus/defaults/build.gradle.kts
`polaris-java` doesn't configure a Java release, `polaris-server` & `polaris-client` do.
=> Use correct `--release` in quarklus-defaults

integration-tests/src/main/java/org/apache/polaris/service/it/env/IcebergHelper.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogViewIntegrationBase.java
Obtain access tokens from `PolarisAccessManager` (#789) before starting Spark sessions as opposed to passing client ID/secret to Spark and relying on the Iceberg REST Client to obtain access tokens.
This makes all "blackbox" integration tests obtain access tokens the same way.
=> Inject auth tokens into Spark sessions

CHAT_BYLAWS.md, CONTRIBUTING.md, site/content/community/_index.adoc
The original link expired after 30 days. This PR updates a link never expired.
=> Update a Slack invite link never expired

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisCredentialsBootstrap.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PrincipalSecretsGenerator.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisCredentialsBootstrapTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PrincipalSecretsGeneratorTest.java, quarkus/admin/src/main/java/org/apache/polaris/admintool/BootstrapCommand.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/BootstrapCommandTest.java, quarkus/service/build.gradle.kts, quarkus/service/src/testFixtures/java/org/apache/polaris/service/quarkus/it/QuarkusServerManager.java, site/content/in-dev/unreleased/configuring-polaris-for-production.md
It turns out that only `root` credentials can be created during bootstrap, since the principal name is hard-coded to `PolarisEntityConstants.getRootPrincipalName()`:
https://github.com/apache/polaris/blob/390f1fa57bb1af24a21aa95fdbff49a46e31add7/polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManagerImpl.java#L612
Because of that, the second element in the quadruplet `realm,name,id,secret` is useless and can be removed.
=> Simplify credentials format when bootstrapping

quarkus/admin/src/main/java/org/apache/polaris/admintool/BootstrapCommand.java, quarkus/admin/src/main/java/org/apache/polaris/admintool/PurgeCommand.java, site/content/in-dev/unreleased/admin-tool.md
=> docs: Polaris Admin Tool

site/content/in-dev/unreleased/telemetry.md
=> Add docs for telemetry (metrics, traces and logging)

README.md
Needs #610 because the instructions for regtests will change.
=> Adapt main README.md to Quarkus

k8/deployment.yaml, run.sh
=> Adapt run.sh script (Polaris on local Kind cluster) to Quarkus

site/content/in-dev/unreleased/admin-tool.md, site/content/in-dev/unreleased/command-line-interface.md, site/content/in-dev/unreleased/configuration.md, site/content/in-dev/unreleased/metastores.md, site/content/in-dev/unreleased/telemetry.md
Keep the link title and page title consistent. They don't have to be the same, but we should try to do that if possible.
=> Docs: Keep the titles consistent

integration-tests/README.md, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisManagementServiceIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogViewIntegrationBase.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisSparkIntegrationTest.java, quarkus/defaults/src/main/resources/application-it.properties, quarkus/defaults/src/main/resources/application-test.properties, quarkus/defaults/src/main/resources/application.properties, quarkus/service/build.gradle.kts, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusSparkIT.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/TimedApplicationEventListenerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogViewTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisCatalogHandlerWrapperAuthzTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusApplicationIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusManagementServiceIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewAwsIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewAzureIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewFileIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewGcpIntegrationTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/ratelimiter/RateLimiterFilterTest.java
This PR cleans up the test profile and makes it converge with the prod profile, which is better as by default, tests are testing the real-life application.
If tests need to customize the configuration, this is now done on a per-test basis.
=> Cleanup test profile and make it converge with prod profile

quarkus/defaults/build.gradle.kts, quarkus/service/build.gradle.kts
If for nothing else, this allows IDEs to enable support for Quarkus in this module, and provide things like autocompletion for properties in `application.properties`, which is very convenient.
=> Mark polaris-quarkus-defaults as a Quarkus module

server-templates/api.mustache
As discussed on the `dev` list, these annotations are no longer relevant. `PolarisAuthorizer` is the source of truth for access control decisions.
=> Remove `@RolesAllowed` from generated API code

getting-started/trino/README.md, getting-started/trino/create-polaris-catalog.sh, getting-started/trino/docker-compose.yml, getting-started/trino/trino-config/catalog/iceberg.properties
Updates Trino example to make it working again. There are 2 major part of changes
1. Configure Polaris container to use test authenticator and token service
2. Add `fs.hadoop.enabled=true` to enable Local Filesystem support for Trino
=> Fix Trino Getting-started Example

service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java
Log them as "DEBUG" instead.
This is to avoid having an "ERROR" log message about "namespace not found" (with a long stack trace) when, for example, Spark executes a `CREATE NAMESPACE myNewNamespace`.
=> Do not log errors for propagated exceptions in IcebergCatalogAdapter

polaris-core/src/main/java/org/apache/polaris/core/context/RealmId.java, service/common/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java
Realm id is a request-scoped component, so we need to copy it to ensure it is available when the task is executed, even if the original realm id is no longer available because the request has completed.
This was being done previously afair, even with Quarkus... I guess it got swollen with the many rebases of #469.
=> Copy RealmId when passing it to TaskExecutorImpl

gradle/libs.versions.toml, quarkus/admin/build.gradle.kts, quarkus/server/build.gradle.kts, quarkus/service/build.gradle.kts
The latest 3.6.2 version seems to fix the issue. I also tested with Postgres using the docker-compose files from #859 and had no issues.
=> Remove dns-java workarounds

getting-started/trino/README.md, getting-started/trino/create-polaris-catalog.sh, getting-started/trino/docker-compose.yml, getting-started/trino/trino-config/catalog/iceberg.properties
With the update in #804, we switched to "default" authenticator in regtest, we can also use the same setup in the trino example. This PR is a follow-up of #868 to use default authenticator in trino example.
=> Update Trino Getting-started example to use default authenticator

.asf.yaml
Adding renovate-bot as a collaborator, so CI doesn't need to be manually approved, removing one manual step that has to be done for each renovate-PR.
=> Add `renovate-bot` as a collaborator

regtests/Dockerfile
Due to the upcoming update of Poetry from version 1.x to 2.x (https://github.com/apache/polaris/pull/873), the minimum Python version requirement will increase to 3.9 (3.8 is EOL already as of 2025). For more details, refer to [Poetry PR #9692](https://github.com/python-poetry/poetry/pull/9692).
This upgrade presents compatibility issues with the current Spark image (`docker.io/apache/spark:3.5.4-python3`), which is based on `eclipse-temurin:11-jre-focal` and uses JDK 11 with Python 3.8. Official Spark images are only available with JDK 11 and JDK 17.
To resolve this, I propose we switch to the JDK 17 version of the Spark image, which uses `eclipse-temurin:17-jammy` and includes Python 3.10. This pull request updates our Spark image accordingly.
=> Spark JDK 17 for python 3.10

site/content/in-dev/unreleased/metastores.md
This is related to a known issue, and a question on Slack. If the HELM charts are correct, this note informs the users.
@adutra does it look good to you ?
@flyrain this is the issue discussed on Slack about EclipseLink "stuck" while loading the `persistence.xml`.
=> Add a note about EclipseLink persistence.xml location

getting-started/eclipselink/docker-compose.yml
This new getting start docker compose is trying to mount local `~/.ivy2` into `/home/spark/.ivy2`. Users can get the following error:
```
spark-sql-1          | Exception in thread "main" java.io.FileNotFoundException: /home/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-83e429a6-2332-4f48-9b70-e9f6e356aeeb-1.0.xml (Permission denied)
spark-sql-1          |  at java.base/java.io.FileOutputStream.open0(Native Method)
spark-sql-1          |  at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
spark-sql-1          |  at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
spark-sql-1          |  at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
spark-sql-1          |  at …
```
=> Change default ivy home to /tmp

LICENSE, aggregated-license-report/build.gradle.kts, build-logic/src/main/kotlin/copiedcode/CopiedCodeCheckerExtension.kt, build-logic/src/main/kotlin/copiedcode/CopiedCodeCheckerPlugin.kt, build-logic/src/main/kotlin/polaris-root.gradle.kts, build.gradle.kts
To ensure that files that are known to be mentioned in `LICENSE` are really mentioned in that file, the Gradle plugin introduced in this change verifies this.
The "magic word" `CODE_COPIED_TO_POLARIS` must be present in such files. The presence of the "magic word" triggers a validation that the path of the containing file, relative to the project root directory, must be mentioned in `LICENSE`, prefixed with `* `.
The plugin checks all source directories in projects that have any Java plugin applied. For other projects, the plugin's extension provides a mechanism to add directory sets similar to how `SourceDirectorySet` works, which is used for the root project.
The plugin must be applied on the root project, it adds itself to all other projects. The introduced `checkForCopiedCode` task is …
=> Check to verify that "copied files" are mentioned in `LICENSE`

integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisApiEndpoints.java, integration-tests/src/test/java/org/apache/polaris/service/it/env/PolarisApiEndpointsTest.java
Currently you're able to supply a base URI to tests but the path is ignored because `resolve()` ignores it. This makes it so tests respect the base path, which allows you to run integration tests against a server where Polaris is under a prefix.
It's not possible to circumvent this by specifying a custom HTTP client either, as the custom HTTP client is only used for the management API and not the catalog API.
=> Make PolarisApiEndpoints respect base URI path prefixes

site/content/community/meetings/_index.adoc
I don't have the google calendar access. But maybe we can use https://groups.google.com/u/0/g/polaris-community-sync instead?
=> Update community sync link

quarkus/defaults/build.gradle.kts, quarkus/defaults/src/main/java/org/apache/polaris/service/defaults/Readme.java, quarkus/server/build.gradle.kts, quarkus/server/src/main/java/org/apache/polaris/server/quarkus/Readme.java
This is to avoid spurious error messages during build, such as: `error: No public or protected classes found to document`
=> Move dummy package-info.java to Readme.java

getting-started/spark/notebooks/Dockerfile
Reported issue: https://apache-polaris.slack.com/archives/C084XDM50CB/p1738620667525009
As part of https://github.com/apache/polaris/pull/726, we change the poetry version from 1.5.0 to 1.8.5. There was a concern around whether we should automate the poetry version for demo (getting-started). After revisited this, I think it makes sense to automate this one as well and use the same version as the one we have in CLI. This is because the demo we have is highly depends on polaris cli (as it copies regtest/client into the container and install it via poetry). Thus, it makes more sense to update both when we update poetry.
=> Fix poetry version used by demo

helm/polaris/LICENSE, helm/polaris/NOTICE
... instead of symlinkng to the repository's root LICENSE file.
This is motivated by the fact that the root LICENSE file now includes notices about the Gradle wrapper. This mention would be inappropriate in a packaged Helm chart since there is no binary files at all in a Helm chart package.
=> Helm chart: use separate LICENSE file

quarkus/defaults/src/main/resources/application-test.properties, quarkus/defaults/src/main/resources/application.properties, site/content/in-dev/unreleased/telemetry.md
Set `quarkus.otel.sdk.disabled` to `true` by default to avoid spurious "connection refused" warnings, for example:
```
2025-01-31 20:51:56,989 WARNING [io.qua.ope.run.exp.otl.sen.VertxGrpcSender] [,] [,,,] (vert.x-eventloop-thread-2) Failed to export TraceRequestMarshalers. The request could not be executed. Full error message: Connection refused: localhost/127.0.0.1:4317
```
Proper trace collection requires running some additional infrastructure, so enabling it by default is not very meaningful. When OTel collectors are available `quarkus.otel.sdk.disabled` can be set to `false` to re-enable tracing at the server start time.
=> Disable OTel SDK by default

site/content/in-dev/unreleased/rest-catalog-open-api.md
This PR is the first follow-up of https://github.com/apache/polaris/pull/906
Updated the website's reference to `generated/bundled-polaris-catalog-service.yaml` instead of `rest-catalog-open-api.yaml`. This change ensures that Polaris-native APIs and models can be removed from `rest-catalog-open-api.yaml` in the next step, allowing it to align with the released version.
cc: @flyrain @jackye1995
=> Update Site's REST Catalog Spec Reference to Bundled Polaris + Iceberg API YAML

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisCatalogHandlerWrapperAuthzTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java, service/common/src/main/java/org/apache/polaris/service/context/CallContextCatalogFactory.java, service/common/src/main/java/org/apache/polaris/service/context/PolarisCallContextCatalogFactory.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
This reverts commit 8a46a451d6207d524cc423e815a119ec320635be.
=> Revert "Remove CallContextCatalogFactory (#592)"

site/hugo.yaml
Solves : https://github.com/apache/polaris/issues/941
CSP policy whats being specified in prod url of polaris is `"script-src 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.apache.org/"` this makes rendering of js script fail due to CSP being enforce.
This change explicitly adds the js script in the CSP policy so that rendering of the page happens correctly. 
please ref this for steps of repro : 
https://github.com/apache/polaris/issues/941#issuecomment-2635142316
I am not sure if this is the best way to fix this, but the above steps fixes the rendering issue !
=> [Site] Explicitly specify CSP policy

regtests/client/python/cli/command/__init__.py, regtests/client/python/cli/command/catalogs.py, regtests/client/python/cli/constants.py, regtests/client/python/cli/options/option_tree.py, regtests/client/python/polaris/management/models/aws_storage_config_info.py, regtests/client/python/test/test_cli_parsing.py, regtests/t_cli/src/test_cli.py
Ass https://github.com/apache/polaris/pull/455 added support for storing AWS region when creating catalog, this PR is to add the support for users to do the same via Polaris CLI.
=> Add support for setting region for AWS via CLI

integration-tests/src/main/java/org/apache/polaris/service/it/env/IcebergHelper.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisApiEndpoints.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/RestApi.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/Server.java, integration-tests/src/main/java/org/apache/polaris/service/it/ext/PolarisIntegrationTestExtension.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisSparkIntegrationTest.java, quarkus/defaults/src/main/resources/application-it.properties, quarkus/defaults/src/main/resources/application.properties, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusFilterPriorities.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/logging/QuarkusLoggingMDCFilter.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/metrics/RealmIdTagContributor.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/tracing/QuarkusTracingFilter.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusApplicationIntegrationTest.java, quarkus/service/src/testFixtures/java/org/apache/polaris/service/quarkus/it/QuarkusServerManager.java, service/common/src/main/java/org/apache/polaris/service/auth/PolarisPrincipalAuthenticatorFilter.java, service/common/src/main/java/org/apache/polaris/service/auth/PolarisPrincipalRolesProviderFilter.java, service/common/src/main/java/org/apache/polaris/service/config/PolarisFilterPriorities.java, service/common/src/main/java/org/apache/polaris/service/context/DefaultRealmContextResolver.java, service/common/src/main/java/org/apache/polaris/service/context/RealmContextConfiguration.java, service/common/src/main/java/org/apache/polaris/service/context/RealmContextFilter.java, service/common/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java, service/common/src/main/java/org/apache/polaris/service/context/TestRealmContextResolver.java, service/common/src/main/java/org/apache/polaris/service/context/UnresolvableRealmContextException.java, service/common/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java, service/common/src/test/java/org/apache/polaris/service/context/DefaultRealmIdResolverTest.java, site/content/in-dev/unreleased/configuring-polaris-for-production.md
Fixes #819. 
Summary of changes:
* Vert.x route filters were converted to JAX-RS `ContainerRequestFilter`
* New `RealmIdFilter` introduced
* `RealmIdResolver` now can throw `UnresolvableRealmException` => maps to HTTP 404
* Added tests in `PolarisApplicationIntegrationTest`
* Fixed default realm name in tests
* Priorities were revisited, new order of execution is shown below:
| Filter | Order | Priority |
| ------|-----| --------|
| `RealmIdFilter` | 1 | 900  |
| `QuarkusLoggingMDCFilter` | 2 | 901 |
| `QuarkusTracingFilter` | 3 | 902 |
| `PolarisPrincipalAuthenticatorFilter` | 4 | 1000 |
| `PolarisPrincipalRolesProviderFilter`  | 5 | 1001 |
| `RateLimiterFilter` | 6 | 5000 |
=> Reorder filters and let RealmContextResolver throw UnresolvableRealmContextException

LICENSE, NOTICE
This PR adds the missing parts in LICENSE/NOTICE found in 0.9.0 rc4.
@rdblue @snazy
=> Add the missing parts (code coming from other projects) in LICENSE & NOTICE

polaris-core/src/main/resources/schemas/policies/system/data-compaction/2025-02-03.json
This PR adds a policy schema for data compaction. Please refer to the [design doc](https://docs.google.com/document/d/1kIiVkFFg9tPa5SH70b9WwzbmclrzH3qWHKfCKXw5lbs/edit?tab=t.0#heading=h.nly223xz13km)  for more context.
Check out #938 if you want to know more about how a policy is validated. 
The policy schemas will be shipped within the `polaris-core` jar file, so that engines or applications can reuse the `polaris-core` for related functionallities, like schema validation. 
The policy will also be pushed in the Apache Polaris website via a link like https://polaris.apache.org/schemas/policies/system/data-compaction/2025-02-03.json, so that it is easy to refer to.
cc @HonahX @jackye1995 @jbonofre @eric-maynard @dennishuo @collado-mike @RussellSpitzer
=> Add data compaction policy schema

site/content/in-dev/unreleased/rest-catalog-open-api.md, spec/README.md, spec/generated/bundled-polaris-catalog-service.yaml, spec/polaris-catalog-apis/notifications-api.yaml
In `notification-api.yaml`, the current reference of `IcebergErrorResponse` is pointing to the wrong model. We should use the one defined in `components/schemas` instead of `components/responses` if we want to customize the example of the corresponding error code.
The incorrect reference cause a problematic `responses-IcebergErrorResponse` model be generated in the `bundled-polaris-catalog-service.yaml`, which cause an error in swagger editor.
=> Spec: Fix incorrect reference to IcebergErrorResponse in notifications-api.yaml

site/content/in-dev/unreleased/polaris-catalog-service.md, site/content/in-dev/unreleased/rest-catalog-open-api.md
Depends on #957 
This PR re-introduce the https://github.com/apache/polaris/pull/935, which is first merged and later reverted (https://github.com/apache/polaris/pull/942) when trying to solve the site issue: https://github.com/apache/polaris/issues/941
The site issue is now fixed with https://github.com/apache/polaris/pull/950 so we are now ready to move forward with the site change.
Updated the website's reference to generated/bundled-polaris-catalog-service.yaml instead of rest-catalog-open-api.yaml. This change ensures that Polaris-native APIs and models can be removed from rest-catalog-open-api.yaml in the next step, allowing it to align with the released version.
cc @flyrain @jackye1995
=> Re-Introduce: Update Site's REST Catalog Spec Reference to Bundled Polaris + Iceberg API YAML

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/EclipseLinkProductionReadinessChecks.java, extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkPersistenceUnit.java, polaris-core/build.gradle.kts, polaris-core/src/main/java/org/apache/polaris/core/config/ProductionReadinessCheck.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/ProductionReadinessChecks.java, service/common/src/main/java/org/apache/polaris/service/auth/JWTRSAKeyPairFactory.java
You can test this feature with the following commands by observing the warnings in the logs:
```shell
./gradlew run  \
-Dpolaris.realm-context.type=test \
-Dpolaris.authentication.token-service.type=test \
-Dpolaris.authentication.authenticator.type=test
./gradlew run \
-Dpolaris.authentication.token-broker.type=symmetric-key \
-Dpolaris.authentication.token-broker.symmetric-key.secret=secret
./gradlew run  \
-Dpolaris.persistence.type=eclipse-link  \
-PeclipseLinkDeps=org.postgresql:postgresql:42.7.4
```
=> Add production readiness checks

CHAT_BYLAWS.md, CONTRIBUTING.md, README.md, site/content/_index.adoc, site/content/community/_index.adoc, site/hugo.yaml
As discussed on the mailing list, we have a consensus to "promote" Slack as our main chat service.
This PR removes mention to Zulip in favor of Slack.
=> Remove ref to Zulip (in favor of Slack)

README.md, site/content/in-dev/unreleased/configuration.md
=> Add configuration notes to README.md

regtests/client/python/cli/command/catalogs.py, regtests/client/python/cli/options/option_tree.py, regtests/client/python/test/test_cli_parsing.py, regtests/run.sh, regtests/t_cli/src/test_cli.py
At head, currently "polaris catalogs update" is broken whenever storage_config is modified; just like updating properties or other top-level fields, the storage_config must be initially built off of the existing storage_config, and edits must be applied client-side.
This fixes --allowed-location and --region in "catalogs update".
Additionally, there was a recent regression where a "fix" in run.sh got rid of previously "accidentally" running the base directory and thus pulling in client/python/test. Now, make run.sh explicitly run the client/python/test directory to get all the pytests in there as a special case aside from all the t_* tests.
=> Add support for updating catalog region, fix catalogs update, fix running client pytests

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTRSAKeyPairTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTSymmetricKeyGeneratorTest.java, service/common/src/main/java/org/apache/polaris/service/auth/DefaultOAuth2ApiService.java, service/common/src/main/java/org/apache/polaris/service/auth/JWTBroker.java, service/common/src/main/java/org/apache/polaris/service/auth/NoneTokenBrokerFactory.java, service/common/src/main/java/org/apache/polaris/service/auth/TokenBroker.java, service/common/src/test/java/org/apache/polaris/service/auth/DefaultOAuth2ApiServiceTest.java
Iceberg supports multiple token types during a token exchange and also supports sending client secret without a client id. The default Polaris implementation doesn't support most of this, but the `TokenBroker` interface does allow for implementations that do. This merely updates the `DefaultOAuth2ApiService` to delegate to the `TokenBroker` to support these cases.
=> Update DefaultOAuth2ApiService to support multiple token types and client secret without id

.gitignore, polaris, regtests/client/python/cli/command/__init__.py, regtests/client/python/cli/command/profiles.py, regtests/client/python/cli/constants.py, regtests/client/python/cli/options/option_tree.py, regtests/client/python/cli/options/parser.py, regtests/client/python/cli/polaris_cli.py, regtests/polaris-reg-test, site/content/in-dev/unreleased/command-line-interface.md
Helper:
```
➜  polaris git:(cli_profile) ./polaris profiles --help
input: polaris profiles --help
options:
profiles
create
Positional arguments:
profile
delete
Positional arguments:
profile
get
Positional arguments:
profile
list
update
Positional arguments:
profile
```
Create profile:
```
➜  polaris git:(cli_profile) ./polaris profiles create dev
Polaris Client ID: root
Polaris Client Secret: 712f1f6daf16326fd794607ef1ce90d9
Polaris Host [localhost]:
Polaris Port [8181]:
Polaris profile dev created successfully.
```
Get profile:
```
➜  polaris git:(cli_profile) ./polaris profiles get dev
Polaris profile dev: {'client_id': 'root', 'client_secret': '712f1f6daf16326fd794607ef1ce90d9', 'host': 'localhost', 'port': 8181}
```
List profiles:
```
➜  polaris git:(cli_profile) ./polaris profiles …
```
=> Add profile support for cli

.github/renovate.json5
This PR proposes:
* to schedule renovatebot daily before 4 AM
* to add `renovatebot` label to easily filter PRs and emails
=> Add label to easily filter renovatebot PR notifications

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java
Polaris currently returns a 500 error for the `registerTable` catalog API if the provided metadata file path does not contain any slashes.
- `lastIndexOf("/")` will return `-1`, causing an `Range [0, -1) out of bounds` error when calling `substring()`.
- This change handles this case & returns a 400 instead.
=> Fix: check for slashless metadata paths

helm/polaris/README.md, helm/polaris/README.md.gotmpl
This is is no longer needed (nor make sense) as we are not longer using grep command to filter out the verbose messages (as the issue got fixed with LICENSE file that is not a soft link)
=> Doc: Remove lines that are not no longer needed

helm/polaris/templates/service.yaml, helm/polaris/tests/service_test.yaml
Added extra conditional check to #626  to add check to NodePort before adding the port.
fix: #981
=> (fix): add conditional for nodePort check

README.md, getting-started/eclipselink/README.md, getting-started/spark/README.md, getting-started/telemetry/README.md, getting-started/trino/README.md, helm/polaris/README.md, helm/polaris/README.md.gotmpl, quarkus/admin/README.md, quarkus/server/README.md, regtests/README.md, run.sh, site/content/in-dev/unreleased/admin-tool.md, site/content/in-dev/unreleased/quickstart.md
This PR fixed inconsistent image build issue after a successful build is made already. It contains two changes:
1. add `clean` to the build command
2. disable gradle build cache when building image
Here are the test:
```
➜  polaris git:(main) docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
➜  polaris git:(main) ./gradlew :polaris-quarkus-server:assemble :polaris-quarkus-admin:assemble \
-Dquarkus.container-image.build=true \
-PeclipseLinkDeps=org.postgresql:postgresql:42.7.4 \
...
BUILD SUCCESSFUL in 38s
115 actionable tasks: 98 executed, 17 up-to-date
➜  polaris git:(main) docker images
REPOSITORY                  TAG                         IMAGE ID       CREATED          SIZE
apache/polaris-admin-tool   1.0.0-incubating-SNAPSHOT   4162495a3d93   29 seconds ago   535MB …
```
=> Fix inconsistent image build issue

regtests/client/python/cli/options/parser.py, regtests/client/python/test/test_cli_parsing.py, regtests/t_cli/src/test_cli.py
Currently the CLI parsing is too pessimistic and throws an error if it detects '=' in the parsed value of a property. However, the split 1 semantics are already standard behavior for most parsers where the right-hand-side is allowed to contain '='.
This commonly comes up if the value is itself a comma-separated kv list or if it the value is a base64-encoded string.
=> Allow Polaris CLI to set property values that contain '='

regtests/client/python/cli/command/principals.py, regtests/client/python/cli/constants.py, regtests/client/python/cli/options/option_tree.py, site/content/in-dev/unreleased/command-line-interface.md
This is one of the purposed CLI option in https://github.com/apache/polaris/issues/989 (item 1). This new subcommand will display the entities relation a given principal has.
Here is a sample output for quickstart_user based on our example:
```json
{
"principal": "quickstart_user",
"principal_roles": [
{
"name": "quickstart_user_role",
"catalog_roles": [
{
"name": "quickstart_catalog_role",
"catalog": "quickstart_catalog",
"privileges": [
{
"type": "catalog",
"privilege": "CATALOG_MANAGE_CONTENT"
}
]
}
]
}
]
}
```
Here is another example for the same user but with additional access, principal roles, and catalogs:
```json
{
"principal": "quickstart_user",
"principal_roles": [
{
"name": "demo_user_role",
"catalog_roles": [
{
"name": "demo_catalog_role",
"catalog": "demo_catalog", …
```
=> CLI: add subcommand access for principals

site/content/community/proposals.adoc, site/hugo.yaml
Proposals page is a adoc file. So this PR uses the right links format for adoc.
=> Use correct link format for adoc and update menu title for proposals

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/ManifestFileCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/DefaultFileIOFactory.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/FileIOFactory.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/FileIOUtil.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/WasbTranslatingFileIOFactory.java, service/common/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java, service/common/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java, service/common/src/main/java/org/apache/polaris/service/task/TaskFileIOSupplier.java, service/common/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java, service/common/src/testFixtures/java/org/apache/polaris/service/catalog/io/MeasuredFileIOFactory.java
This appeared to be some leaky divergence that occurred after CallContext had been removed, but PolarisMetaStoreSession really is only a low-level implementation detail that should never be handled by BasePolarisCatalog/FileIOFactory.
This plumbs CallContext explicitly into the FileIOFactory and FileIOUtil methods and thus removes a large source of CallContext.getCurrentContext calls; now the threadlocal doesn't have to be set at all in BasePolarisCatalogTest.
=> Remove PolarisMetaStoreSession from FileIOFactory/FileIOUtil in favor of CallContext

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java, service/common/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java
Presently cleaning up of ManifestList is missing when we call the table drop with purge. This change aims to fix this issue by adding manifest list also to the metadata cleanup part of the task. 
Solve bug reported via: https://github.com/apache/polaris/issues/967
Updated existing test cases
=> Service: Cleanup Iceberg Manifest list on Purge

site/content/in-dev/unreleased/quickstart.md
I noticed a very small typo in the quickstart doc, which this PR addresses.
=> Fix small quickstart typo

build.gradle.kts, integration-tests/README.md, quarkus/admin/README.md, quarkus/defaults/README.md, quarkus/server/README.md, spec/README.md
By default, all files in the source distribution should contain the ASF header, including md files.
This PR enables rat check on md files and fix some md files.
=> Enable rat check on md files and fix the existing ones

build-logic/src/main/kotlin/polaris-java.gradle.kts
=> build-logic: let javadoc depend on jandex

.asf.yaml
Prashant would like to contributor on GitHub Issues. Adding him as collaborator allows us to assign issue to him 😄
=> Add Prashant in the collaborators list

quarkus/admin/src/main/resources/application.properties, quarkus/defaults/src/main/resources/application.properties, quarkus/server/src/main/resources/application.properties
As discussed in latest community meeting, having proprties that are settable only at build time can be surprising to Polaris users and contributors.
This change attempts to help with that matter by grouping build time properties into dedicated sections inside application.properties files and adding comments to clarify their usage.
=> Group application.properties by build time / run time

helm/polaris/README.md, helm/polaris/tests/deployment_test.yaml, helm/polaris/values.yaml
This change enforces a strong default security context for both the pod and the container. Polaris default Docker images are compatible with such contexts.
Requires #1079
=> Helm chart: enforce strong security contexts by default

polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/MetaStoreManagerFactory.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java
Make the `purgeRealms` method return the purge results.
These changes are a prerequisite for #878 and #887.
=> MetaStoreManagerFactory: make purgeRealms() return purge results

service/common/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java, service/common/src/test/java/org/apache/polaris/service/context/DefaultRealmIdResolverTest.java
According to the RFC, HTTP headers should be case-insensitive. To support this, we need to avoiding doing string comparison against a case-sensitive map.
=> Treat headers as case-insensitive during RealmContext resolution

polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java
`EntityCache` can be `null` now, adopt the change to `Resolver`
=> Annotate `cache` as `@Nullable`

quarkus/admin/src/main/java/org/apache/polaris/admintool/BootstrapCommand.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/BootstrapCommandTest.java
This alters the bootstrap command to require either explicit credentials or a new flag `--print-credentials`.
Fixes #219 
Credentials are now printed during bootstrap when it's enabled:
```
realm: default-realm root principal credentials: 2b98107557bcce20:f74281319ac8519ef30cbced6563223b
```
=> Prevent the bootstrap command from leaving root credentials unrecoverable

extension/persistence/eclipselink/src/main/resources/META-INF/persistence.xml
Remove the unused ModelEntityDropped config from eclipselink reference which was removed as part of https://github.com/apache/polaris/pull/1070/files#diff-66d555be4a9e71a59752d79ee810d7935ab3d10c086b5d580f90db637d477e6e
=> Cleanup: Remove unused class

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java
We [recently added](https://github.com/apache/polaris/commit/5c3c7d6e80bb13131317a2f4cc7f63369821a997) the loadCredentials endpoint, but it throws a 501. This PR adds support for this endpoint.
Fixes #464
=> Add support for the loadCredentials endpoint

helm/polaris/ci/fixtures/persistence.yaml
From https://github.com/apache/polaris/pull/1092/files, we added `eclipselink.session.customizer` and `eclipselink.transaction.join-existing` in persistence.yaml, this PR added the same for helm setup.
=> Add fix from 1092 to helm

quarkus/defaults/src/main/resources/application.properties, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, service/common/src/main/java/org/apache/polaris/service/auth/DefaultActiveRolesProvider.java
When debugging with Quarkus, @RichardLiu2001 and I noticed that `DefaultActiveRolesProvider` doesn't have an `Identifier` currently. This means that if we add a new implementation of `ActiveRolesProvider`, the runtime can fail with:
```
jakarta.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type org.apache.polaris.service.auth.ActiveRolesProvider and qualifiers [@Default]
```
=> Add Identifier annotation to DefaultActiveRolesProvider

regtests/client/python/cli/constants.py, regtests/client/python/cli/options/parser.py, regtests/client/python/cli/polaris_cli.py
This feature is requested from https://github.com/apache/polaris/issues/1113. Currently we don't support pass in proxy info. 
Here is how this PR is being validated:
Terminal 1:
```
(venv) yong@DESKTOP:~/k8s/polaris(main)$ pip install mitmproxy
(venv) yong@DESKTOP:~/k8s/polaris(proxy_support)$ mitmproxy
```
```
yong@DESKTOP:~/k8s/polaris(main)$ ./gradlew run
```
```
yong@DESKTOP:~/k8s/polaris(proxy_support)$ ./polaris --profile dev catalogs list
yong@DESKTOP:~/k8s/polaris(proxy_support)$ echo $?
0
yong@DESKTOP:~/k8s/polaris(proxy_support)$ ./polaris --profile dev --proxy http://localhost:8080 catalogs list
yong@DESKTOP:~/k8s/polaris(proxy_support)$ echo $?
0
```
Now here is the output from terminal 1:
=> Add proxy option for CLI

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/BasePersistence.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/TransactionWorkspaceMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/cache/EntityCache.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/AbstractTransactionalPersistence.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/PolarisMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/PolarisTreeMapMetaStoreSessionImpl.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisCredentialVendor.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/EntityCacheTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTRSAKeyPairTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTSymmetricKeyGeneratorTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, service/common/src/main/java/org/apache/polaris/service/auth/BasePolarisAuthenticator.java, service/common/src/main/java/org/apache/polaris/service/auth/DefaultActiveRolesProvider.java, service/common/src/main/java/org/apache/polaris/service/auth/JWTBroker.java, service/common/src/main/java/org/apache/polaris/service/auth/TestOAuth2ApiService.java, service/common/src/main/java/org/apache/polaris/service/auth/TokenBroker.java, service/common/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java, service/common/src/test/java/org/apache/polaris/service/auth/BasePolarisAuthenticatorTest.java
This is mainly needed for the upcoming NoSQL implementation.
Also, this change harmonizes the API parameters across all lookup methods.
This change induces changes in the MetaStore Manager API and related classes. In most top-level call sites the required extra information is already available.
A minor inefficiency exists in PolarisAdminService, but it will only manifest in backends that do rely on the new parameter to perform lookups, plus the affected use case is not expected to be frequent (Admin API queries to obtain existing grants for a catalog role).
=> Added typeCode to BasePersistence.lookupEntity

polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java
Following up on #1055, this refactoring does not remove `EntityCache`, but allows it to be `null` in principle, should a particular MetaStoreManagerFactory implementation choose not to use an `EntityCache`.
* Remove bean producer for `EntityCache` (beans cannot be `null`).
* Harmonize all `PolarisEntityManager` producers (explicit and CDI) to go through `RealmEntityManagerFactory` (tangential to the cache being null, but related).
=> Allow MetaStoreManagerFactory to produce `null` `EntityCache`

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java
This change is in anticipation of NoSQL persistence implementations.
A MetaStore manager does not have to use entity caching and provide fresh results from all load method, thus making the `bulkValidate` call redundant in `Resolver`.
This change does not alter existing behaviour, but enables future optimizations.
=> Allow MetaStore manager to declare whether bulk reload is necessary

service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java
Removes the unused `refreshCredentials` private methods from `BasePolarisCatalog`. `BasePolarisCatalog` currently uses the `FileIOUtil` method instead: https://github.com/apache/polaris/blob/0ab9978de644a94f7bf2d067a2f04b2a4c017ac6/service/common/src/main/java/org/apache/polaris/service/catalog/io/FileIOUtil.java#L78
=> Remove unused `refreshCredentials` methods on `BasePolarisCatalog`

site/content/downloads.md, site/hugo.yaml
Add 0.9.0 is a "thin release", I'm adding a downloads page on the website to give visibility and download sources for our users.
=> Add downloads page on the website

quarkus/service/build.gradle.kts
Useful example is to run a Quarkus integration test with the `-Dquarkus.test.arg-line=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005` system property to eventually attach a debugger.
=> Allow passing `quarkus.*` system properties to Quarkus ITs

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisEntityManager.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisCatalogNoEntityCacheTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisCatalogWithEntityCacheTest.java
Following up on #1131:
* Fix annotations in `PolarisEntityManager`
* Add unit tests for running without `EntityCache`
=> Fix annotations in `PolarisEntityManager`

polaris
When the polaris CLI script performs first-time setup, it creates `polaris-venv` based on the dependencies configured in poetry. However, if there happens to be an existing poetry.lock file in the directory then the correct dependencies will not get installed. To remedy this, we should clear out any pre-existing poetry.lock file before generating a `polaris-venv` and installing dependencies there.
<hr>
**Without this change:**
```bash
rm -rf polaris-venv
rm -rf poetry.lock
touch poetry.lock
./polaris -h
```
Yields:
```
ModuleNotFoundError: No module named 'pydantic'
```
While
```bash
rm -rf polaris-venv
rm -rf poetry.lock
./polaris -h
```
Yields:
```
First time setup complete.
input: polaris -h
...
```
<hr>
**After this change:**
```bash
rm -rf polaris-venv
rm -rf poetry.lock
./polaris -h …
```
=> Clear the poetry.lock file during first-time setup of the polaris CLI

polaris-core/src/main/java/org/apache/polaris/core/exceptions/FileIOUnknownHostException.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/DefaultFileIOFactory.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/ExceptionMappingFileIO.java, service/common/src/main/java/org/apache/polaris/service/exception/IcebergExceptionMapper.java, service/common/src/test/java/org/apache/polaris/service/catalog/io/ExceptionMappingFileIOTest.java, service/common/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java, service/common/src/test/java/org/apache/polaris/service/exception/IcebergExceptionMapperTest.java
Typically when a S3/GCS bucket isn't found, you'll get a 404. Azure seems to be unique, in that it provisions a subdomain for each "blob container", so non-existence manifests as a DNS resolution failure instead. This makes the Polaris return code consistent.
=> File IO UnknownHostException 404

polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java
The `StorageCredentialCache` currently uses a custom `Expiry`. I think that this works correctly.
IMHO using a built-in one that Caffeine provides, like `Expiry.writing` reads better - this is what this PR proposes.
=>  Use Caffeine's `Expiry.creating` for `StorageCredentialCache`

polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/TransactionWorkspaceMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/PolarisMetaStoreManagerImpl.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java, service/common/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java
* Use `PolarisBaseEntity` for the entity that is acted upon in `renameEntity` and `dropEntityIfExists`
* This is in line with existing parameters for "acted upon" entities in other methods.
* Simplify TaskExecutorImpl (avoid object copy)
* Existing call sites have the required data available.
=> Harmonize parameters in PolarisMetaStoreManager

api/polaris-catalog-service/build.gradle.kts, spec/generated/bundled-polaris-catalog-service.yaml, spec/polaris-catalog-apis/policy-apis.yaml, spec/polaris-catalog-service.yaml
The PR adds definition of policy management APIs designed in https://docs.google.com/document/d/1kIiVkFFg9tPa5SH70b9WwzbmclrzH3qWHKfCKXw5lbs/edit?tab=t.0#heading=h.nly223xz13km
The first set of APIs includes:
- createPolicy
- getPolicy
- updatePolicy
- dropPolicy
- listPolicies
- attachPolicy
- detachPolicy
This PR also provides a models and example result to serve as a start point of discussion. All implementations and definition are subject to be changed upon further discussion.
Convenient viewer: https://editor-next.swagger.io/?url=https://raw.githubusercontent.com/HonahX/polaris/refs/heads/honahx_policy_management_apis/spec/generated/bundled-polaris-catalog-service.yaml
cc: @flyrain
=> Polaris Catalog Spec: Policy Management Apis

polaris-core/src/main/java/org/apache/polaris/core/persistence/MetaStoreManagerFactory.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/test/PolarisIntegrationTestFixture.java, service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/context/DefaultCallContextResolver.java
No functional change.
* Adjust the type parameter to the Persistence supplier to cover all possible implementation types.
* Remove unnecessary fields from IcebergCatalogAdapter
* Adjust types at call sites of `getOrCreateSessionSupplier`.
=> Generify MetaStoreManagerFactory.getOrCreateSessionSupplier

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/BatchFileCleanupTaskHandlerTest.java
In #516, incorrect type of NotNull (`org.jetbrains.annotations.NotNull`) was used in the test, which caused errors in CI. This fix PR replaces it with the correct one `jakarta.annotation.Nonnull`
=> Fix CI error for NotNull import

gradle/libs.versions.toml, polaris-core/build.gradle.kts, polaris-core/src/main/java/org/apache/polaris/core/PolarisDefaultDiagServiceImpl.java, polaris-core/src/main/java/org/apache/polaris/core/PolarisDiagnostics.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java
The main intention of this change is to avoid confusion between Jetbrains' `@NotNull` and Jakarta's `@Nonnull` (the latter is standard in the Polaris codebase).
As a side effect `@Contract` is no longer available. However, its value is realised only in tools that support it and Polaris builds do not rely on it for producing artifacts. For a human being the value of `@Contract` appears to be negligible compared to javadoc. Therefore, in the interest of keeping annotation dependencies concise, `@Contract` lines are removed.
Jetbrains' `@VisibleForTesting` is converted to the same annotation from Guava (which is also standard in the Polaris codebase).
=> Remove jetbrains-annotations

polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisGrantManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/TransactionWorkspaceMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/PolarisMetaStoreManagerImpl.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java
Previously strongly typed methods redirected to typeless lookup methods, while implementations had only the typeless variant.
This change moves the redirects from strongly typed methods to existing typeless methods in implementations.
As a result it is possible to simplify the interface by removing typeless lookup methods.
Existing call sites all have strongly typed parameters available and use the typed lookup methods now.
For context: This refactoring seems valuable by itself, but it is also needed for the upcoming NoSQL implementations for reasons similar to #1112
=> Simplify PolarisGrantManager

polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisEntityType.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PolicyEntity.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PolicyType.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PredefinedPolicyType.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PredefinedPolicyTypes.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/org/apache/polaris/core/policy/PolicyEntityTest.java, polaris-core/src/test/java/org/apache/polaris/core/policy/PolicyTypeTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java
This PR introduces basic classes for supporting Policy Store in Polaris, as discussed in https://github.com/apache/polaris/issues/1059.
1. PolicyEntity – Represents a policy object in Polaris.
2. PolicyType – Defines a category of policies, which can be either predefined or custom (user-defined). Currently only predefined classes supported
This will be the first step to unblock all other Policy PRs and discussions
cc: @flyrain
=> Policy Store: Add PolicyEntity and PolicyTypes

regtests/run.sh, regtests/run_spark_sql.sh, regtests/setup.sh
Three changes in this PR:
1. Change download URL for spark distribution
2. Update spark version to 3.5.5 (all other places are changed except this one)
3. Cleanup tarball after extracted and add check after download (in case failed download, abort the regtests)
Explanation for item 1:
Currently it is downloading spark via following link:
```
https://dlcdn.apache.org/spark/${SPARK_VERSION}/${SPARK_DISTRIBUTION}.tgz
```
This URL will only return the valid download tgz when the version is latest (as the older version is not accessible from this link...in this case, https://www.apache.org/dyn/closer.lua/spark/spark-3.5.4/spark-3.5.4-bin-hadoop3.tgz).
Thus, it is better to download from archive link instead:
```
https://archive.apache.org/dist/spark/${SPARK_VERSION}/${SPARK_DISTRIBUTION}.tgz …
```
=> Fix spark download and add check/cleanup

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkSessionCustomizer.java, site/content/in-dev/0.9.0/metastores.md, site/content/in-dev/unreleased/metastores.md
Currently we are using EclipseLink 4.0.5 but we still ref to 2.5/2.6 version. Since EclipseLink 4.0.x, EclipseLink has changed their doc to Asciidoc format (ref: https://github.com/eclipse-ee4j/eclipselink/pull/1746). The refs we are using in 2.5/2.6 are still valid, but it may contains outdated info as people want to dig deeper into certain settings.
=> Update EclipseLink doc to 4.0

.github/renovate.json5
Quarkus-platform releases happen some time after the "actual" Quarkus release, which causes "broken" CI for Renovate PRs against for example the Quarkus Gradle plugin.
This change groups all Quarkus dependencies together to consistently bump all Quarkus-platform dependencies at once.
=> Renovate: Group all Quarkus dependencies

build-logic/src/main/kotlin/polaris-java.gradle.kts, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusManagementServiceIT.java, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewAwsIT.java, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewAzureIT.java, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewFileIT.java, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewGcpIT.java, tools/version/src/jarTest/java/org/apache/polaris/version/TestPolarisVersion.java
Only runs on 'main', 'test', 'testFixtures', but not on others like 'intTest'. This change fixes this.
=> Let 'spotless' run on all java source directories

polaris-core/src/main/java/org/apache/polaris/core/config/BehaviorChangeConfiguration.java
The BehaviorChangeConfiguration added in #1124 as an example actually has the wrong config name; this fix is also picked up in #1170 but per [this comment](https://github.com/apache/polaris/pull/1170#discussion_r1999710195) I've opened this PR as a small fix focused on adjusting the config.
=> Fix behavior change config VALIDATE_VIEW_LOCATION_OVERLAP

extension/persistence/eclipselink/src/test/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreManagerTest.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapMetaStore.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapTransactionalPersistenceImpl.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/EntityCacheTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisTreeMapAtomicOperationMetaStoreManagerTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisTreeMapMetaStoreManagerTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, service/common/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java
This PR is renaming only without logic changes. The goal is to make the name consistent within the package `org.apache.polaris.core.persistence.transactional`.
cc @singhpk234 @dennishuo
=> Rename classes in transactional persistence package

build-logic/src/main/kotlin/polaris-java.gradle.kts, getting-started/spark/notebooks/Dockerfile, quarkus/defaults/src/main/resources/application.properties, regtests/Dockerfile, site/docker/Dockerfile
=> Use 'en-us' in all `Dockerfile`s, Gradle `Test` tasks and Quarkus defaults

service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandlerWrapper.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
With the revert of b84f4624db8d0bd5b8920b0df719bcc15666008f by ccf25df7b055e9d232b88a3f6fe8b4e0a2ab035a, we lost an extra benefit that was included in the reverted commit: a fix for the fact that `IcebergCatalogHandlerWrapper` does not always close its underlying `Catalog`, thus relying on `CallContext` to play the role of the "sweeper car" and close everything that was left unclosed at the end of the request processing.
This PR re-applies that fix again.
If this change gets accepted, we could envisage removing `CallContext.closeables()` – as the main purpose of this method is to close unclosed catalogs.
=> IcebergCatalogAdapter: close underlying catalog consistently

helm/polaris/README.md, helm/polaris/values.yaml
```
$ curl -v http://polaris.io
> GET / HTTP/1.1
> Host: polaris.io
> 
* Request completely sent off
< HTTP/1.1 500 Domain Not Found
< 
<html>
<head>
<title>Fastly error: unknown domain polaris.io</title>
</head>
<body>
<p>Fastly error: unknown domain: polaris.io. Please check that this domain has been added to a service.</p>
```
=> Fix CI build after polaris.io

quarkus/admin/src/test/java/org/apache/polaris/admintool/BootstrapCommandTestBase.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/PurgeCommandTestBase.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/el/EclipselinkBootstrapCommandTest.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/el/EclipselinkProfile.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/el/EclipselinkPurgeCommandTest.java
... and make the PG test-resource non-global.
=> Move polaris-admin-tool tests to separate package

quarkus/admin/src/main/java/org/apache/polaris/admintool/PurgeCommand.java
=> Let `PurgeCommand` inspect the results

gradle/projects.main.properties, tools/misc-types/build.gradle.kts, tools/misc-types/src/main/java/org/apache/polaris/misc/types/memorysize/MemorySize.java, tools/misc-types/src/main/java/org/apache/polaris/misc/types/memorysize/MemorySizeConfigConverter.java, tools/misc-types/src/main/java/org/apache/polaris/misc/types/memorysize/MemorySizeJackson.java, tools/misc-types/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module, tools/misc-types/src/test/java/org/apache/polaris/misc/types/memorysize/TestMemorySize.java, tools/misc-types/src/test/resources/logback-test.xml
The type allows human friendly memory size specifications like `32k` or `64M`, including support for smallrye-config and Jackson.
=> Add type and converters for `MemorySize`

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusApplicationIntegrationTest.java, service/common/src/main/java/org/apache/polaris/service/auth/JWTBroker.java
Two fixes in this PR:
* `JWTBroker` was expecting  the `requested_token_type` field to be present, but this field is optional, and the Iceberg REST client never includes it; as a consequence, token refreshes were failing.
* when `JWTBroker.verify()` throws, the exception was being propagated to `IcebergExceptionMapper`, which results in an incorrect OAuth response:
```json
{
"error" : {
"message" : "Failed to verify the token",
"type" : "NotAuthorizedException",
"code" : 401
}
}
```
The correct payload would be:
```json
{
"error" : "unauthorized_client",
"error_description" : "The client is not authorized"
}
```
I included tests for both, although it's hard to test the path where the decoded JWT is invalid.
=> JWTBroker: fix refresh token logic

client/python/cli/polaris_cli.py
When running a command like this in the Polaris CLI:
```
./polaris \
--access-token 'principal:root;realm:default-realm' \
--client-id abc \
--client-secret xyz \
catalogs \
create test_catalog \
--storage-type file \
--default-base-location 'file:///tmp/polaris'
```
We reject the invocation because it's ambiguous whether the user would like to use the access token or the client ID & secret.
However, it's also possible for the user to specify client ID & secret via environment variables. In that case, we reject commands even like this:
```
./polaris \
--access-token 'principal:root;realm:default-realm' \
catalogs \
create test_catalog \
--storage-type file \
--default-base-location 'file:///tmp/polaris'
```
I believe that we should allow situations where the user explicitly provides one …
=> Fix overzealous check in the Polaris CLI

helm/polaris/README.md, helm/polaris/README.md.gotmpl, helm/polaris/ci/fixtures/postgres.yaml
Follow up PR based on chart in Slack: https://apache-polaris.slack.com/archives/C084QSKD6S2/p1742395080998099
=> Doc: catalog bootstrap steps for helm deployment

service/common/build.gradle.kts, service/common/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyServiceImpl.java
As part of the generic tables implementation, I added `polaris-api-catalog-service` as a dependency in `polaris-service-common`. What I found was that the interfaces such as `PolarisCatalogPolicyApiService` require scope-annotated implementations or else errors like this will occur during initialization:
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.apache.polaris.service.catalog.api.PolarisCatalogPolicyApiService and qualifiers [@Default]
- injection target: parameter 'service' of …
```
=> Implement service interfaces for policies & generic tables

api/iceberg-service/build.gradle.kts, api/management-model/build.gradle.kts, api/management-service/build.gradle.kts, api/polaris-catalog-service/build.gradle.kts
In order to publish artifact to Maven (local or remote), we have to use `processResources` task.
This task has to depend to `openApiGenerate` to be valid.
=> Add openApiGenerate task as dependency for processResources

service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java
An error message that's currently printed during a resolution failure assumes there's an entity that could not be resolved. However, in other code paths such as [this one](https://github.com/apache/polaris/blob/e619a0075bcd13eef1e139f608625c22ab5b50de/polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java#L755), the value of `ResolverStatus.getFailedToResolvedEntityName` may be null. Accordingly, this PR fixes some error messages that rely on this value.
[Other places that print a similar error are already resilient to a null being in this field](https://github.com/apache/polaris/blob/e619a0075bcd13eef1e139f608625c22ab5b50de/service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java#L260).
=> Better error message when sibling resolution fails

regtests/t_pyspark/src/conftest.py, regtests/t_pyspark/src/test_spark_sql_s3_with_privileges.py
Minor Updates to PySpark Reg Tests
Each test directly cleans the artifacts it created.
Optional bucket prefix location has a UUID appended to allow for multiple runs against the same instance not conflicting if a previous run didn't get cleaned up.
For testing - RAN 
`./gradlew clean :polaris-quarkus-server:assemble -Dquarkus.container-image.build=true --no-build-cache                                                            docker compose -f ./regtests/docker-compose.yml up --build --exit-code-from regtest`
`exported AWS_STORAGE_BUCKET, AWS_BUCKET_BASE_LOCATION_PREFIX, AWS_ROLE_ARN,AWS_TEST_ENABLED`
Saw REG tests complete with exit code 0
=> PySpark Reg Test Updates

.asf.yaml
With https://github.com/apache/infrastructure-asfyaml/pull/55 I added the `require_last_push_approval` option to `.asf.yaml` (it was not possible to change it before).
This PR updates `.asf.yaml` with:
* `dismiss_stale_reviews: true`
* `require_last_push_approval: false`
See https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#branch-protection for details.
=> Update .asf.yaml adding dismiss_stale_reviews to true and require_last_push_approval to false

polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheEntry.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java
@XJDKC brought it to my attention that [different versions of the Iceberg client expect different credential keys for Azure credentials](https://github.com/apache/iceberg/commit/b07455a940538eda5f27bd4b1b87e49b121346e4#diff-b6b966659def85b3107d8db1f7c3e23ca7c84b9139123114b21dd4df85942664R114). In order to support both variations, Polaris should vend Azure credentials both with and without the host suffixes like `dfs.core.windows.net`.
=> Vend Azure credentials compatible with Iceberg 1.7

CONTRIBUTING.md
As discussed on the mailing list, this PR adds a quick note about replying to not `nit` or `minor` comments in PRs.
=> Add a note about nit/minor comments

quarkus/admin/build.gradle.kts, quarkus/admin/distribution/LICENSE, quarkus/admin/distribution/NOTICE, quarkus/server/build.gradle.kts, quarkus/server/distribution/LICENSE, quarkus/server/distribution/NOTICE
The distributions (admin and server) will be published in the next release (both on dist.apache.org and Nexus).
As for all distributed artifacts, they have to contain complete and accurate `LICENSE` and `NOTICE` files.
This PR updates `LICENSE` and `NOTICE` in server and admin distributions.
=> Update `LICENSE` and `NOTICE` in the distributions (admin and server)

build-logic/src/main/kotlin/polaris-quarkus.gradle.kts
While the tasks `build` or `assemble` can used for generating the docker images, Quarkus also provides a more specific task, `imageBuild`, that may be convenient sometimes because it runs faster.
However, that task must depend on `jandex` for the build to succeed.
=> Gradle/Quarkus: make imageBuild task depend on jandex

polaris-core/src/main/java/org/apache/polaris/core/persistence/BasePersistence.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/IntegrationPersistence.java
=> Clarify the atomicity of BasePersistence methods

service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java, service/common/src/main/java/org/apache/polaris/service/http/IcebergHttpUtil.java
-Make the hash generation resilient against null metadataLocation
-Use getResolvedPath instead of getPassthroughResolvedPath to avoid redundant persistence round-trip
-Only try to calculate the etag for comparison against ifNoneMatch if the ifNoneMatch is actually provided
=> Improve code-containment and efficiency of etag-aware loading

scripts/postgres/schema-v1-postgresql.sql
This is step 1 of Bigger change https://github.com/apache/polaris/issues/649
Add SQL Script for user to create the Polaris tables 
Complete Tasks break down 
- [within extensions package or  polaris-core/relational-jdbc ?]
- Add DBCP2 utilities / helper
=> [JDBC] Part1 : ADD SQL script for Polaris setup

regtests/t_spark_sql/src/spark_sql_azure_blob.sh, regtests/t_spark_sql/src/spark_sql_azure_dfs.sh, regtests/t_spark_sql/src/spark_sql_basic.sh, regtests/t_spark_sql/src/spark_sql_gcp.sh, regtests/t_spark_sql/src/spark_sql_s3.sh, regtests/t_spark_sql/src/spark_sql_s3_cross_region.sh, regtests/t_spark_sql/src/spark_sql_views.sh
This grant in regtests isn't needed any longer
=> Remove some unnecessary code from regtests

service/common/src/main/java/org/apache/polaris/service/catalog/common/CatalogHandler.java
Fix the CI error after https://github.com/apache/polaris/pull/1233
=> Refactor CatalogHandler to comply with ErrorProne rules

build-logic/src/main/kotlin/publishing/configurePom.kt
`project.scm.tag` in a Maven pom is intended to refer to the SCM (Git) tag. We currently publish `main`, which is incorrect.
This change omits the SCM tag for snapshot builds, but emits the Git tag for releases.
=> Maven publication: Produce correct `<scm><tag>` in `pom.xml`

extension/persistence/eclipselink/build.gradle.kts, extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/EclipseLinkConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/auth/QuarkusAuthenticationConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/catalog/io/QuarkusFileIOConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusBehaviorChangesConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusFeaturesConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/context/QuarkusRealmContextConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/logging/QuarkusLoggingConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/metrics/QuarkusMetricsConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/persistence/QuarkusPersistenceConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/ratelimiter/QuarkusRateLimiterFilterConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/ratelimiter/QuarkusTokenBucketConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/storage/QuarkusStorageConfiguration.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/task/QuarkusTaskHandlerConfiguration.java
There was an issue around mapped configurations having the `@StaticInitSafe` annotation that led to _two_ instances (a "static" one and a "somewhet application-scoped" one) - this was fixed in Quarkus 3.21. One bug in smallrye-config is fixed for Quarkus > 3.21.0, another issue however remains.
Since `@StaticInitSafe` annotated configs seem to cause some weird issues, it seems legit to remote that annotation altogether. This approach was [taken in Nessie](https://github.com/projectnessie/nessie/pull/10606) as well. Investigations (via practical experiments) have proven that there's no measurable impact (runtime + heap) when doing this - and that's also been confirmed by Quarkus + Smallrye-config maintainers.
Hence this change remotes that annotation from the code base.
=> Remove `@StaticInitSafe` annotation

build-logic/src/main/kotlin/publishing/PublishingHelperExtension.kt, build-logic/src/main/kotlin/publishing/digest-task.kt, build-logic/src/main/kotlin/publishing/rootProject.kt, build-logic/src/main/kotlin/publishing/util.kt, quarkus/admin/build.gradle.kts, quarkus/server/build.gradle.kts
Ensure that digest and signature are generated for both Polaris-Server and admin tar/zip distribution. This actually _adds_ a SHA-512 digest for the tar/zip files, which can (and should) be published along those on download pages.
The Quarkus zip/tar distributables would already be published to Nexus as well, which implies a digest and signature. However this change makes the digest and signature available in a way that enables us to publish those along the zip/tar to download servers.
NB: This change moves the existing "generate digest" functionality to a reusable Gradle task implementation.
=> Build/Release: Add digest for Quarkus distributables

.github/workflows/helm.yml, .github/workflows/regtest.yml, README.md, getting-started/eclipselink/README.md, getting-started/spark/README.md, getting-started/telemetry/README.md, getting-started/trino/README.md, helm/polaris/README.md, helm/polaris/README.md.gotmpl, quarkus/admin/README.md, quarkus/server/README.md, regtests/README.md, run.sh, site/content/in-dev/unreleased/admin-tool.md, site/content/in-dev/unreleased/metastores.md, site/content/in-dev/unreleased/quickstart.md
`quarkusAppPartsBuild --rerun` is the right way to force a Docker image build.
=> Remove unnecessary `clean` and `--no-build-cache` from Gradle invocations

polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/persistence/QuarkusPersistenceConfiguration.java, service/common/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java
* Remove `instanceof` checks from `QuarkusProducers`.
* Remove the now unused `onStartup` method from `InMemoryPolarisMetaStoreManagerFactory`.
* Instead, call the good old `bootstrapRealms` method from `QuarkusProducers`.
* Add new config property to control which MetaStore types are bootstrapped automatically (defaults to `in-memory` as before).
* There is no bootstrap behaviour change in this PR, only refactorings to simplify code.
* Add info log message to indicate when a realm is bootstrapped in runtime using preset credentials.
Future enhancements may include pulling preset credentials from a secret manager like Vault for bootstrapping (s discussed in comments on #1228).
=> Generalize bootstrapping in servers

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolicyMappingAlreadyExistsException.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/policy/exceptions/PolicyAttachException.java, polaris-core/src/main/java/org/apache/polaris/core/policy/validator/PolicyValidators.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalog.java, service/common/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java
=> Implement PolicyCatalog Stage 2: detach/attach/getApplicablePolicies

api/polaris-catalog-service/build.gradle.kts, spec/generated/bundled-polaris-catalog-service.yaml, spec/polaris-catalog-apis/policy-apis.yaml
Adds two additional fields to the response of the GetApplicablePolicies API (GET /v1/{prefix}/applicablePolicies):
- `inherited`: Boolean indicating whether the applicable policy is directly attached or inherited from a parent entity.
- `namespace`: A list representing the hierarchical parent path to the policy, ordered from higher level namespace to lower.
These fields enable users to determine the origin of a policy, helping them identify when and how to correctly override or update policies.
=> [Spec] Add 'inherited' and 'namespace' Fields to GetApplicablePolicies API Response

service/common/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java
=> Properly track bootstrappedRealms in InMemoryPolarisMetaStoreManagerFactory

build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/polaris-root.gradle.kts, build-logic/src/main/kotlin/polaris-spotless.gradle.kts, settings.gradle.kts
Intelij gives following warnings during sync 
```
Multiple projects in this build have project directory '/Users/yzou/polaris/plugins/spark/v3.5': [:polaris-spark-3.5_2.12, :polaris-spark-3.5_2.13]
```
And Intelij dependency analysis also fails with same error.
Further more, the stylecheck and spotless check are unnecessary for duplicated projects, and may cause problem.
Here, we fix the problem by only loading one project for the spark plugin during Intelij IDE usage. 
Also manually verified that only one spotless error will be thrown if there is format issue for spark client plugins.
=> Avoid adding duplicated projects for Intelij IDE usage

build-logic/src/main/kotlin/publishing/maven-utils.kt, gradle/jar-licenses/LICENSE, gradle/jar-licenses/NOTICE, integration-tests/build.gradle.kts, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java, integration-tests/src/main/resources/META-INF/LICENSE
In preparation of the next releases (including jar artifacts publication), this PR uses "clean" `LICENSE` and `NOTICE` in published jar artifacts, and "regular" location.
=> Use "clean" LICENSE and NOTICE in published jar artifacts

bom/build.gradle.kts, gradle/projects.main.properties, nosql/persistence/varint/build.gradle.kts, nosql/persistence/varint/src/main/java/org/apache/polaris/persistence/varint/VarInt.java, nosql/persistence/varint/src/test/java/org/apache/polaris/persistence/varint/TestVarInt.java
It's a separate module to separate things.
=> Add `Varint` type for variable-length integer encoding

site/content/in-dev/0.9.0/rest-catalog-open-api.md
The 0.9.0 release documentation should point to the right OpenAPI spec (on the tag).
=> Update the link to OpenAPI in the documentation

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java
This PR fixes #1272
In Polaris, the empty namespace implicitly exists by default, see [link](https://github.com/apache/polaris/blob/8b5dfa97a8e50a53412d2ded40f2e4db5a40cc42/service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java#L490-L493). However, the superclass test assumes that the empty namespace does not exist initially, which causes the test to fail as expected in Polaris. This test was originally introduced in apache/iceberg#9890.
- Fix Polaris API including `namespaceExists`, `dropNamespace`, `listTables`, `listViews`
=> Unblock test `listNamespacesWithEmptyNamespace`

polaris-core/src/main/java/org/apache/polaris/core/context/CallContext.java, service/common/src/main/java/org/apache/polaris/service/auth/BasePolarisAuthenticator.java
With the switch to Quarkus Security this method is not used anymore.
The right way to access the principal is to `@Inject SecurityIdentity identity` or `@Inject SecurityContext context`.
=> Remove CallContext.getAuthenticatedPrincipal()

extension/persistence/jpa-model/build.gradle.kts, extension/persistence/jpa-model/src/main/java/org/apache/polaris/jpa/models/ModelPolicyMappingRecord.java, getting-started/assets/eclipselink/persistence.xml
This is a follow-up of https://github.com/apache/polaris/pull/1104#discussion_r2022107629. The EclipseLink seems not respect the ordering of the columns in order of their appearance in the member declarations using the `@Id` annotation. We will need to use `org.eclipse.persistence.annotations.PrimaryKey` annotation to ensure the ordering.
To verify this:
use the getting-started/eclipselink example
```
docker compose -f getting-started/eclipselink/docker-compose-postgres.yml -f getting-started/eclipselink/docker-compose-bootstrap-db.yml -f getting-started/eclipselink/docker-compose.yml up
```
Go into the Postgres container and run
```
> psql -U postgres -d POLARIS
> \d policy_mapping_records;
```
Before the fix, we will see
```
\d policy_mapping_records;
Table …
```
=> Fix incorrect primary key column order in policy_mapping_records table by using EclipseLink @PrimaryKey annotation

getting-started/eclipselink/README.md, getting-started/eclipselink/docker-compose-bootstrap-db.yml, getting-started/eclipselink/docker-compose-postgres.yml, getting-started/eclipselink/docker-compose.yml
Fixes #1398. Reinstates the missing dependencies that were taken out due to the recomposition of the `docker-compose.yml` files.
This should restore previous behavior - here's my local output:
```
ahemani@F7Q5C90CJX polaris % docker compose -f getting-started/eclipselink/docker-compose-postgres.yml -f getting-started/eclipselink/docker-compose-bootstrap-db.yml -f getting-started/eclipselink/docker-compose.yml up -d
[+] Running 7/7
✔ Network eclipselink_default                Created                                                                                                                                                                                       0.0s 
✔ Container eclipselink-postgres-1           Healthy …
```
=> Reinstate dependencies between Docker Compose services

polaris-core/src/main/java/org/apache/polaris/core/policy/PolicyEntity.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalog.java
The spec has been updated (https://github.com/apache/polaris/pull/1277) that now `GetApplicablePolicies` shall return a list of `ApplicablePolicies`, which include the policy's parent namespace and whether the policy is inherited or not. This PR updates the `getApplicablePolicies` method in `PolicyCatalog` to include the additional information.
cc @flyrain
=> PolicyCatalog: Update GetApplicablePolicies to return List<ApplicablePolicies>

polaris-core/src/main/resources/schemas/policies/system/snapshot-expiry/2025-02-03.json
I'm proposing to rename the table maintenance policy "snapshot-retention" to "snapshot-expiry". While "snapshot-retention" is a reasonable name, it's a bit too general. I believe "snapshot-expiry" more precisely captures the intent of the policy, which is specifically about removing expired snapshots. 
I think this is the right time to make the change before we include the policy schemas in an upcoming release.
Will change related classes in a followup PR.
=> Rename the Snapshot Retention policy

polaris-core/src/main/java/org/apache/polaris/core/policy/PredefinedPolicyTypes.java, polaris-core/src/main/java/org/apache/polaris/core/policy/content/maintenance/SnapshotExpiryPolicyContent.java, polaris-core/src/main/java/org/apache/polaris/core/policy/validator/PolicyValidators.java, polaris-core/src/test/java/org/apache/polaris/core/policy/MaintenancePolicyContentTest.java, polaris-core/src/test/java/org/apache/polaris/core/policy/PolicyTypeTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java
In https://github.com/apache/polaris/pull/1284 we've made the decision to rename `snapshot-retention` to `snapshot-expiry`. This PR updates the corresponding names in `polaris-core`
cc @flyrain
=> Policy: Rename Snapshot Retention to Snapshot Expiry

build-logic/src/main/kotlin/publishing/rootProject.kt, build-logic/src/main/kotlin/publishing/util.kt
The `releaseEmailTemplate` task is looking for project name from https://whimsy.apache.org/public/public_ldap_projects.json. It's looking for `name` attribute in the project json, but `name` doesn't exist there, meaning the task is failing.
This PR remove the fetch project name method and just use `Apache Polaris` as project name (as it's the project name 😄 ).
=> Fix releaseEmailTemplate task

polaris-core/src/main/java/org/apache/polaris/core/auth/AuthenticatedPolarisPrincipal.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/PolarisResolutionManifest.java
This seems to be a leftover from when `ActiveRolesProvider` was introduced. The setter was still used (just in one place, by the `Resolver`), but the getter wasn't, which hints at the fact that this property can be safely removed.
As a bonus, `AuthenticatedPolarisPrincipal` now becomes immutable, which is imho a very good thing.
=> Remove activatedPrincipalRoles property from AuthenticatedPolarisPrincipal

.github/workflows/helm.yml, getting-started/assets/cloud_providers/deploy-aws.sh, getting-started/assets/cloud_providers/deploy-azure.sh, getting-started/assets/cloud_providers/deploy-gcp.sh, getting-started/eclipselink/README.md, helm/polaris/README.md, helm/polaris/README.md.gotmpl, quarkus/admin/distribution/LICENSE, quarkus/server/build.gradle.kts, quarkus/server/distribution/LICENSE, run.sh, site/content/in-dev/unreleased/admin-tool.md, site/content/in-dev/unreleased/getting-started/quickstart.md, site/content/in-dev/unreleased/metastores.md
As discussed on the mailing list (https://lists.apache.org/thread/7bccoyzcr77xd8qzzz4r6nn3zytc7doz), this PR:
1. ship EclipseLink and PostgreSQL JDBC driver by default in Polaris distribution
2. update LICENSE
3. update documentation
4. update helm charts/tests
=> Ship eclipselink and PostgreSQL JDBC driver by default in Polaris distribution

polaris-core/src/main/java/org/apache/polaris/core/connection/AuthenticationParametersDpo.java, polaris-core/src/main/java/org/apache/polaris/core/connection/AuthenticationType.java, polaris-core/src/main/java/org/apache/polaris/core/connection/BearerAuthenticationParametersDpo.java, polaris-core/src/main/java/org/apache/polaris/core/connection/ConnectionConfigInfoDpo.java, polaris-core/src/main/java/org/apache/polaris/core/connection/ConnectionType.java, polaris-core/src/main/java/org/apache/polaris/core/connection/IcebergRestConnectionConfigInfoDpo.java, polaris-core/src/main/java/org/apache/polaris/core/connection/OAuthClientCredentialsParametersDpo.java, polaris-core/src/test/java/org/apache/polaris/core/connection/ConnectionConfigInfoDpoTest.java
Change the annotations from
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "authenticationTypeCode", visible = true)
@JsonSubTypes({
@JsonSubTypes.Type(value = OAuthClientCredentialsParametersDpo.class, name = "1"),
@JsonSubTypes.Type(value = BearerAuthenticationParametersDpo.class, name = "2"),
})
```
to
```java
@JsonTypeInfo(
use = JsonTypeInfo.Id.NAME,
include = JsonTypeInfo.As.EXISTING_PROPERTY,
property = "authenticationTypeCode")
@JsonSubTypes({
@JsonSubTypes.Type(value = OAuthClientCredentialsParametersDpo.class, name = "1"),
@JsonSubTypes.Type(value = BearerAuthenticationParametersDpo.class, name = "2"),
})
```
The reason for this change is that when `visible = true` and `authenticationTypeCode` is already a field in the class, the serialized json ends up including …
=> Fix Connection Config DPOs

version.txt
As 0.10.0-beta-incubating release branch has been created, we can bump to 0.11.0-beta-incubating on `main`.
=> Bump version to 0.11.0-beta-incubating-SNAPSHOT

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkStore.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapTransactionalPersistenceImpl.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BasePolarisMetaStoreManagerTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java
All implementations of `TransactionalPersistence.lookupEntityInCurrentTxn()` are currently ignoring the `typeCode` parameter completely and could potentially return an entity of the wrong type.
This can become very concerning during authentication, since a principal lookup could return some entity that is not a principal, and that would be considered a successful authentication.
=> Make entity lookups by id honor the specified entity type

extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/DatasourceOperations.java
The logging is a bit redundant, as in the IcebergException log's for these unhandled / unintentional exception are logged.
More details : https://github.com/apache/polaris/pull/1430#issuecomment-2825464377
cc @flyrain @dimas-b
=> JDBC: Remove logging for DatabaseOperations

quarkus/admin/build.gradle.kts
In #1411, the build was updated to always include the postgresql dependency.  But only the gradle files that package the `polaris` image were updated.  The image that packages the polaris admin tool was not.  As a result, it was not possible to bootstrap a Postgres-backed Polaris instance with the admin tool.  This commit fixes the issue.
Related: #1441
=> Add missing Postgresql dependency

api/iceberg-service/build.gradle.kts, api/management-service/build.gradle.kts, api/polaris-catalog-service/build.gradle.kts, gradle/libs.versions.toml, quarkus/defaults/src/main/resources/application.properties, quarkus/service/build.gradle.kts, server-templates/api.mustache, service/common/build.gradle.kts, service/common/src/main/java/org/apache/polaris/service/exception/IcebergExceptionMapper.java
- Adds `@Timeout` to request endpoints, configured with a default of 60 seconds.
- https://quarkus.io/guides/smallrye-fault-tolerance
- Updates the exception mapping to return 408 for request timeouts.
=> Add Request Timeouts 

build-logic/src/main/kotlin/publishing/digest-task.kt
The sha512 files should use `.sha512` extension, today it's `-sha512`.
=> Use .sha512 extension instead of -sha512

site/content/in-dev/unreleased/getting-started/quickstart.md
Updated Quickstart with pre-set root principal credentials.
=> Update Local Root Principal Credentials in Quickstart

service/common/src/main/java/org/apache/polaris/service/catalog/common/CatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogHandler.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogHandler.java
This PR moves the feature config check from `CatalogHandler::initializeCatalog` to `CatalogAdapter::newHandlerWrapper` for generic-table and policy, such that if the feature is not enabled we can directly throw unsupported exception instead of doing authorization first.
cc: @flyrain @eric-maynard @gh-yzou
=> Generic Table/Policy Store: Move feature config check to Adapter and some small refactoring

polaris-core/src/main/java/org/apache/polaris/core/config/BehaviorChangeConfiguration.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/io/FileIOExceptionsTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java
For rest catalogs, `TableOperations.refresh()` can result in an expensive trip to object storage. Despite this, the method is called quite frequently and is currently called after every commit when we construct a BaseTable to return back to a client that requested a commit.
In some cases, the same TableOperations is used for one commit and then is immediately used for another. We can see this in some tests, such as Iceberg's `CatalogTests.testUpdateTableSchemaThenRevert`:
```
table.updateSchema().addColumn("col1", StringType.get()).addColumn("col2", StringType.get()).addColumn("col3", StringType.get()).commit();
table.updateSchema().deleteColumn("col1").deleteColumn("col2").deleteColumn("col3").commit();      
```
This PR proposes that the TableOperations can update its `currentMetadata` …
=> Allow BasePolarisTableOperations to skip refreshing metadata after a commit

README.md
The instruction of how to set your own credentials is no where to be found in the polaris documents and repo markdowns, so according to the comment: https://github.com/apache/polaris/pull/1452#issuecomment-2829080942
Added the instruction of how to set credentials in README.
=> Added set credentials env instruction in README

site/content/in-dev/unreleased/access-control.md
There are some typo left on my previous pr #1460  related to polaris policy
cc: @HonahX
=> Typo fix on access-control policy docs

site/content/in-dev/unreleased/getting-started/using-polaris.md
=> Added link to the Spark-Jupyter Notebook Getting Started from the main Getting Started Page

extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/cache/EntityCache.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/cache/InMemoryEntityCache.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/cache/InMemoryEntityCacheTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BaseResolverTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/CatalogNoEntityCacheTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/GenericTableCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogViewTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisCatalogWithEntityCacheTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java
Refactors the EntityCache into an interface to make it swappable. The MetaStoreManagerFactory, which is fully swappable, can specify any cache implementation now through `getOrCreateEntityCache`.
=> Refactor EntityCache into an interface

integration-tests/src/main/java/org/apache/polaris/service/it/env/PolicyApi.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisPolicyServiceIntegrationTest.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/dao/entity/BaseResult.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapTransactionalPersistenceImpl.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PolicyMappingUtil.java, polaris-core/src/main/java/org/apache/polaris/core/policy/exceptions/PolicyInUseException.java, polaris-core/src/main/java/org/apache/polaris/core/policy/validator/maintenance/BaseMaintenancePolicyValidator.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BasePolarisMetaStoreManagerTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalog.java, service/common/src/main/java/org/apache/polaris/service/exception/PolarisExceptionMapper.java
This PR updates `dropPolicy` to check if the policy is in use before dropping. It also supports a `detach-all` flag which drops policy and all corresponding mappings.
=> Policy Store: Check whether Policy is in use before dropping and support `detach-all` flag

service/common/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogAdapter.java
Polaris have many downstream call that relies on the thread local CallContext. There are work currently working on removing the thread local CallContext, before that continue apply the thread local context setting as IcebergCatalogAdapter  https://github.com/apache/polaris/blob/main/service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java#L160
=> Add the thread local callContext setting for GenericTableCatalogAdapter and PolicyCatalogAdapter

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkStore.java, extension/persistence/jpa-model/src/main/java/org/apache/polaris/jpa/models/ModelPolicyMappingRecord.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java
`writeToPolicyMappingRecords` should update the existing record if there is one with the same primary key. This PR fix the implementation in EclipseLink Persistence to align with the expectation
=> Ensure writeToPolicyMappingRecord update existing record if primary key equals in EclipseLink Persistence Impl

quarkus/admin/src/main/resources/application.properties, quarkus/defaults/src/main/resources/application-test.properties, quarkus/test-commons/src/main/java/org/apache/polaris/test/commons/PostgresRelationalJdbcLifeCycleManagement.java
Some of the user experience at 409 for docker pull of postgres-17 image during (./gradlew build), which gets fixed by docker pull of postgres:17 i.e making the image of postgres locally available. I never experience this as this image was always on my docker locally. turns out the dev-services pull the postgres-17 default and we just need them to use postgres-17-alpine
To fix this looked into logs : 
```
Task :polaris-quarkus-admin:compileTestJava FROM-CACHE
> Task :polaris-quarkus-admin:testClasses
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [org.slf4j.impl.JBossSlf4jServiceProvider@39722b04]
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@1c916ca1]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation. …
```
=> Fix: Remove Dev Containers pulling diff postgres version

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/io/FileIOExceptionsTest.java
It looks like after #1283, this test no longer compiles as the Iceberg API has changed. I'm not sure how this wasn't caught by CI on that PR itself.
=> Fix FileIOExceptionsTest to conform to new Iceberg 1.8 API

extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/JdbcBasePersistenceImpl.java
Optimize writeEntity calls by extracting the calls out of transaction. please ref to benchmarks below for the motivation for the change. 
**_Note : Handling transaction failures and retries are not in the scope of this pr. This is purely for optimization purpose._**
-----
started the jdbc implementation backed Service : https://github.com/apache/polaris/pull/1470/files#diff-44e2226f0bc5712cf1cd511efd94242a08c9760b947809c7ebe76f121f480c76
Updated creds via 
```
--- a/benchmarks/src/gatling/resources/benchmark-defaults.conf
+++ b/benchmarks/src/gatling/resources/benchmark-defaults.conf
@@ -28,11 +28,11 @@ http {
auth {
-  client-id = null
+  client-id = root
-  client-secret = null
+  client-secret = s3cr3t
}
```
go to benchmark tools and run the following benchmarks : 
```
./gradlew …
```
=> JDBC: Optimize writeEntity calls

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisPolicyServiceIntegrationTest.java
Use `NestedField.optional()` instead.
=> Avoid using deprecated `NestedField.of()`

extension/persistence/relational-jdbc/build.gradle.kts, quarkus/admin/build.gradle.kts
Add `jackson-annotations` as a `compileOnly` dependency where it was missing to allow Jackson annotations to be found when compiling modules that depend on classes having those annotations.
=> Fix compile warning: unknown enum constant Id.NAME

site/layouts/partials/navbar.html
When viewed on our mobile phone, the navigation menu component will overlap and making it impossible to navigate the website.
current: 
proposed fix: 
With the new one, the nav bar will be scrollable and each link will not obstruct the other.
This change is based on [docsy's navigation bar on their web doc](https://github.com/google/docsy/blob/62273b980ed40831d3bcbc96b13f5e81915eebab/layouts/partials/navbar.html#L51) where they ensure each navigation options are enclosed with `li` tag and have `nav-item` css class.
cc: @snazy @flyrain
=> fix overlapping menu item on the nav bar

polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java
Log explicit messages around auto-bootstrapping and unnecessary/left-over secrets that are (still) available.
=> Auto-bootstrap: add verbose logging

.github/workflows/nightly.yml
This PR adds a new GitHub Action to publish SNAPSHOT on Apache Nexus every day (nightly build).
=> Add nightly build GH action to publish SNAPSHOT on Nexus

build-logic/src/main/kotlin/publishing/PublishingHelperExtension.kt, build-logic/src/main/kotlin/publishing/configurePom.kt, build-logic/src/main/kotlin/publishing/rootProject.kt, build-logic/src/main/kotlin/publishing/util.kt
The added flexibility is intended to be ported to the multiple project in the polaris-tools repository.
(Follow up of #1384)
=> Build: Fix `fetchAsfProjectName` and make the publishing extension more flexible

plugins/spark/README.md, plugins/spark/v3.5/integration/build.gradle.kts, plugins/spark/v3.5/integration/src/intTest/java/org/apache/polaris/spark/quarkus/it/SparkDeltaIT.java, plugins/spark/v3.5/integration/src/intTest/java/org/apache/polaris/spark/quarkus/it/SparkIT.java, plugins/spark/v3.5/integration/src/intTest/java/org/apache/polaris/spark/quarkus/it/SparkIntegrationBase.java, plugins/spark/v3.5/integration/src/intTest/resources/logback.xml, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/SparkCatalog.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/utils/PolarisCatalogUtils.java, site/content/in-dev/unreleased/polaris-spark-client.md
Add following tests for Detla and Iceberg support:
1) create, rename, list and drop for both Iceberg and Delta
2) alter support for delta table
3) spark dataframe APi testing
=> Add Integration tests for Delta tables for Spark Client

quarkus/service/build.gradle.kts, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java
Test IcebergCatalogTest and TableCleanupTaskHandlerTest fails when maxParallelForks is set to 1.
1) IcebergCatalogTest fails because the metadata location file already exists, this is due to the fact that couple of tests points try to write to the same location. Mitigated by using location with random suffix to avoid conflict.
2) TableCleanupTaskHandlerTest fails due to Null pointer problem for getCurrentCallContext. Fix the test by using quarkus injection to get the callContext correctly.
3) The quarkus tests sometimes fails due to OutOfMemory error, default heap size seems 512 MB. Increase it to 4g to avoid the problem
=> Fix test failure for IcebergCatalogTest and TableCleanupTaskHandlerTest under low concurrency

service/common/src/main/java/org/apache/polaris/service/events/TestPolarisEventListener.java
Use `Class.cast()` instead of implicit cast.
=> Fix compile warning: [unchecked] unchecked cast

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/BatchFileCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TaskTestUtils.java, service/common/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java
As a follow-up PR for #312 
Previously, when DROP TABLE PURGE was issued, Polaris cleaned up data files, manifest files, and metadata files, but did not clean up partition-level statistics files.
Partition statistics files (partition_stats) remain in storage after the table is dropped. These files are listed in the TableMetadata but were not included in the batch deletion task, resulting in orphaned files.
- Added support for including partitionStatisticsFiles from TableMetadata in the batch cleanup task (BatchFileCleanupTaskHandler).
- Updated `getMetadataFileBatches()` to collect and batch partition statistics files for deletion.
- Added test coverage in `TableCleanupTaskHandlerTest` and `BatchFileCleanupTaskHandlerTest` to verify:
- partitionStats files are scheduled for deletion
- …
=> Add cleanup support for partition-level statistics files when `DROP TABLE PURGE`

integration-tests/src/main/java/org/apache/polaris/service/it/env/GenericTableApi.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/PolarisRESTCatalog.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/rest/CreateGenericTableRESTRequest.java, plugins/spark/v3.5/spark/src/test/java/org/apache/polaris/spark/rest/DeserializationTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogHandler.java, spec/polaris-catalog-apis/generic-tables-api.yaml
Today, we directly uses the CreateGenericTableRequest constructor in the code, when new field is added or removed, we need to update the main code also.
Instead of using constructor, we switch to use builder to avoid changes in main code to allow api (api class) only change in the future
=> Use builder for CreateGenericTableRequest instead of constructor for easier API spec update

quarkus/admin/build.gradle.kts, quarkus/server/build.gradle.kts
We forgot to include `DISCLAIMER` file in the binary distributions (`admin` and `server`).
=> Include DISCLAIMER in binary distributions

extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/DatasourceOperations.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/JdbcBasePersistenceImpl.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/models/Converter.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/models/ModelEntity.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/models/ModelGrantRecord.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/models/ModelPolicyMappingRecord.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/models/ModelPrincipalAuthenticationData.java, extension/persistence/relational-jdbc/src/test/java/org/apache/polaris/extension/persistence/impl/relational/jdbc/DatasourceOperationsTest.java
Simplify the JDBC entity conversion logic, to address this comment, https://github.com/apache/polaris/pull/1487#discussion_r2071123425.
=> Simplify JDBC entity conversion

regtests/t_pyspark/src/test_spark_sql_s3_with_privileges.py, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java
Fixes #1380 
**Issue:**
Currently, loadTable returns a 403 error when the metadata file is not found, which can be misleading. Since users are expected to have configured the appropriate ListBucket permissions in their IAM policy, a 404 error would be more accurate in this scenario.
`Access Denied or Forbidden error: User: arn:aws:sts::{account}:assumed-role/{role}/PolarisAwsCredentialsStorageIntegration is not authorized to perform: s3:ListBucket on resource: \"arn:aws:s3:::ashok-test-local\" because no session policy allows the s3:ListBucket action (Service: S3, Status Code: 403, Request ID: W6Q2D563ETEKR6XZ, Extended Request ID: Izq3QS7eZmGjhjfyoxJWMHeCgrFvUlpZjj73JYMO8i/qnKw6CjOaPVgOWVLFr/JsToTeTxO0YaM=)`
As per S3 GetObject [documentation](https://docs.aws.amazon.com/AmazonS3/latest/A …
=> fix(Catalog): Add List PolarisStorageAction for all metadata read operations

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisPolicyServiceIntegrationTest.java, polaris-core/src/main/java/org/apache/polaris/core/config/BehaviorChangeConfiguration.java, polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java, polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfiguration.java, polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfigurationStore.java, polaris-core/src/test/java/org/apache/polaris/service/storage/PolarisConfigurationStoreTest.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusReservedProperties.java, service/common/src/main/java/org/apache/polaris/service/config/ReservedProperties.java
Previously, some `FeatureConfiguration`s could have a `catalogConfig` which allowed admins to enable or disable the feature on a per-catalog basis. Unfortunately, config itself was a freeform string.
This means that new configs could potentially collide with existing configs. For example, imagine a user has had a catalog with some property `delete.everything.yes` since they started using Polaris with release 0.9.0. At some point in time, we add a new `FeatureConfiguration` with `catalogConfig` `delete.everything.yes`. When the user upgrades their Polaris, whatever new behavior is gated behind that catalog config will be silently enabled.
To prevent this, catalog configs should start with the reserved `polaris.` prefix, so that they cannot collide with existing properties. We can allowlist …
=> Migrate catalog configs to the new reserved prefix

polaris-core/src/main/java/org/apache/polaris/core/persistence/BasePersistence.java
=> nit: remove unused javadoc parameter in BasePersistence

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
`gradle-wrapper.properties` should not contain ASF header (as it's not created by "us").
=> Fix header in the gradle-wrapper.properties

quarkus/admin/build.gradle.kts, quarkus/admin/distribution/DISCLAIMER, quarkus/admin/src/main/docker/Dockerfile.jvm, quarkus/server/build.gradle.kts, quarkus/server/distribution/DISCLAIMER, quarkus/server/src/main/docker/Dockerfile.jvm
As we are going to publish Docker images (SNAPSHOT and release), like for any binary distribution, the Docker images have to contain `LICENSE`, `NOTICE`, and `DISCLAIMER` files.
=> Include LICENSE, NOTICE, DISCLAIMER files in the docker images

LICENSE, helm/polaris/templates/_helpers.tpl, helm/polaris/templates/serviceaccount.yaml, helm/polaris/templates/servicemonitor.yaml, helm/polaris/templates/storage.yaml, helm/polaris/tests/logging_storage_test.yaml, helm/polaris/tests/quantity_test.yaml, helm/polaris/tests/service_monitor_test.yaml
The header doesn't seem correct here. It should be the ASF header as it's a Polaris resource.
@adutra can you please confirm ?
=> Use correct header in Helm chart

quarkus/admin/distribution/LICENSE, quarkus/admin/distribution/NOTICE, quarkus/server/distribution/LICENSE, quarkus/server/distribution/NOTICE
My script to help on `LICENSE` didn't include the required license content inline (for BSD or MIT licenses).
I updated my script:
1. To group the artifacts (to reduce the duplicate content)
2. Add BSD and MIT licenses inline
=> In binary distributions, now we group the artifacts and we add BSD/MIT licenses inline

polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfigurationStore.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/config/DefaultConfigurationStoreTest.java
After the merge of #1557, I noticed that this check may incorrectly call `config.catalogConfigUnsafe()` on a `FeatureConfiguration` that doesn't actually have a `catalogConfigUnsafe`. Unfortunately this code path never got exercised in the original PR, as we didn't have any configs that had a safe config but not an unsafe one.
=> Better null-safety for check against unsafe catalog configs

integration-tests/src/main/java/org/apache/polaris/service/it/env/ManagementApi.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisPolicyServiceIntegrationTest.java, polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisAuthorizableOperation.java, polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisAuthorizerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisPrivilege.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAdminServiceAuthzTest.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java, spec/polaris-management-service.yml
This PR adds new policy related privileges to `polaris-management-api.yml` and update `PolarisAdminService` to allow granting new privileges
dev list discussion: https://lists.apache.org/thread/tytrj8lts0zx7xl38o9pmjwwt9kyzy61
=> [Policy Store | Management Spec] Add policy privileges to spec and update admin service impl

spec/polaris-management-service.yml
* https://github.com/apache/polaris/pull/1026
* https://github.com/apache/polaris/pull/1305
Below are all the reference mentioned in this PR:
* AWS Docs:
* AWS SigV4 protocol: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html
* Configure IAM for Glue: https://docs.aws.amazon.com/glue/latest/dg/configure-iam-for-glue.html
* [AWS STS Regions and endpoints](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_region-endpoints.html)
* Iceberg SDK 
* [AuthProperties.java#30](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/auth/AuthProperties.java#L30)
* [RESTSigV4Signer.java#L91](https://github.com/apache/iceberg/blob/apache-iceberg-1.9.0/aws/src/main/java/org/apache/iceberg/aws/RESTSigV4Signer.java#L91)
* …
=> Spec: Add SigV4 Auth Support for Catalog Federation

.github/workflows/helm.yml
Whether helm-charts work (or not) doesn't only depend on what's on the `helm/` directory, but also the production code. It's hard to figure out which changes could break the helm-charts or what the helm-charts rely on. Therefore it's likely better to run Helm-CI for all changes.
=> CI: Make helm-CI run for all changes

helm/polaris/README.md, helm/polaris/README.md.gotmpl, helm/polaris/ci/features-values.yaml, helm/polaris/templates/configmap.yaml, helm/polaris/values.yaml
Fixes #1618 .
Fixes #1634.
This change adapts the `Values.features` section to the changes from #1572, also fixing incorrect configmap entries produced by the template.
It also re-syncs the README.md file with README.md.gotmpl (the sync was lost a few commits ago), and enhances the instructions for running Helm tests locally.
=> fix(helm): Fix features configuration section & enhance docs

quarkus/service/src/main/java/org/apache/polaris/service/quarkus/metrics/RealmIdTagContributor.java
It's not a good practice to create metrics from error messages. This change removes that.
=> fix(metrics): Do not emit metrics for failed realm resolutions

helm/polaris/DISCLAIMER, helm/polaris/LICENSE, helm/polaris/NOTICE
As pointing it out on RC3, the Helm chart `LICENSE` and `NOTICE` are fixed in this PR.
@rdblue @RussellSpitzer ^^
=> Add DISCLAIMER in Helm chart, fix LICENSE and NOTICE regarding code coming from Project Nessie in Helm chart

.asf.yaml, .github/workflows/spark_client_regtests.yml
Job names in GH WFs should be unique and not ambiguous to be able to distinguish those.
=> fix(CI): Resolve ambiguous `regtests` GH WF job name

.github/workflows/nightly.yml
Adopt the `Nightly Build` workflow to not (try to) publish every night from forks.
=> fix(nightly-CI): Do not publish snapshots from forks

extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, extension/persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkStore.java, extension/persistence/jpa-model/src/main/java/org/apache/polaris/jpa/models/ModelPolicyMappingRecord.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/JdbcBasePersistenceImpl.java, extension/persistence/relational-jdbc/src/main/java/org/apache/polaris/extension/persistence/relational/jdbc/QueryGenerator.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/AbstractTransactionalPersistence.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapMetaStore.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapTransactionalPersistenceImpl.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PolicyMappingPersistence.java, polaris-core/src/main/java/org/apache/polaris/core/policy/TransactionalPolicyMappingPersistence.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java
This PR adds `policyTypeCode` to both the in-memory tree map store's slice and the SQL table `policy_mapping_records` index (JDBC has already included this in #1468 ). This change lays the groundwork for future features that require efficient filtering by policy type—such as fetching all entities with a data compaction policy attached.
As part of this update, the signature of `loadAllTargetsOnPolicy` is also modified to accept `policyTypeCode`, allowing the method to take advantage of the new index for improved performance.
cc: @flyrain @singhpk234
=> [Policy Store] Add policyTypeCode to Slice/Index for Future Filtering Support and Update Policy Persistence Method

extension/persistence/eclipselink/src/test/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreManagerTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogViewFileIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogViewFileIntegrationTestBase.java, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewFileIT.java, quarkus/service/src/intTest/java/org/apache/polaris/service/quarkus/it/relational/jdbc/JdbcQuarkusViewFileIT.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTRSAKeyPairTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/io/FileIOExceptionsTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogViewFileIntegrationTest.java
* `PolarisRestCatalogViewFileIntegrationTest`
* `FileIOExceptionsTest`
* `JWTRSAKeyPairTest`
Changes the tests to leverage JUnit's `@TempDir`.
Simplifies `PolarisEclipseLinkMetaStoreManagerTest`
=> fix(test): Do not let some more tests spam `/tmp`

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisOverlappingTableTest.java
Changes the test to leverage JUnit's `@TempDir`.
=> fix(testing): Do not let PolarisOverlappingTableTest spam `/tmp`

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java
Following up on #1694
* Restore `private` scope on internal fields in `IcebergCatalog`
* Use a test-only setter instead of sub-classing to manage injecting test FileIO implementations
=> Refactor IcebergCatalog to isolate internal state

regtests/t_pyspark/src/test_spark_sql_s3_with_privileges.py
This test doesn't run due to following reason
1) incorrect call to s3.delete_objects, which should be a list of objects
2) 400 exception is thrown for metadata file missing instead of 404
3) Spark drop table calls load table underneath, which fails.
=> Fix test_spark_credentials_s3_exception_on_metadata_file_deletion

regtests/docker-compose.yml, regtests/t_pyspark/src/conftest.py
In change https://github.com/apache/polaris/commit/f2d1caf94c1f077c70b53f94e4ece1c0afc47144
DROP_WITH_PURGE is now set to false by default, however, our regression tests test with purge enabled.
Set the DROP_WITH_PURGE to true for our python regression tests
=> Fix regression test docker setup for purge

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisPolicyServiceIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java
* In `PolarisPolicyServiceIntegrationTest`
* In `PolarisRestCatalogIntegrationTest`
Following up to #1557
=> Use canonical catalog property names in tests

polaris-core/src/main/java/org/apache/polaris/core/config/PolarisConfigurationStore.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/config/DefaultConfigurationStoreTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/FileIOUtil.java, service/common/src/main/java/org/apache/polaris/service/config/DefaultConfigurationStore.java, service/common/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java
Although we do a check of !realmContextInstance.isUnsatisfied() it only checks if there is matching bean, however, it doesn't check if the context is active or not. Similarly isResolvable also don't check if the scope is active. Therefore if getConfiguration is called when there is no active scope, it will get Exception like ContextNotActiveException. 
This actually fails the TaskExecutor because it runs in a separate thread.
In order to fix the problem, we introduces a new getConfiguration function to handle the background tasks, and also use isResolvable instead of isUnsatisfied to handle ambiguities.
Tests:
1) Manually verified the test with S3 setup
2) Tried to add a SparkIntegration tests for the purge, however, either runs into dependency problem like following
``` …
```
=> Handle RequestScoped instance injection gracefully for DefaultConfigurationStore

polaris-core/src/main/java/org/apache/polaris/core/context/CallContext.java, polaris-core/src/test/java/org/apache/polaris/core/storage/InMemoryStorageIntegrationTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BasePolarisMetaStoreManagerTest.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTSymmetricKeyGeneratorTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/BatchFileCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/ManifestFileCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/test/PolarisIntegrationTestFixture.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java, service/common/src/main/java/org/apache/polaris/service/context/catalog/PolarisCallContextCatalogFactory.java, service/common/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
Now that every catalog created by PolarisCallContextCatalogFactory is correctly closed by IcebergCatalogAdapter, we can finally remove the CallContext.close() method and the associated cloaseables group. This PR also removes the dispose method in `QuarkusProducers`.
This simplification will hopefully pave the way to a more robust handling of request-scoped beans in task executor threads.
=> feat(cdi): Remove CallContext.close()

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java
Per the discussion in #801 and on followup PRs, it seems there is a consensus to not rotate root's secrets after bootstrapping. This PR updates `JdbcMetaStoreManagerFactory` to align with that consensus.
=> Don't rotate root's credentials on startup in JdbcMetaStoreManagerFactory

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/PolarisCallContext.java, polaris-core/src/main/java/org/apache/polaris/core/context/CallContext.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, service/common/src/main/java/org/apache/polaris/service/context/DefaultCallContextResolver.java
This is the first step to consolidate call context. After this change, you can already use `PolarisCallContext` to get a `RealmContext`. To finish the consolidation, here are follow-ups.
=> Consolidate CallContext with PolarisCallContext

persistence/eclipselink/src/test/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreManagerTest.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/AtomicMetastoreManagerWithJdbcBasePersistenceImplTest.java, polaris-core/src/main/java/org/apache/polaris/core/PolarisCallContext.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisTreeMapAtomicOperationMetaStoreManagerTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisTreeMapMetaStoreManagerTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/ResolverTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/cache/InMemoryEntityCacheTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/InMemoryStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/ManagementServiceTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTRSAKeyPairTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/auth/JWTSymmetricKeyGeneratorTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogViewTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisGenericTableCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/config/DefaultConfigurationStoreTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/entity/CatalogEntityTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/BatchFileCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/ManifestFileCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/test/PolarisIntegrationTestFixture.java, service/common/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java, service/common/src/test/java/org/apache/polaris/service/task/TaskExecutorImplTest.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
After pr https://github.com/apache/polaris/pull/1806, the original constructor is marked as deprecated and is not suppose to be used anymore.
This PR removes the usage of the old constructors.
=> Remove deprecated constructor for PolarisCallContext

persistence/relational-jdbc/build.gradle.kts, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/DatasourceOperations.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcBasePersistenceImpl.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/QueryGenerator.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/models/Converter.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/models/ModelEntity.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/models/ModelGrantRecord.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/models/ModelPolicyMappingRecord.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/models/ModelPrincipalAuthenticationData.java, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/AtomicMetastoreManagerWithJdbcBasePersistenceImplTest.java, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/DatasourceOperationsTest.java, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/QueryGeneratorTest.java
=> JDBC: Use PrepareStatement

build-logic/src/main/kotlin/publishing/PublishingHelperPlugin.kt, plugins/spark/README.md, plugins/spark/v3.5/getting-started/notebooks/SparkPolaris.ipynb, plugins/spark/v3.5/regtests/run.sh, plugins/spark/v3.5/spark/LICENSE, plugins/spark/v3.5/spark/NOTICE, plugins/spark/v3.5/spark/build.gradle.kts, site/content/in-dev/unreleased/polaris-spark-client.md
This PR does following:
1) add default license and notice to spark client jar
2) update the spark client jar name to align with polaris published jar
3) enable publish spark client jar to maven
=> Add license and notice to spark client jar and push jar to maven

polaris-core/src/main/java/org/apache/polaris/core/connection/ConnectionType.java
Previously, the `maxCode` was generated using `AuthenticationType.values()`. It worked fine because Polaris supported the same number of Connection and Authentication types. The enum conversion would break if we add new authentication or connection types independently as in #1805 or other forms of federation.
=> Fix  maxCode generation for ConnectionTypeEnum

persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, service/common/src/test/java/org/apache/polaris/service/exception/IcebergExceptionMapperTest.java
Fix by wrapping jakarta.persistence.PersistenceException thrown in the EclipseLink module within a RuntimeException.
Issue: #608
=> Fix the issue where the Polaris Server exposes backend metadata in the error response body when the database is not bootstrapped.

api/polaris-catalog-service/build.gradle.kts, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/rest/CreateGenericTableRESTRequest.java, spec/generated/bundled-polaris-catalog-service.yaml, spec/polaris-catalog-apis/generic-tables-api.yaml
Add  a base-location keyword for GenericTable create request and GenericTable load response.
=> [SPEC] Add base-location keyword for GenericTable API

quarkus/admin/distribution/LICENSE, quarkus/admin/distribution/NOTICE, quarkus/distribution/LICENSE, quarkus/distribution/NOTICE, quarkus/server/distribution/LICENSE, quarkus/server/distribution/NOTICE
This is due to the lib version update by renovate bot #1842 and #1845, and this is needed in 1.0 release as 1.0.x branch has these version update. cc @jbonofre
=> Update LICENSE for binary distributions

gradle/libs.versions.toml, integration-tests/build.gradle.kts, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisManagementServiceIntegrationTest.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/el/EclipselinkPurgeCommandTest.java, quarkus/admin/src/test/java/org/apache/polaris/admintool/relational/jdbc/RelationalJdbcPurgeCommandTest.java, quarkus/service/build.gradle.kts, quarkus/service/src/test/java/org/apache/polaris/service/quarkus/metrics/MetricsTestBase.java
=> Avoid using org.testcontainers.shaded.**

build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/polaris-spotless.gradle.kts, codestyle/checkstyle.xml, gradle/libs.versions.toml, plugins/spark/v3.5/spark/build.gradle.kts, quarkus/test-commons/build.gradle.kts
Now ready for review.
I'm implementing my own suggestion of using a Checkstyle rule to check for forbidden packages.
=> feat(build): Add Checkstyle plugin and an IllegalImport rule

client/python/pyproject.toml
Mypy did a new release 1.16.1 and it cause our CI to fail for about 20 minutes due to missing wheel (upload not completed)
```
| Unable to find installation candidates for mypy (1.16.1)
| 
| This is likely not a Poetry issue.
| 
|   - 14 candidate(s) were identified for the package
|   - 14 wheel(s) were skipped as your project's environment does not support the identified abi tags
| 
| Solutions:
| Make sure the lockfile is up-to-date. You can try one of the following;
| 
|     1. Regenerate lockfile: poetry lock --no-cache --regenerate
|     2. Update package     : poetry update --no-cache mypy
| 
| If neither works, please first check to verify that the mypy has published wheels available from your configured source that are compatible with your environment- ie. operating system, …
```
=> Python CI: pin mypy version to avoid CI failure due to new release

.asf.yaml, .github/workflows/gradle.yml
This is a simple attempt to reduce the CI execution time for pull requests. Instead of executing all tests in the same job, it parallelizes the tests in 4 jobs:
* Code style & publishing checks
* Unit tests
* Quarkus tests 
* Integration tests
This could certainly be improved further, but I observed a total execution time around 10 minutes instead of 20 minutes before (at the cost of more compute power, of course).
=> feat(ci): Split Java Gradle CI in many jobs to reduce execution time

service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/CatalogHandlerUtils.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java, service/common/src/test/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapterTest.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
Details can be found in this issue: https://github.com/apache/polaris/issues/1848
=> Fix Pagination for Catalog Federation

site/content/in-dev/unreleased/getting-started/quickstart.md
Ref PR on why this is needed: https://github.com/apache/polaris/pull/1010/files
We have it correct in all other places except this one.
=> Update doc to fix docker build inconsistency issue

site/content/in-dev/unreleased/getting-started/install-dependencies.md
Minor change to simply the install dependency doc:
1. change from two lines to one line with `git clone`
2. instead of asking users to check official jq doc (which will tell them the same thing about brew) and we are using brew for `docker` and `jenv` already in this doc. Thus, I think it makes more senses to provide brew command directly.
=> Simplify install dependency doc

helm/polaris/Chart.yaml, helm/polaris/README.md
The reason to remove it
1. The maintainer list is optional. 
2. It adds code maintenance burden, which make it inaccurate inevitably.
3. We don't do that in elsewhere of the project. 
More discussions are here, https://github.com/apache/polaris/pull/1957#discussion_r2170162461.
=> Remove the maintainer list in Helm Chart

site/content/in-dev/unreleased/getting-started/using-polaris.md
NIT: change the long command into multi-lines for easy read-ability as we are following this "rule" throughout the rest of the doc
Current one is following (horizontal scrolling bar is there to get to the end):
=> Use multi-lines instead of single line for long command

plugins/spark/v3.5/spark/build.gradle.kts
Previously the build code would add LICENSE and NOTICE files from other shaded dependencies, some of which could potentially shade the project's LICENSE or NOTICE or cause confusion as to which file was correct.
To fix this a post-processing task is added which removes all potentially confusing files and manually adds the project LICENSE and NOTICE files back to the jar.
---
I tried fixing this via exclusions and include rules but for whatever reason the shadowJar plugin didn't seem to behave
well. The Duplication strategy apparently can only apply to the final jar so unless I was able to individually exclude the
licenses from all dependencies I was a bit stuck. To avoid the issue entirely, I just post process the jar. This adds about 10 
seconds to the task on my machine but I figure …
=> fix: Only include project LICENSE and NOTICE in Spark Client Jar

site/content/in-dev/unreleased/admin-tool.md
Fix admin tool doc with following changes:
1. Remove refs for `Two distribution archives in...` as this command no longer does so
2. Change wording from standalone JAR (often refs to as uber-JAR to Fast-JAR) 
3. Update JAR refs in the sample commands
=> Fix admin tool doc

helm/polaris/ci/fixtures/persistence.yaml, helm/polaris/ci/persistence-values.yaml, helm/polaris/templates/configmap.yaml, helm/polaris/templates/deployment.yaml, helm/polaris/tests/configmap_test.yaml, helm/polaris/tests/deployment_test.yaml, helm/polaris/values.yaml
Polaris needs to support relational-jdbc as the default persistence type for simpler database configuration and better cloud-native deployment experience.
Currently, the Helm chart only supports eclipse-link persistence type as the default, which requires complex JPA configuration with persistence.xml files.
- Add relational-jdbc persistence type support to Helm chart
- Use relational-jdbc as the default persistence type
- Inject JDBC configuration (username, password, jdbc_url) through Kubernetes Secrets as environment variables
- Maintain backward compatibility with eclipse-link
- Updated persistence-values.yaml for CI testing
- Updated test coverage for relational-jdbc configuration
- JDBC credentials are injected via QUARKUS_DATASOURCE_* environment variables from Secret
- Secret …
=> Add relational-jdbc to helm

CHANGELOG.md, build.gradle.kts, gradle/libs.versions.toml, site/content/release-guide.md
* Add rudimentary CHANGELOG.md
* Add the Jetbrains Changelog Gradle plugin to help managing CHANGELOG.md
Dev list discussion: https://lists.apache.org/thread/qznf8toht1r7ml35lt4p8nwlk9op638v
=> Add CHANGELOG

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/QueryGenerator.java
* Fix javadoc warning: invalid input: '&'
* Correct javadoc text in generateOverlapQuery()
=> Correct javadoc text in generateOverlapQuery()

runtime/distribution/build.gradle.kts
This PR is to fix the sign failure of this command: `./gradlew build sourceTarball -Prelease -PuseGpgAgent -PsignArtifacts -x test -x intTest`. Here are error message: 
```
> Task :polaris-distribution:signDistTar FAILED
[Incubating] Problems report is available at: file:///Users/ygu/asf/polaris/build/reports/problems/problems-report.html
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':polaris-distribution:signDistTar'.
> Cannot perform signing task ':polaris-distribution:signDistTar' because it has no configured signatory
```
=> Fix the sign failure

site/content/in-dev/unreleased/access-control.md
Minor update for the access control doc:
1. Remove the misleading section on privileges can only be granted at catalog level. I've tested the fine-grained access controls and confirmed that privileges can be applied to an individual table in the catalog.
=> Fix doc to remove outdated note about fine-grained access control support

helm/polaris/ci/persistence-values.yaml, helm/polaris/templates/configmap.yaml, helm/polaris/tests/deployment_test.yaml, helm/polaris/values.yaml
Through documentation review and testing, I confirmed that the **db-kind** is determined at build time and cannot be modified at runtime. 
To prevent user confusion, this PR removes the db kind configuration option from the Helm chart since it cannot be set during runtime deployment.
This change improves the user experience by eliminating a non-functional configuration parameter that could mislead users into thinking they can change the database kind after deployment.
=> fix: Remove runtime-immutable db kind configuration from Helm chart

site/content/in-dev/unreleased/command-line-interface.md
PR for https://github.com/apache/polaris/issues/1866
=> Fix doc for CLI update

spec/polaris-management-service.yml
In #1929 it was pointed out that the example in the Polaris docs suggests that users can provide a client ID during principal creation:
This PR attempts to fix this by adding an explicit example to the spec.
=> Improve createPrincipal example in API docs

site/content/in-dev/unreleased/command-line-interface.md
PR for https://github.com/apache/polaris/issues/1864
=> Add doc for repair option

.github/workflows/spark_client_regtests.yml, plugins/spark/v3.5/regtests/README.md, plugins/spark/v3.5/regtests/docker-compose.yml, plugins/spark/v3.5/regtests/run.sh, plugins/spark/v3.5/regtests/setup.sh
Spark can use the Spark Client with --jars and --packages use case, the regression test today only covers the --jars use case. 
This PR adds regression test with the --packages use case.
=> Add regression test coverage for Spark Client with package conf

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/DatasourceOperations.java
#1942 changed the way that the bootstrap init script is handled, but it added an extra `InputStream.close` call that shouldn't be needed after the BufferedReader [here](https://github.com/apache/polaris/pull/1942/files#diff-de43b240b5b5e07aba7e89f5515a417cefd908845b85432f3fcc0819911f3e2eR89) is closed. This PR removes that extra call.
=> Remove unnecessary `InputStream.close` call

client/templates/regenerate.sh
Currently if an end-user try to rerun `regenerate.sh` (as part of polaris repair or OpenAPI code regen, it will keep adding new headers to the existed README.nd. As this file is not part of the template, update the list to exclude this file.
=> Ignore regenerate.sh on README.md

api/iceberg-service/build.gradle.kts, api/management-model/build.gradle.kts, api/management-service/build.gradle.kts, api/polaris-catalog-service/build.gradle.kts
The jaxrs-resteasy OpenAPI generator adds the generation timestamp to the generated sources by default. This behavior leads to different code for every generation, leading to unnecessary rebuilds (and re-tests), because the generated `.class` files are different.
=> OpenAPI-generate: Omit generation timestamp

.asf.yaml
Some devs were added in the past to `.asf.yaml` to let CI run w/o committer approval. After [INFRA-26985](https://issues.apache.org/jira/browse/INFRA-26985) this is no longer necessary, so the file can be cleaned up.
=> Cleanup collaborators in `.asf.yaml`

api/iceberg-service/build.gradle.kts, api/management-model/build.gradle.kts, api/management-service/build.gradle.kts, api/polaris-catalog-service/build.gradle.kts, build-logic/src/main/kotlin/polaris-java.gradle.kts
The current way how OpenAPI Java code is generated suffers from a bunch of issues:
* Changes to any of the source spec files requires a Gradle `clean`, otherwise old generated Java source will remain - i.e. "no longer" existing sources are not removed. This is addressed by adding an additional action to `GenerateTask`.
* The output of `GenerateTask` was explicitly not cached, this is removed, so the output is cached.
* Add explicit inputs to `GenerateTask` to the whole templates and spec folders.
=> Fix bunch of OpenAPI generation issues

runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisGenericTableCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java
also rename the field for clarity and consistency
=> Remove duplicate MetaStoreManagerFactory mocks

site/content/release-guide.md
This PR changes the release dir name from `apache-polaris-x.y.z` to `x.y.z` to be consistent with the historical releases. Either name is fine, the intent is to make sure they are consistent.
=> Update release-guide.md for release dir name

plugins/spark/v3.5/getting-started/notebooks/Dockerfile, plugins/spark/v3.5/regtests/setup.sh, regtests/setup.sh, site/content/in-dev/polaris-spark-client.md
We had better use `closer.lua` download script instead of a direct link in order to reduce the flakiness of `archive.apache.org`.
In addition, this complies with Apache INFRA guidelines, too.
- https://infra.apache.org/release-download-pages.html#download-scripts
> Apache project download pages must use a closer.lua script. You'll find below a standard mechanism to let you easily create scripts that comply with the ASF distribution policy.
=> Use `closer.lua` download script to download Apache Spark distribution

build.gradle.kts
The newly added `store-gradle-cache` CI job has run some Gradle task to trigger Gradle's automatic cache cleanup. In the source project Nessie we used a simple task `showVersion` to do this. As having this task in Polaris might be useful, adding this task as there's no other suitable task (cheap and not generating much output) seems legit.
=> Fix CI (no 2)

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/MetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheConfig.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, runtime/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, runtime/service/src/main/java/org/apache/polaris/service/quarkus/storage/QuarkusStorageCredentialCacheConfig.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogHandlerAuthzTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolarisGenericTableCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/PolicyCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/config/RealmEntityManagerFactory.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
since `StorageCredentialCache` is application scoped and after 6ddd1487877ce13f2640ea73437b24bbd7c3eb09 its constructor no longer uses the `RealmContext` passed into `getOrCreateStorageCredentialCache` we can now let all `PolarisEntityManager` instances share the same `StorageCredentialCache`.
=> Use application-scoped StorageCredentialCache

.github/renovate.json5
Looks that I accidentally broke Renovate with #1891. This was made under the impression of the [Renovate change to support `baseBranches` in forking-renovate] (https://github.com/renovatebot/renovate/pull/36054). However, a [later Renovate change](https://github.com/renovatebot/renovate/pull/35579)  seems to break that.
The plan here is to:
1. remove the regex from our `baseBranches` option - if that doesn't work then
2. just use the default branch
Relevant [renovate issue](https://github.com/renovatebot/renovate/issues/28700#issuecomment-3073312040)
=> Attempt to make Renovate work again

polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheKey.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java
note that `entityId` was not part of the `equals`/`hashCode` and thus did not need to be a field
=> Use PolarisImmutable for StorageCredentialCacheKey

.github/renovate.json5
Per the mailing list thread "[DISCUSS] Disable renovatebot on release branches", we should not do automatic dependency upgrades for release branches. Since it seems `release/1.0.x` is a release branch, we can remove this regex from renovate's list.
=> Disable renovatebot on release branches

runtime/service/src/test/java/org/apache/polaris/service/quarkus/task/BatchFileCleanupTaskHandlerTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/task/ManifestFileCleanupTaskHandlerTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/task/TableCleanupTaskHandlerTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/FileIOFactory.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestFileIOFactory.java
also cleanup warnings in `TableCleanupTaskHandlerTest`
=> Add TestFileIOFactory helper

client/python/cli/command/catalogs.py, client/python/cli/constants.py, client/python/test/test_cli_parsing.py
PRs #1925 and #1912 were merged around the same time.  This PR connects the two changes and enables the CLI to accept IMPLICIT authentication type. 
Since Hadoop federated catalogs rely purely on IMPLICIT authentication, the CLI parsing test has been updated to reflect the same.
=> Add IMPLICIT authentication support to the CLI

runtime/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisS3InteroperabilityTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogTest.java
creation of `IcebergCatalog` instances in `AbstractIcebergCatalogTest` was quite redundant as test methods use the same parameters most of the time.
also remove unused fields in 2 other test classes.
=> Add newIcebergCatalog helper

client/python/cli/polaris_cli.py, client/python/pyproject.toml, polaris, regtests/Dockerfile
Currently we are using `<git_root_dir>/polaris` as the entrypoint to interact with polaris CLI. This is a okay for local usage but it is not ideal for others who doesn't want to downlaod the entire code base to just use the CLI as well as making polaris client distributable as part of release. To address this issue, we will need to public polaris as an CLI without depends on the bash script.
This PR addressed this problem with following changes:
1. create main in `polaris_cli.py` as that will be the entrypoint for us to use
2. set scripts directly (which is point to item 1) and include both polaris and cli directories as part of packaging. Due to `client/python/polais` is auto generated from OpenAPI and `poetry.core.masonry.api` doe build backend (with `poetry.core.masonry.api` as build …
=> Package polaris client as python package

.github/workflows/gradle.yml, .github/workflows/nightly.yml, .github/workflows/spark_client_regtests.yml, build-logic/src/main/kotlin/publishing/util.kt
CI sometimes fails with this failure:
```
* What went wrong:
Execution failed for task ':generatePomFileForMavenPublication'.
> Unable to process url: https://api.github.com/repos/apache/polaris/contributors?per_page=1000
```
The sometimes failing request fetches the list of contributors to be published in the "root" POM. Unauthorized GH API requests have an hourly(?) limit of 60 requests per source IP. Authorized requests have a much higher rate limit. We do have a GitHub token available in every CI run, which can be used in GH API requests. This change adds the `Authorization` header for the failing GH API request to leverage the higher rate limit and let CI not fail (that often).
=> CI: Address failure from accessing GH API

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisEntityManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/PolarisResolutionManifest.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/ResolverFactory.java, runtime/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractPolarisGenericTableCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractPolicyCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/IcebergCatalogHandlerAuthzTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/config/RealmEntityManagerFactory.java, service/common/src/main/java/org/apache/polaris/service/context/catalog/PolarisCallContextCatalogFactory.java, service/common/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java, service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
`PolarisEntityManager.prepareResolver` was the only place that used the
`EntityCache`.
By introducing an application-scoped `ResolverFactory` the creation of
an `EntityCache` is decided only once in `QuarkusProducers`, which will become
the only place where `MetaStoreManagerFactory.getOrCreateEntityCache` gets called.
Note that the little left-over functionality of `PolarisEntityManager` can
be split out to smaller but more dedicated interfaces in a follow-up most likely.
=> Extract ResolverFactory from PolarisEntityManager

Makefile, client/templates/regenerate.sh
Similar to https://github.com/apache/polaris/pull/2051/files, this PR add support for podman for python client regeneration script. Also, as `DOCKER` seems to be preferred, I changed the `Makefile` to use the same to avoid confusion later.
=> Add podman support

polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/dao/entity/ScopedCredentialsResult.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/storage/AccessConfig.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/StorageAccessProperty.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheEntry.java, polaris-core/src/main/java/org/apache/polaris/core/storage/gcp/GcpCredentialsStorageIntegration.java, polaris-core/src/test/java/org/apache/polaris/core/storage/AccessConfigTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/InMemoryStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/aws/AwsCredentialsStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/catalog/io/DefaultFileIOFactory.java, service/common/src/main/java/org/apache/polaris/service/storage/PolarisStorageIntegrationProviderImpl.java
This refactoring does not change Polaris behaviour.
* Move storage-specific access properties processing logic from core code to storage integration implementations.
* Add `isExpirationTimestamp` flag to `StorageAccessProperty` to allow them to be processed uniformly.
* Prepare for supporting access config properties that may have different values in Polaris Servers and Clients. This enables future enhancements to support different S3 endpoint DNS names in servers and clients for #1530
=> Push AccessConfig creation to PolarisStorageIntegration

integration-tests/src/main/java/org/apache/polaris/service/it/env/ManagementApi.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisManagementServiceIntegrationTest.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisEntityManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManager.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BaseResolverTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/admin/ManagementServiceTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractPolarisGenericTableCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractPolicyCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/test/PolarisIntegrationTestFixture.java, service/common/src/main/java/org/apache/polaris/service/auth/DefaultAuthenticator.java
`PolarisMetaStoreManager.readEntityByName` is quite a low-level api, so we can simplify a lot of callers with additional helpers:
- add `PolarisMetaStoreManager.findRootPrincipal`
- add `PolarisMetaStoreManager.findPrincipalByName`
- add `PolarisMetaStoreManager.findPrincipalRoleByName`
also we now prefer `PolarisEntityConstants` where applicable
=> Add Principal lookup helpers to PolarisMetaStoreManager

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisResolvedPathWrapper.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisResolvedPathWrapperTest.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, service/common/src/test/java/org/apache/polaris/service/admin/PolarisAdminServiceTest.java
I encountered the bug while implementing RBAC for federation. 
For grant/revoke operations on tables, polaris checks the subtype of the leaf entity and make sure it matches. However, for namespace the only check is that the resolved path is not null. 
Ideally we should check that the entire path matches the one sent in the request. Further, all entities except the root should be of the type NAMESPACE. 
Testing: 
Added unit tests.
=> Fix Namespace resolution on grant/revoke privilege operations

persistence/eclipselink/src/main/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcBasePersistenceImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/BaseMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapTransactionalPersistenceImpl.java
as a static helper method its strongly preferable to not depend on the full `PolarisCallContext` if not necessary.
=> Remove PolarisCallContext from BaseMetaStoreManager.extractStorageConfiguration

polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapMetaStore.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TreeMapTransactionalPersistenceImpl.java
the concrete class `TreeMapMetaStore` only uses `PolarisDiagnostics` from the given `PolarisCallContext`.
we also remember `initialDiagnosticServices` and reset it after a transaction for consistency (not sure if it will ever get used outside a transaction context though)
=> Remove PolarisCallContext from TreeMapMetaStore

service/common/src/main/java/org/apache/polaris/service/auth/DefaultOAuth2ApiService.java, service/common/src/main/java/org/apache/polaris/service/auth/JWTBroker.java, service/common/src/main/java/org/apache/polaris/service/auth/NoneTokenBrokerFactory.java, service/common/src/main/java/org/apache/polaris/service/auth/TokenBroker.java
this is working towards the removal of the `CallContext.CURRENT_CONTEXT` threadlocal
also remove deprecated methods which seem to be unused in the codebase
=> Remove getCurrentContext from JWTBroker

client/python/cli/constants.py, client/python/cli/options/parser.py, client/python/cli/polaris_cli.py
Enable request tracing via money patching:
Original:
```
➜  polaris git:(python_client_debug_flag) ./polaris --profile dev principals list
{"name": "root", "clientId": "root", "properties": {}, "createTimestamp": 1753151091780, "lastUpdateTimestamp": 1753151091780, "entityVersion": 1}
```
With debug mode (dummy password from the getting start example):
```
➜  polaris git:(python_client_debug_flag) ./polaris --profile dev --debug principals list
Request: POST http://localhost:8181/api/catalog/v1/oauth/tokens
Headers: HTTPHeaderDict({'Content-Type': 'application/x-www-form-urlencoded'})
Body: grant_type=client_credentials&client_id=root&client_secret=s3cr3t&scope=PRINCIPAL_ROLE%3AALL
Request: GET http://localhost:8181/api/management/v1/principals
Headers: {'Accept': 'application/json', …
```
=> Enable python client debug flag

runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogTest.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java, service/common/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java, spec/generated/bundled-polaris-catalog-service.yaml
In some cases, we were using CommitFailedException to represent commit conflicts, which returns the correct 409 response but is tied to Iceberg.
However, some of these conflicts originate from Polaris, making CommitConflictException a more appropriate and accurate choice.
This change updates those instances to improve clarity and exception handling semantics.
Resolves #2168
=> Replace CommitFailedException with CommitConflictException

polaris-core/src/main/java/org/apache/polaris/core/context/CallContext.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/catalog/AbstractIcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/quarkus/test/PolarisIntegrationTestFixture.java, service/common/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java, service/common/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogAdapter.java, service/common/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogAdapter.java
the last callers of `CallContext.getCurrentContext` had been
removed in the following commits:
- 756e535fabe150eefdfe16f3c61c1207217d2e2f
- e7eb59f6d89a5891381c805c9ed4244601d5b430
- 4d94745db36c5d4907cf34d749a3a2690f8e4fff
thus we can now remove the `CURRENT_CONTEXT` threadlocal and all
associated methods.
=> Remove CallContext.CURRENT_CONTEXT

polaris-core/src/main/java/org/apache/polaris/core/entity/CatalogEntity.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsStorageConfigurationInfo.java, polaris-core/src/test/java/org/apache/polaris/core/storage/aws/AwsStorageConfigurationInfoTest.java, runtime/service/src/intTest/java/org/apache/polaris/service/quarkus/it/QuarkusRestCatalogMinIOSpecialIT.java, spec/polaris-management-service.yml
This API change is backward compatible with older clients and server using old storage configuration.
* The `endpointInternal` allows Polaris Servers to use a different host name (or IP address) for accessing S3 storage than clients. This is not a common use case, but may be relevant is more complex environments.
* If not set `endpointInternal` defaults to `endpoint`.
* The STS endpoint default changes to `endpointInternal`.
Contributes to #1530
=> feat: Add `endpointInternal` to `AwsStorageConfigInfo`

api/iceberg-service/build.gradle.kts, api/management-model/build.gradle.kts, api/management-service/build.gradle.kts, api/polaris-catalog-service/build.gradle.kts, build-logic/src/main/kotlin/publishing/shadowPub.kt
* `shadowPub.kt` the change removes a special case that doesn't apply to Polaris
* `api/...` build scripts - changes due to nullable type handling (`Property<String>` vs `Property<String?>` - latter is ... weird)
=> Prepare upgrade to Gradle 9

runtime/service/src/test/java/org/apache/polaris/service/quarkus/admin/ManagementServiceTest.java
this takes less code and is more flexible in the future
=> Replace TestPolarisMetaStoreManager with Mockito.spy

polaris-core/src/main/java/org/apache/polaris/core/entity/CatalogEntity.java, polaris-core/src/main/java/org/apache/polaris/core/storage/FileStorageConfigurationInfo.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageConfigurationInfo.java, polaris-core/src/main/java/org/apache/polaris/core/storage/StorageConfigurationOverride.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsStorageConfigurationInfo.java, polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureStorageConfigurationInfo.java, polaris-core/src/main/java/org/apache/polaris/core/storage/gcp/GcpStorageConfigurationInfo.java, polaris-core/src/test/java/org/apache/polaris/core/storage/InMemoryStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/aws/AwsStorageConfigurationInfoTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/PolarisStorageConfigurationInfoTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/aws/AwsCredentialsStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java
This change eventually enables usage of the `*StorageConfigurationInfo` in the `StorageCredentialCacheKey` due to the then memoized hash-code values, to eliminate a couple of JSON re-serializations.
=> Make `*StorageConfigurationInfo` types immutable

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcBasePersistenceImpl.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/AtomicMetastoreManagerWithJdbcBasePersistenceImplTest.java
otherwise every call to `MetaStoreManagerFactory.getOrCreateSession` was running a query to load the schema version.
i am assuming the version can not change at runtime.
=> JdbcMetaStoreManagerFactory determines schemaVersion once per realm

runtime/service/src/test/java/org/apache/polaris/service/task/TaskExecutorImplTest.java, runtime/service/src/testFixtures/java/org/apache/polaris/service/TestServices.java
if diagnostics checks are failing in our tests we want to know about it as input validation and object invariants of production code should never be bypassed
=> Stop mocking PolarisDiagnostics

runtime/service/src/test/java/org/apache/polaris/service/admin/ManagementServiceTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java, runtime/service/src/test/java/org/apache/polaris/service/task/BatchFileCleanupTaskHandlerTest.java, runtime/service/src/test/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandlerTest.java, runtime/service/src/test/java/org/apache/polaris/service/task/TaskExecutorImplTest.java, runtime/service/src/testFixtures/java/org/apache/polaris/service/TestServices.java
also add local `newCallContext` helper in some test classes
=> Add TestServices.newCallContext

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, runtime/service/src/main/java/org/apache/polaris/service/persistence/InMemoryAtomicOperationMetaStoreManagerFactory.java, runtime/service/src/main/java/org/apache/polaris/service/persistence/InMemoryPolarisMetaStoreManagerFactory.java, runtime/service/src/main/java/org/apache/polaris/service/task/TaskExecutorImpl.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/entity/CatalogEntityTest.java
`new PolarisDefaultDiagServiceImpl()` should not be used anywhere in production code outside of `QuarkusProducers`, as it turns out a `PolarisDiagnostics` instance already was getting injected.
this actually required fixing the setup in `CatalogEntityTest` so that we dont pass in `null`.
for clarity we mark ctors that only exist for CDI as protected so that they dont get used by tests accidentally.
=> Use injected PolarisDiagnostics in MetaStoreManagerFactory impls

polaris
Currently when running `--repair` with client, it will produce following message
```
➜  polaris git:(client_repair_mode) ./polaris --repair
Configuration on demand is an incubating feature.
> Task :regeneratePythonClient
...
Writing lock file
Installing the current project: polaris (1.0.0)
Dependencies repaired.
Traceback (most recent call last):
File "/Users/yong/Desktop/GitHome/polaris/polaris-venv/bin/polaris", line 6, in <module>
sys.exit(main())
~~~~^^
File "/Users/yong/Desktop/GitHome/polaris/client/python/cli/polaris_cli.py", line 219, in main
PolarisCli.execute()
~~~~~~~~~~~~~~~~~~^^
File "/Users/yong/Desktop/GitHome/polaris/client/python/cli/polaris_cli.py", line 70, in execute
client_builder = PolarisCli._get_client_builder(options)
File …
```
=> Clean exit when running repair mode for client

runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java, runtime/service/src/test/java/org/apache/polaris/service/admin/ManagementServiceTest.java
`PolarisAdminService` has multiple spots where it is working around the sub-optimal `PolarisMetaStoreManager` APIs.
This results in multiple fixes like:
https://github.com/apache/polaris/pull/1949
https://github.com/apache/polaris/pull/2258
While eventually the underlying APIs should be improved, for now we can make a single central workaround and clean up some redundant code. Also we can improve the return types as callers are not interested in details of the entity layer.
=> Add PolarisAdminService.loadEntities helper

Makefile
`CONTAINER_TOOL` got renamed to `DOCKER` in
6764a886857da464e3de11013165cd82aa5fedcb
but then
eda70740a4e327889f1ac38295d23c8947d87703
added more `CONTAINER_TOOL` usage
=> Fix python CI client-integration-test

site/content/in-dev/unreleased/realm.md
`BasePolarisAuthenticator` has been renamed to `DefaultAuthenticator`: #1397
=> fix(docs): update BasePolarisAuthenticator to DefaultAuthenticator

runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java
This PR addresses the gap in Hadoop federation to ensure that we initialize the hadoop configuration prior to initializing the catalog object.
The iceberg library expects the hadoop configuration to be initialized before creating a HadoopCatalog object. This change ensures that Polaris is compatible with the underlying iceberg library. Additionally, since the config initialization is based on the underlying (default) core-site.xml file, the change ensures that the federated catalog was created using `IMPLICIT` authentication mode. 
Testing: 
Due to current limitations in the current test setup, tested the change manually.
[TODO] Add a regtest with hadoop federation once the change is baked into the apache/polaris docker image.
=> Fix Hadoop federation to initialize the configuration

.github/workflows/gradle.yml
when having to debug CI test failures its much more convenient to be able to download the html report compared to the XML reports (as the latter requires to you find the right file/failure manually).
=> Let CI archive html test reports

polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/generic/GenericTableCatalogAdapter.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogAdapter.java
this works towards breaking down `CallContext` usage and contents
=> Replace CallContext with RealmConfig in enforceFeatureEnabledOrThrow

polaris-core/src/main/java/org/apache/polaris/core/entity/CatalogEntity.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageConfigurationInfo.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractIcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractPolarisGenericTableCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractPolicyCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/IcebergCatalogHandlerAuthzTest.java, runtime/service/src/test/java/org/apache/polaris/service/entity/CatalogEntityTest.java
the concrete `setStorageConfigurationInfo` method in the `Builder` only uses the `RealmConfig` so we should pass that instead.
=> Replace CallContext with RealmConfig in CatalogEntity

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisManagementServiceIntegrationTest.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisServiceImpl.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAdminServiceAuthzTest.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAdminServiceTest.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/IcebergCatalogHandlerAuthzTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/PolarisGenericTableCatalogHandlerAuthzTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/PolicyCatalogHandlerAuthzTest.java
the `boolean` return values of many methods in `PolarisAdminService`
were often simply not getting used at all, thus the REST api returned
success in those cases even though the `PrivilegeResult` was marked
as failed.
due to this fix a silently failing test now needs to be adjusted.
we return the `PrivilegeResult` instead of a `boolean` to give the
client at least some indication of what has gone wrong on the server
side.
note that some of the other operations were throwing Expcetions already,
which are already reported back correctly to the client.
=> Fix REST responses for failed Admin operations

polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisAuthorizer.java, polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisAuthorizerImpl.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/common/CatalogHandler.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogHandler.java, runtime/service/src/main/java/org/apache/polaris/service/config/ServiceProducers.java, runtime/service/src/test/java/org/apache/polaris/service/admin/ManagementServiceTest.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractIcebergCatalogViewTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractPolarisGenericTableCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractPolicyCatalogTest.java
all methods in `PolarisAuthorizer` currently have a `CallContext` parameter.
in its only implementation only `CallContext.getRealmConfig` is getting used.
so since `PolarisAuthorizer` cant be used outside a request, we can simply make it request-scoped and inject the request-scoped `RealmConfig` directly.
=> Make PolarisAuthorizer RequestScoped

polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisBaseEntity.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/BaseMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BasePolarisMetaStoreManagerTest.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java
seems like these helpers existed for a long time but were just not
getting used consistently
=> Use asMap property helpers 

polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/BaseMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java
similar to 7af85be7f45c933a377314a669e2a16633c93532 we should prefer the existing helper methods on the entity instead
=> Remove BaseMetaStoreManager.serializeProperties

site/content/in-dev/unreleased/entities.md, site/content/in-dev/unreleased/getting-started/using-polaris.md
- fixed dead link to catalog definition in Iceberg docs on Entities page
- removed single quotes from credential parameter in the cmdline example for connecting a local spark-sql: env variables need to be resolved in cmdline, they will not be resolved by spark-sql itself.
=> fix: minor corrections of documentation

CHANGELOG.md
=> Mention Helm chart support for PodDisruptionBudget in CHANGELOG.md

site/content/release-guide.md
While doing the latest release, I found some issues in the release guide. This PR fixes:
* use dev@polaris.apache.org for announcement
* publish Docker images only when the vote passed (we are not suppose to publish any public artifacts before the vote is completed)
* update the vote email accordingly
=> Fixes on the release guide

runtime/service/src/main/java/org/apache/polaris/service/task/BatchFileCleanupTaskHandler.java, runtime/service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java, runtime/service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java, runtime/service/src/main/java/org/apache/polaris/service/task/TaskFileIOSupplier.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java
we cant just convert a `TaskEntity` to a `IcebergTableLikeEntity` as the
`getTableIdentifier()` method will not return a correct value by using
the name of the task and its parent namespace (which is empty?).
task handlers instead need to pass in the `TableIdentifier` that they
already inferred via `TaskEntity.readData`.
=> Fix TableIdentifier in TaskFileIOSupplier

site/content/in-dev/unreleased/access-control.md
Fix https://github.com/apache/polaris/issues/2418
=> Doc fix: Access control page update

polaris-core/src/main/java/org/apache/polaris/core/policy/PolicyEntity.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalog.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/policy/PolicyCatalogHandler.java
this is a follow-up to https://github.com/apache/polaris/pull/2290
the optimization is to use `listEntities` instead of `loadEntities` when
there is no `policyType` filter to apply
=> Optimize PolicyCatalog.listPolicies

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/AtomicMetastoreManagerWithJdbcBasePersistenceImplTest.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/BaseMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisTreeMapAtomicOperationMetaStoreManagerTest.java, runtime/service/src/main/java/org/apache/polaris/service/persistence/InMemoryAtomicOperationMetaStoreManagerFactory.java
the ultimate goal is removing the `PolarisCallContext` parameter from every `PolarisMetaStoreManager` interface method, so we make steps towards reducing its usage first.
=> Add PolarisDiagnostics field to BaseMetaStoreManager

CHANGELOG.md, runtime/service/src/main/java/org/apache/polaris/service/auth/ActiveRolesAugmentor.java, runtime/service/src/main/java/org/apache/polaris/service/auth/ActiveRolesProvider.java, runtime/service/src/main/java/org/apache/polaris/service/auth/AuthenticationRealmConfiguration.java, runtime/service/src/main/java/org/apache/polaris/service/auth/DefaultActiveRolesProvider.java, runtime/service/src/main/java/org/apache/polaris/service/config/ServiceProducers.java, runtime/service/src/test/java/org/apache/polaris/service/auth/ActiveRolesAugmentorTest.java
This change deprecates `ActiveRolesProvider` for removal. The actual removal is here: #2390.
=> Deprecate ActiveRolesProvider for removal

runtime/service/src/main/java/org/apache/polaris/service/config/ProductionReadinessChecks.java, runtime/service/src/main/java/org/apache/polaris/service/metrics/MetricsConfiguration.java, runtime/service/src/main/java/org/apache/polaris/service/metrics/PolarisValueExpressionResolver.java, runtime/service/src/test/java/org/apache/polaris/service/metrics/MetricsTestBase.java, runtime/service/src/test/java/org/apache/polaris/service/metrics/RealmIdTagEnabledMetricsTest.java, runtime/service/src/test/java/org/apache/polaris/service/metrics/UserPrincipalTagDisabledMetricsTest.java, runtime/service/src/test/java/org/apache/polaris/service/metrics/UserPrincipalTagEnabledMetricsTest.java, server-templates/api.mustache
Fixes #2444.
This PR adds a user principal tag in metrics and an associated configuration option that turns it on. 
This is the following: `polaris.metrics.user-principal-tag.enable-in-api-metrics`, and **by default this is set to `false`.**
To retrieve the user principal ID it uses the SecurityContext and annotates it with a `MeterTag` annotation under the key `principal`.
=> Add user principal tag in metrics

build-logic/src/main/kotlin/Utilities.kt, build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/polaris-reproducible.gradle.kts, runtime/distribution/build.gradle.kts, tools/config-docs/site/build.gradle.kts
As part of the effort for #2204, this change fixes a few aspects around reproducible builds:
Some Gradle projects produce archive files, but don't get the necessary Gradle archive-tasks settings applied: one not-published project but also the tarball&zip of the distribution. This change moves the logic to the new build-plugin `polaris-reproducible`.
Another change is to have some Quarkus generated jar files adhere to the same conventions, which are constant timestamps for the zip entries and a deterministic order of the entries. That's sadly not a full fix, as the classes that are generated or instumented by Quarkus differ in each build.
Contributes to #2204
=> Built: improve reproducible archive files

CHANGELOG.md, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/TransactionWorkspaceMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, polaris-core/src/main/java/org/apache/polaris/core/rest/PolarisResourcePaths.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisCredentialVendor.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/StorageAccessProperty.java, polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegration.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCache.java, polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheKey.java, polaris-core/src/main/java/org/apache/polaris/core/storage/gcp/GcpCredentialsStorageIntegration.java, polaris-core/src/test/java/org/apache/polaris/core/storage/InMemoryStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/aws/AwsCredentialsStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java, polaris-core/src/test/java/org/apache/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java, runtime/service/src/intTest/java/org/apache/polaris/service/it/RestCatalogMinIOSpecialIT.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalog.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapter.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/SupportsCredentialDelegation.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/io/DefaultFileIOFactory.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/io/FileIOUtil.java, runtime/service/src/main/java/org/apache/polaris/service/storage/PolarisStorageIntegrationProviderImpl.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/IcebergCatalogHandlerAuthzTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogAdapterTest.java
Rebased version of https://github.com/apache/polaris/pull/1164
=> add refresh credentials property to loadTableResult

runtime/service/src/main/java/org/apache/polaris/service/auth/DefaultOAuth2ApiService.java, runtime/service/src/main/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandler.java, runtime/service/src/main/java/org/apache/polaris/service/task/TableCleanupTaskHandler.java, runtime/service/src/main/java/org/apache/polaris/service/task/TaskUtils.java, runtime/service/src/test/java/org/apache/polaris/service/task/ManifestFileCleanupTaskHandlerTest.java, runtime/service/src/test/java/org/apache/polaris/service/task/TableCleanupTaskHandlerTest.java
`java.util.Base64` is available since java8 and we are already using it in a few other spots.
in a follow-up we might be able to get rid of our `commons-codec` dependency completely.
=> Prefer java.util.Base64 over commons-codec

runtime/service/build.gradle.kts, runtime/service/src/main/java/org/apache/polaris/service/catalog/io/DefaultFileIOFactory.java, runtime/service/src/main/java/org/apache/polaris/service/context/RealmContextResolver.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandlerAuthzTest.java
since https://github.com/apache/iceberg/commit/9bc6853938533c9c1dfac497229c8f4c30672458 passing a hadoop Configuration to `CatalogUtil.loadCatalog` is optional.
since `hadoop-common` brings in a lot of dependencies (and thus potential vulnerabilities) we should avoid depending on it in our core modules if not strictly required.
note that we were using the transitive `commons-collections` dependency in a spot that we have to adjust.
=> Remove hadoop-common from polaris-runtime-service

polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisEntityType.java, polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisPrivilege.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/dao/entity/BaseResult.java, polaris-core/src/test/java/org/apache/polaris/core/entity/PolarisEntityTypeTest.java, polaris-core/src/test/java/org/apache/polaris/core/entity/PolarisPrivilegeTest.java, polaris-core/src/test/java/org/apache/polaris/core/persistence/dao/entity/ReturnStatusTest.java
In https://github.com/apache/polaris/pull/2486, we add the correct index boundary check for PredefinedPolicyType, this PR fix the similar issue for `PolarisPrivilege`, `ReturnStatus` and `PolarisEntityType`.
=> Core: Prevent AIOOBE for negative codes in PolarisEntityType, PolarisPrivilege, ReturnStatus

gradle/libs.versions.toml, polaris-core/build.gradle.kts, polaris-core/src/main/java/org/apache/polaris/core/DigestUtils.java, polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisPrincipalSecrets.java, polaris-core/src/main/java/org/apache/polaris/core/secrets/UnsafeInMemorySecretsManager.java, runtime/service/src/main/java/org/apache/polaris/service/http/IcebergHttpUtil.java
follow-up to f8ad77a6915defdcfd4bf778f8f6123042ded31e
we can simply use guava instead and eliminate the extra dependency
=> Remove commons-codec dependency

runtime/service/src/test/java/org/apache/polaris/service/catalog/iceberg/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/iceberg/IcebergAllowedLocationTest.java
This test, added in #2473, fails after #2422. This fixes the config override.
=> Fix failing tests in IcebergAllowedLocationTest

polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/PolarisTestMetaStoreManager.java
the deserialization of the property maps is already available in the `PolarisBaseEntity` class
=> Remove PolarisTestMetaStoreManager.jsonNode helper

integration-tests/src/main/java/org/apache/polaris/service/it/env/IcebergHelper.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisApiEndpoints.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisRestApi.java, integration-tests/src/main/java/org/apache/polaris/service/it/env/Server.java, integration-tests/src/main/java/org/apache/polaris/service/it/ext/PolarisIntegrationTestExtension.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, runtime/service/src/intTest/java/org/apache/polaris/service/it/RestCatalogMinIOSpecialIT.java, runtime/service/src/test/java/org/apache/polaris/service/it/ApplicationIntegrationTest.java
`PolarisServerManager` is a plugin point for downstream builds to define runtime env. for tests under `integration-tests`.
This change allows more flexibility for test runtime environments by allowing injecting extra headers into test clients.
=> Allow `PolarisServerManager` implementations to define custom client headers

polaris-core/src/main/java/org/apache/polaris/core/connection/ConnectionConfigInfoDpo.java, polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageConfigurationInfo.java
Use `setDefaultPropertyInclusion` instead of `setSerializationInclusion` as suggested by javadoc.
=> fix deprecated ObjectMapper calls

persistence/relational-jdbc/src/main/resources/h2/schema-v3.sql
Changed `additional_properties` column type from `JSONB` to `TEXT` in `schema-v3.sql`, since `JSONB` is not a valid H2 type.
=> Fix H2 JDBC schema init script

.github/workflows/python-client.yml, client/python/pyproject.toml
```
Package operations: 1 install, 1 update, 0 removals
- Updating virtualenv (20.32.0 -> 20.34.0)
- Installing pyiceberg (0.10.0): Failed
AttributeError
'PythonInfo' object has no attribute 'tcl_lib'
at ~/tmp/3/polaris/polaris-venv/lib/python3.13/site-packages/virtualenv/activation/via_template.py:50 in replacements
46│             "__VIRTUAL_ENV__": str(creator.dest),
47│             "__VIRTUAL_NAME__": creator.env_name,
48│             "__BIN_NAME__": str(creator.bin_dir.relative_to(creator.dest)),
49│             "__PATH_SEP__": os.pathsep,
→  50│             "__TCL_LIBRARY__": creator.interpreter.tcl_lib or "",
51│             "__TK_LIBRARY__": creator.interpreter.tk_lib or "",
52│         }
53│
54│     def _generate(self, replacements, templates, to_folder, creator):
```
Currently …
=> Pin virtualenv version to fix python client installation issue

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/models/ModelEvent.java, persistence/relational-jdbc/src/main/resources/h2/schema-v3.sql, persistence/relational-jdbc/src/main/resources/postgres/schema-v3.sql, polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisEvent.java, runtime/service/src/main/java/org/apache/polaris/service/events/listeners/InMemoryBufferPolarisPersistenceEventListener.java, runtime/service/src/main/java/org/apache/polaris/service/events/listeners/PolarisPersistenceEventListener.java
The request ID is an optional information coming from the REST request. This PR makes it nullable in the database schema.
This PR also annotates the `ModelEvent.principalName` and `PolarisEvent.principalName` fields as nullable in code (the corresponding column was already nullable in the database schema).
=> Make database column events.request_id nullable

README.md
Use the password that matches what the `run` task actually configures.
=> fix password in README.md for `./gradlew run`

README.md
Reverts apache/polaris#2572
As discussed in #2572 the reverted README change was a mistake.
=> Revert "fix password in README.md for `./gradlew run`"

gradle/libs.versions.toml, integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java, polaris-core/build.gradle.kts, runtime/service/build.gradle.kts, tools/minio-testcontainer/build.gradle.kts
Manual intervention required for the bump due to the new changes https://github.com/apache/polaris/pull/2586#issue-3423430216 
1. MINIO / S3FileIO tests fails post due to 
- https://github.com/apache/iceberg/pull/13136 
now we required kms too when creating the client factor otherwise we get server RT failure 
2. The metadata construction assertion requires schema to be set before partition spec
=> Bump: iceberg 1.10

client/python/pyproject.toml
This got added in python3.11 and python3.12:
```
Collecting cryptography>=2.0 (from SecretStorage>=3.2->keyring<26.0.0,>=25.1.0->poetry==2.1.4)
Downloading cryptography-46.0.1-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (5.7 kB)
```
=> Fix license check for cryptography

CHANGELOG.md, README.md, site/content/in-dev/unreleased/metastores.md
=> Add doc notes about EclipseLink removal

site/content/in-dev/unreleased/polaris-api-specs/_index.md, site/content/in-dev/unreleased/polaris-api-specs/polaris-catalog-api.md, site/content/in-dev/unreleased/polaris-api-specs/polaris-management-api.md, site/content/in-dev/unreleased/polaris-spark-client.md
create docs/polaris-api-specs
mv docs/polaris-management-service.md-> docs/polaris-api-specs/polaris-management-api.md 
mv docs/polaris-catalog-service.md -> docs/polaris-api-specs/polaris-catalog-api.md
----
Improve the convenience and usability of project documentation.
Menu items are external links, which is inconvenient when studying documentation - each time you navigate to another menu item, a third-party link opens.
Also, both sections essentially belong to the API work category.
- Management OpenAPI
- Catalog API Spec
An additional "Polaris API Reference" section has been created where the two external API specification links are placed. A visual element has also been added to emphasize that these menu items are external links.
The new variant is much more convenient for …
=> chore(docs): add polaris-api-specs section

api/iceberg-service/src/main/java/org/apache/polaris/service/types/NotificationRequest.java, api/iceberg-service/src/main/java/org/apache/polaris/service/types/TableUpdateNotification.java, api/polaris-catalog-service/src/main/java/org/apache/polaris/service/types/PolicyIdentifier.java, codestyle/errorprone-rules.properties, plugins/spark/v3.5/integration/src/intTest/java/org/apache/polaris/spark/quarkus/it/SparkIntegrationBase.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/rest/CreateGenericTableRequest.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/rest/GenericTable.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/rest/ListGenericTablesResponse.java, plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/rest/LoadGenericTableResponse.java, polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisEntityId.java, polaris-core/src/main/java/org/apache/polaris/core/entity/PolarisGrantRecord.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/cache/EntityCacheByNameKey.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/ResolverEntityName.java, polaris-core/src/main/java/org/apache/polaris/core/policy/PolarisPolicyMappingRecord.java, polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BaseResolverTest.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/main/java/org/apache/polaris/service/auth/external/mapping/DefaultPrincipalMapper.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/CatalogHandlerUtils.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergCatalogHandler.java, runtime/service/src/main/java/org/apache/polaris/service/catalog/iceberg/IcebergRESTExternalCatalogFactory.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisServiceImplTest.java, runtime/service/src/test/java/org/apache/polaris/service/auth/DefaultOAuth2ApiServiceTest.java
I was going through all of the open TODOs in the codebase and found some that were on ErrorProne that were easy to enable.
Personally, I think that EqualsGetClass and PatternMatchingInstanceof are reasonable, but I'm on the fence on whether to enable UnusedMethod.
=> chore(errorprone): Enabling EqualsGetClass, PatternMatchingInstanceof, and UnusedMethod in ErrorProne

CHANGELOG.md
Clear out the unreleased version of the CHANGELOG and move the parts release in 1.1 to its dedicated section 
1.1 release logs are taken from here - https://github.com/apache/polaris/commit/9c635e14fb7497cd4d40b79075048af49350d622
Need to put bug fixes which will be part of 1.2 in the unreleased section
=> CHANGELOG: Freeze change log for 1.1 and clear out unreleased version for 1.2

CHANGELOG.md, polaris-core/src/main/java/org/apache/polaris/core/storage/StorageAccessProperty.java, polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegration.java, polaris-core/src/test/java/org/apache/polaris/core/storage/azure/AzureCredentialsStorageIntegrationTest.java
For the credential refresh endpoint for the ADLS its expected the expiration time should be sent with the prefix of `AZURE_SAS_TOKEN_EXPIRES_AT_MS_PREFIX` which presently Polaris doesn't sends as the course of that the CredentialProvider responsible for the refresh fails the assertion here https://github.com/apache/iceberg/blob/main/azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAdlsCredentialProvider.java#L123
and hence not making it usable.
P.S I think we should also use constants for iceberg SDK in the StorageAccessProperty, but this is an orthogonal discussion for now. 
Add a small UT
=> Azure: Fix azure expires at prefix for the credentials refresh

plugins/spark/v3.5/spark/src/main/java/org/apache/polaris/spark/SparkCatalog.java
=> Remove unused LOG in SparkCatalog

client/python/pyproject.toml
There has been a long-standing request for pip-licenses to support [PEP 639 – Improving License Clarity with Better Package Metadata](https://discuss.python.org/t/pep-639-round-3-improving-license-clarity-with-better-package-metadata/53020/127). However, pip-licenses has shown limited progress or support for this enhancement (see [PR #213](https://github.com/raimon49/pip-licenses/pull/213)).
To address this gap, we are switching to [pip-licenses-cli](https://pypi.org/project/pip-licenses-cli/), which provides PEP 639–compliant license metadata handling and is being actively maintained in this area.
=> Fix client license check

tools/minio-testcontainer/src/main/java/org/apache/polaris/test/minio/Minio.java, tools/minio-testcontainer/src/main/java/org/apache/polaris/test/minio/MinioAccess.java, tools/minio-testcontainer/src/main/java/org/apache/polaris/test/minio/MinioContainer.java, tools/minio-testcontainer/src/main/java/org/apache/polaris/test/minio/MinioExtension.java
... to remove the need to derive it via the AWS-SDK default mechanism requiring a system property or environment variable.
=> Minio testcontainer: allow setting a specific region

polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java, runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAdminServiceTest.java, runtime/service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java
In https://github.com/apache/polaris/pull/2223#discussion_r2377271201, one follow-up we identify is to make JIT entities creation configurable per catalog instead of per realm. This PR leverage the feature configuration catalog level override to do this. The corresponding catalog property will be
```
polaris.config.enable-sub-catalog-rbac-for-federated-catalogs
```
=> Make ENABLE_SUB_CATALOG_RBAC_FOR_FEDERATED_CATALOGS configurable per catalog

.github/workflows/gradle.yml, .github/workflows/helm.yml, .github/workflows/nightly.yml, .github/workflows/python-client.yml, .github/workflows/regtest.yml, .github/workflows/spark_client_regtests.yml, README.md, settings.gradle.kts
This PR enables Develocity build scans for all PRs and contributors w/o an Apache account.
CI build scans in the `apache/polaris` repo against branches and tags and having access to the ASF's Develocity secret continue to publish to the ASF's Develocity instance (no behavioral change).
All other build scans are published to Gradle's public Develocity instance:
- Build scans from local developer (non-CI) runs are only published, if Gradle is invoked with the `--scan` option.
- Build scans from or targeting another repository than `apache/polaris` do need be enabled explicity by accepting Gradle's terms of service, via a repository variable, because this is a decision of the owner of a repository.
Advanced options to configure another Develocity server or project-ID are available (for …
=> Publish Develocity builds scans for PRs and local use

runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisCatalogsEventServiceDelegator.java, runtime/service/src/main/java/org/apache/polaris/service/events/CatalogGenericTableServiceEvents.java, runtime/service/src/main/java/org/apache/polaris/service/events/CatalogPolicyServiceEvents.java, runtime/service/src/main/java/org/apache/polaris/service/events/CatalogsServiceEvents.java, runtime/service/src/main/java/org/apache/polaris/service/events/IcebergRestCatalogEvents.java, runtime/service/src/main/java/org/apache/polaris/service/events/jsonEventListener/PropertyMapEventListener.java, runtime/service/src/main/java/org/apache/polaris/service/events/listeners/NoOpPolarisEventListener.java, runtime/service/src/main/java/org/apache/polaris/service/events/listeners/PolarisEventListener.java, runtime/service/src/main/java/org/apache/polaris/service/events/listeners/PolarisPersistenceEventListener.java, runtime/service/src/main/java/org/apache/polaris/service/events/listeners/TestPolarisEventListener.java, runtime/service/src/test/java/org/apache/polaris/service/events/listeners/PolarisEventListenerTest.java, runtime/service/src/test/java/org/apache/polaris/service/events/listeners/TestPolarisEventListenerTest.java
Summary of changes:
- Turned `PolarisEventListener` into an interface to facilitate implementation / mocking
- Added missing `implements PolarisEvent` to many event records
- Removed unused method overrides
- Added missing method overrides to `TestPolarisEventListener`
=> Fix & enhancements to the Events API hierarchy

runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java
`findCatalogByName` in `PolarisAdminService` does not actually require a name, it will fetch the catalog resolved in the resolutionManifest
This PR remove the unused arg and change the name to avoid confusion
=> Remove unused `name` arg from findCatalogByName in PolarisAdminService

runtime/service/src/main/java/org/apache/polaris/service/events/listeners/TestPolarisEventListener.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/iceberg/AbstractIcebergCatalogTest.java, runtime/service/src/test/java/org/apache/polaris/service/catalog/iceberg/AbstractIcebergCatalogViewTest.java
Only the last events are needed, so it's enough to keep only the last events by type. Also adds a `.clear()` function to clear the captured events for a deterministic (empty) state for each test case.
Also uses a thread-safe collection now.
=> TestEventsListener - reduce memory pressure

.github/workflows/gradle.yml
=> CI: Split-jobs - fix store-cache dependencies

runtime/service/src/main/java/org/apache/polaris/service/exception/IcebergExceptionMapper.java, spec/iceberg-rest-catalog-open-api.yaml
Seems like we have just been bumping the iceberg spec versions but not syncing the rest-api.yaml (it was last synced in 1.8.1) and it doesn't reflect the current state of v3 : 
1. check row-lineage (the spec has changed a lot now the req and response have different field) 
2. check encryption (this is entirely missing) 
I think we need the up to date spec to make sure the request / response model are upto date incase there is a client which is already v3 compliant. 
Adding this in the pr as the first starting step and will see how to move forward from there. I am new to this segment of code so unsure if Polaris generates its own model or reuse the model from iceberg library.
=> IRC SPEC v3 support: Change the IRC spec to use 1.10 yaml to support upto date request / response models 

tools/version/build.gradle.kts
Glob patterns were not resolved by Windows shell that expects a filename, used fileTree instead
Fixes #2525
=> Fix: Build task syncNoticeAndLicense fails on Windows

build-logic/src/main/kotlin/polaris-java.gradle.kts, build-logic/src/main/kotlin/polaris-runtime.gradle.kts, plugins/spark/v3.5/integration/build.gradle.kts, runtime/admin/build.gradle.kts, runtime/service/build.gradle.kts, runtime/spark-tests/build.gradle.kts
This changes introduces a build-scoped limit on concurrently running `test` tasks and other test task like `intTest`. The defaults are:
* "num-available-processory / 4" for `Test` tasks except `test`, optionally configurable via the system property `polaris.intTestParallelism`
* "num-available-processory / 2" for `Test` tasks named `test`, optionally configurable via the system property `polaris.testParallelism`
This change also moves the common fork and heap related settings for Quarkus tests to the `polaris-runtime` build plugin.
Overall, this change helps constraining the CPU/heap pressure to any developer system.
=> Testing: add test-parallelism-constraint and unify testing constaints

integration-tests/src/main/java/org/apache/polaris/service/it/env/ManagementApi.java, integration-tests/src/main/java/org/apache/polaris/service/it/test/CatalogFederationIntegrationTest.java, polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/AtomicOperationMetaStoreManager.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/transactional/TransactionalMetaStoreManagerImpl.java, runtime/spark-tests/src/intTest/java/org/apache/polaris/service/spark/it/CatalogFederationIT.java
When enabling table/namespace level RBAC in federated catalog, JIT entities will be created during privilege grant. In the short term, we should ignore them when dropping the catalog. In the long term, we will clean-up those entities when deleting the catalog.
This will be the first step towards JIT entity clean-up:
1. Ignore JIT entities when dropping federated catalog (orphan entities)
2. Register tasks/in-place cleanup JIT entities during catalog drop
3. Add new functionality to PolarisMetastoreManager to support atomic delete non-used JIT entities during revoke.
4. Global Garbage Collector to clean-up unreachable entities (entities with non-existing catalog path/parent)
=> [Catalog Federation] Ignore JIT entities when deleting federated catalogs, add integration test for namespace/table-level RBAC

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/DatabaseType.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/DatasourceOperations.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcBasePersistenceImpl.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcBootstrapUtils.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcMetaStoreManagerFactory.java, persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/QueryGenerator.java, persistence/relational-jdbc/src/main/resources/h2/schema-v3.sql, persistence/relational-jdbc/src/test/java/org/apache/polaris/persistence/relational/jdbc/JdbcBootstrapUtilsTest.java, polaris-core/src/main/java/org/apache/polaris/core/persistence/bootstrap/SchemaOptions.java, runtime/admin/src/main/java/org/apache/polaris/admintool/BootstrapCommand.java, runtime/admin/src/test/java/org/apache/polaris/admintool/BootstrapCommandTestBase.java, runtime/admin/src/test/java/org/apache/polaris/admintool/relational/jdbc/RelationalJdbcBootstrapCommandTest.java
1. Fix bootstrapping with schema option, presently its considered mutually exclusive so if give -v option with -r its fails saying they are exlusive, on not giving -r it say no relams configured 
2. schemaFile checks for empty string as not specifying the option means bootstrap can't use with -v either 
3. Adds a check that if the schema table exists then we can't downgrade as the schema is the global value and specially since realm is the part of schema such thing is not possible 
while testing i found each QuarkusMainlauncher is launching new PG container, thinking of fix still to reuse it to test already bootstrapped schema.
Note: I don't think its a 1.2 blocker since we can't use this, but would love to know other community member takes.
=> JDBC: Fix Bootstrap with schema options
