README.md

Updating blog description in the README.md file to point to today's launch announcement

Update blog links in README

---

README.md

* Hardware:
* Toolchain:
* SDK:
- [x ] I have made corresponding changes to the documentation
- [x ] I have signed and submitted the [ICLA](https://github.com/polaris-catalog/polaris/blob/main/ICLA.md) and if needed, the [CCLA](https://github.com/polaris-catalog/polaris/blob/main/CCLA.md). See …

Doc fix: remove extra = during token generation

---

README.md

The existing example doesn't work as far as I tried locally. 
* Hardware:
* Toolchain:
* SDK:

Fix example when creating a new catalog in README

---

polaris-core/src/main/java/io/polaris/core/context/CallContext.java
polaris-core/src/main/java/io/polaris/core/persistence/LocalPolarisMetaStoreManagerFactory.java
polaris-core/src/main/java/io/polaris/core/resource/TimedApi.java
polaris-core/src/main/java/io/polaris/core/storage/InMemoryStorageIntegration.java
polaris-core/src/main/java/io/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java
polaris-core/src/main/java/io/polaris/core/storage/aws/PolarisS3FileIOClientFactory.java
polaris-core/src/main/java/io/polaris/core/storage/azure/AzureCredentialsStorageIntegration.java
polaris-core/src/main/java/io/polaris/core/storage/azure/AzureLocation.java
polaris-core/src/main/java/io/polaris/core/storage/cache/StorageCredentialCacheEntry.java
polaris-service/src/main/java/io/polaris/service/auth/DiscoverableAuthenticator.java
polaris-service/src/main/java/io/polaris/service/auth/OAuthTokenErrorResponse.java
polaris-service/src/main/java/io/polaris/service/auth/OAuthUtils.java
polaris-service/src/main/java/io/polaris/service/auth/TokenRequestValidator.java
polaris-service/src/main/java/io/polaris/service/catalog/BasePolarisCatalog.java
polaris-service/src/main/java/io/polaris/service/catalog/PolarisCatalogHandlerWrapper.java
polaris-service/src/main/java/io/polaris/service/catalog/SupportsCredentialDelegation.java
polaris-service/src/main/java/io/polaris/service/task/TaskExecutorImpl.java
polaris-service/src/main/java/io/polaris/service/task/TaskUtils.java
polaris-service/src/main/java/io/polaris/service/types/TokenType.java

Some javadoc fixes (broken links, empty tags, etc.) Ideally, we should have some checkstyle rules and/or a strict formatter for javadocs.

Javadoc fixes

---

polaris-service/src/test/java/io/polaris/service/auth/JWTRSAKeyPairTest.java
polaris-service/src/test/java/io/polaris/service/auth/JWTSymmetricKeyGeneratorTest.java
polaris-service/src/test/java/io/polaris/service/auth/TokenRequestValidatorTest.java
polaris-service/src/test/java/io/polaris/service/catalog/PolarisSparkIntegrationTest.java
polaris-service/src/test/java/io/polaris/service/entity/CatalogEntityTest.java

Migrate all JUnit assertions to AssertJ in `polaris-service` module
* Hardware:
* Toolchain:
* SDK:

Migrate all JUnit assertions to AssertJ in `polaris-service` module

---

polaris-core/src/test/java/io/polaris/core/persistence/EntityCacheTest.java
polaris-core/src/test/java/io/polaris/core/storage/cache/StorageCredentialCacheTest.java
polaris-core/src/testFixtures/java/io/polaris/core/persistence/PolarisTestMetaStoreManager.java

Migrate all JUnit assertions to AssertJ in `polaris-core` module
* Hardware:
* Toolchain:
* SDK:

Migrate all JUnit assertions to AssertJ in `polaris-core` module

---

polaris-service/src/main/java/io/polaris/service/catalog/BasePolarisCatalog.java

Few cleanup at BasePolarisCatalog. 
- Fix few log messages 
- Remove extra null checks
- Minor spell check 
Most of the build warnings are being covered with fix https://github.com/polaris-catalog/polaris/pull/75

Code Cleanup of BasePolarisCatalog

---

build.gradle
gradle/libs.versions.toml
polaris-core/src/main/java/io/polaris/core/storage/cache/StorageCredentialCache.java
polaris-core/src/test/java/io/polaris/core/storage/cache/StorageCredentialCacheTest.java
polaris-service/src/main/java/io/polaris/service/admin/PolarisAdminService.java
polaris-service/src/main/java/io/polaris/service/catalog/BasePolarisCatalog.java
polaris-service/src/main/java/io/polaris/service/catalog/IcebergCatalogAdapter.java
polaris-service/src/main/java/io/polaris/service/types/NotificationType.java

Fixes #40
* Hardware:
* Toolchain:
* SDK:

Add ErrorProne Plugin for Gradle

---

polaris-service/src/test/java/io/polaris/service/catalog/PolarisSparkIntegrationTest.java

This provides code highlight on IntelliJ IDEA.
* Hardware:
* Toolchain:
* SDK:

Extract a helper method with `@Language` annotation

---

polaris-core/src/test/java/io/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java
polaris-core/src/test/java/io/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java
polaris-service/src/main/java/io/polaris/service/context/SqlliteCallContextCatalogFactory.java
polaris-service/src/test/java/io/polaris/service/PolarisApplicationIntegrationTest.java
polaris-service/src/test/java/io/polaris/service/test/PolarisConnectionExtension.java

Avoid string concat for logger
* Hardware:
* Toolchain:
* SDK:

Avoid string concat for logger

---

extension/persistence/eclipselink/src/main/java/io/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreSessionImpl.java

The placeholder is redundant because the argument is `debug(String msg, Throwable t)`
* Hardware:
* Toolchain:
* SDK:

Fix incorrect logger arguments

---

build-logic/src/main/kotlin/polaris-java.gradle.kts
polaris-core/src/test/java/io/polaris/service/storage/gcp/GcpCredentialsStorageIntegrationTest.java
polaris-service/src/main/java/io/polaris/service/auth/DefaultOAuth2ApiService.java
polaris-service/src/main/java/io/polaris/service/auth/PemUtils.java
polaris-service/src/test/java/io/polaris/service/auth/JWTRSAKeyPairTest.java
polaris-service/src/test/java/io/polaris/service/catalog/BasePolarisCatalogTest.java
polaris-service/src/test/java/io/polaris/service/task/ManifestFileCleanupTaskHandlerTest.java

Enable ErrorProne [DefaultCharset](https://errorprone.info/bugpattern/DefaultCharset)
* Hardware:
* Toolchain:
* SDK:

Enable ErrorProne DefaultCharset

---

README.md

Add Development section in `README.md`

Add Development section in README.md

---

gradle/wrapper/gradle-wrapper.properties

Upgrade to Gradle 8.10.
Full build

Upgrade to Gradle 8.10

---

.github/workflows/check-md-link-config.json
.github/workflows/check-md-link.yml
docs/quickstart.md

Add GitHub Action that will check that links in Markdown files are working.  This runs on any .md files in the `/docs` & `/regtests/client/python/docs` dirs, and will only be triggered when there are changes to files in those dirs
For notes on why the mvnrepository URL is in "ignore" list JSON, see conversation in this PR: https://github.com/polaris-catalog/polaris/pull/141#pullrequestreview-2234083843
Fixes #139
I tested this on my forked repo: https://github.com/bbrewington/fork-polaris
Test setup
Added these lines of markdown with 3 broken links to the files `docs/access-control.md`, `regtests/client/python/docs/AddGrantRequest.md`, `top_level_file.md`
```markdown
Broken web link: [URL Throwing 404](https://google.com/123456)
Broken relative …
```

Use Github Action to check Markdown links in /docs & /regtests/client/python/docs

---

.asf.yml

Based on #174, with the PR comments applied.

Add initial `.asf.yaml`

---

README.md

Fix name and trademark as per ASF policy
Fixes # N/A
N/A
N/A

Update README.md to use Apache Polaris TM

---

.asf.yml

Add first Polaris collaborators.

Add first Polaris collaborators

---

extension/persistence/eclipselink/src/test/java/org/apache/polaris/extension/persistence/impl/eclipselink/PolarisEclipseLinkMetaStoreManagerTest.java
polaris-core/src/test/java/org/apache/polaris/core/persistence/PolarisTreeMapMetaStoreManagerTest.java
polaris-core/src/testFixtures/java/org/apache/polaris/core/persistence/BasePolarisMetaStoreManagerTest.java

Rename test classes of metastore manager + fix typo
* Hardware:
* Toolchain:
* SDK:

Rename test classes of metastore manager + fix typo

---

build-logic/src/main/kotlin/polaris-java.gradle.kts
polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java

Enable ErrorProne FallThrough, MissingCasesInEnumSwitch, OrphanedFormatString
* Hardware:
* Toolchain:
* SDK:

Enable ErrorProne FallThrough, MissingCasesInEnumSwitch, OrphanedFormatString

---

build-logic/src/main/kotlin/polaris-java.gradle.kts
polaris-service/src/main/java/org/apache/polaris/service/catalog/PolarisCatalogHandlerWrapper.java

Update created-at property in createTableDirectWithWriteDelegation + enable ErrorProne ModifiedButNotUsed
* Hardware:
* Toolchain:
* SDK:

Update created-at property in createTableDirectWithWriteDelegation + enable ErrorProne ModifiedButNotUsed

---

polaris-core/src/main/java/org/apache/polaris/core/persistence/PolarisMetaStoreManager.java
polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageIntegration.java
polaris-service/src/test/java/org/apache/polaris/service/PolarisApplicationIntegrationTest.java

Replace snowflake keyword with Polaris

Remove keyword "snowflake" from polaris-service/core.

---

polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisOverlappingCatalogTest.java

Nested loop doesn't provide helpful failure messages unless we set the description in each assertion.

Replace nested loop with `@ParameterizedTest`

---

gradle/libs.versions.toml

This Dropwizard version includes a lot of dependency updates bringing fixes and security enhancements. You can take a look on the Release Notes for details: https://github.com/dropwizard/dropwizard/releases/tag/v4.0.8

Upgrade to Dropwizard 4.0.8

---

polaris-service/src/test/java/org/apache/polaris/service/auth/TokenUtils.java

Remove unused method

---

.github/CODEOWNERS

Add Yufei Gu to CODEOWNERS file so he can merge PRs.

Add new committer Yufei Gu to CODEOWNERS

---

polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java
polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisSparkIntegrationTest.java

`CREATE VIEW <>` is failing with spark. 
add support of catalog properties for view. 
- [*] Bug fix (non-breaking change which fixes an issue)
Tested with unit tests.

Fix create view operation

---

build.gradle.kts

Build failed due to rat check on files in regtests/output
Build passed after the change.

Fix the rat check failure

---

.github/CODEOWNERS

@jbonofre - I think we are ready to do this? Are we waiting on anything else?

Update CODEOWNERS with New Committers

---

polaris-service/src/main/java/org/apache/polaris/service/throttling/RequestThrottlingErrorResponse.java
polaris-service/src/main/java/org/apache/polaris/service/throttling/StreamReadConstraintsExceptionMapper.java
polaris-service/src/test/java/org/apache/polaris/service/PolarisApplicationIntegrationTest.java

Using record to simplify class RequestThrottlingErrorResponse

---

helm/polaris/Chart.yaml
helm/polaris/README.md
helm/polaris/README.md.gotmpl

The home URL within helm is outdated. Updated to reflect the apache one. Also, rerun helm-docs to reflect the added/removed config parameters.
- [] I have performed a self-review of my code

Fix home url within helm and update README.md

---

polaris-service/build.gradle.kts

There is a duplicated line in `build.gradle.tks` in polaris-service.
* Hardware:
* Toolchain:
* SDK:

Remove duplicated line in polaris-service build.gradle

---

site/content/in-dev/unreleased/_index.md

Site: fix links

---

README.md

Add dev mailing list and remove a duplicated Zulip link

---

gradle/libs.versions.toml

Upgrade to latest version of AWS SDK
dependency maintenance
CI build

Upgrade AWS SDK to version 2.28.15

---

polaris-core/src/main/java/org/apache/polaris/core/storage/FileStorageConfigurationInfo.java
polaris-core/src/main/java/org/apache/polaris/core/storage/InMemoryStorageIntegration.java
polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisStorageConfigurationInfo.java
polaris-core/src/main/java/org/apache/polaris/core/storage/StorageLocation.java
polaris-core/src/main/java/org/apache/polaris/core/storage/azure/AzureLocation.java
polaris-core/src/test/java/org/apache/polaris/core/storage/StorageUtilTest.java
polaris-core/src/test/java/org/apache/polaris/service/storage/aws/AwsCredentialsStorageIntegrationTest.java
polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureCredentialStorageIntegrationTest.java
polaris-core/src/test/java/org/apache/polaris/service/storage/azure/AzureLocationTest.java
polaris-service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java
polaris-service/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java
polaris-service/src/test/java/org/apache/polaris/service/entity/CatalogEntityTest.java

This adds support for the legacy [WASB driver](https://hadoop.apache.org/docs/current/hadoop-azure/index.html) on Azure.
Modified several existing tests

WASB Support

---

README.md

Simple update to the README to avoid confusion.  I made the mistake of sending to dev@polaris.apache.org to subscribe but never heard back 🤦

Update readme to clarify how to subscribe to the devlist

---

regtests/run.sh
regtests/run_spark_sql.sh

Spark 3.5.3 has been released. They may delete the 3.5.2 soon. Update the version to avoid failures.
Local test works well

Update Spark version to 3.5.3

---

.asf.yaml

Must use `Helm tests` instead of the job's "ID".

asf.yaml: Fix required check introduced by #352

---

gradle/libs.versions.toml

maintainenance upgrade to Micrometer 1.13.6
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.13.6
Github Actions CI

Upgrade to micrometer version 1.13.6

---

build-logic/src/main/kotlin/polaris-java.gradle.kts
polaris-service/src/test/java/org/apache/polaris/service/catalog/PolarisPassthroughResolutionView.java

Enable errorprone PatternMatchingInstanceof
N/A

Enable errorprone PatternMatchingInstanceof

---

.asf.yaml

Some users/contributors asked to enable GitHub wiki and projects.

Enable GitHub wiki and projects

---

polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisAuthorizer.java
polaris-core/src/main/java/org/apache/polaris/core/auth/PolarisAuthorizerImpl.java
polaris-service/src/main/java/org/apache/polaris/service/PolarisApplication.java
polaris-service/src/test/java/org/apache/polaris/service/admin/PolarisAuthzTestBase.java
polaris-service/src/test/java/org/apache/polaris/service/catalog/BasePolarisCatalogTest.java
polaris-service/src/test/java/org/apache/polaris/service/catalog/BasePolarisCatalogViewTest.java

No functional change. Just a refactoring to improve encapsulation.
Manual smoke test (plus normal CI).

Extract interface for PolarisAuthorizer

---

regtests/setup.sh
regtests/t_pyspark/src/iceberg_spark.py

We have upgraded to Iceberg 1.6.1 in the dependency. We should update it in integration tests as well.
Local test passed

Update Iceberg version to 1.6.1 in tests

---

NOTICE

Updating NOTICE file with:
- SGA
- include NOTICE file from ALv2 used code

Fix NOTICE file content

---

build-logic/src/main/kotlin/publishing/MemoizedGitInfo.kt
build-logic/src/main/kotlin/publishing/PublishingHelperExtension.kt
build-logic/src/main/kotlin/publishing/rootProject.kt
build-logic/src/main/kotlin/publishing/util.kt

Also fix two related Gradle deprecations

Source tarball - include file name in digest file

---

service/common/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java

Do not accept provided technical IDs

---

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/PolarisApplicationConfigurationTest.java
dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/PolarisApplicationIntegrationTest.java
dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/TimedApplicationEventListenerTest.java

Move test classes to appropriate package

---

polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java

Remove redundant local variable

---

polaris-core/src/main/java/org/apache/polaris/core/entity/CatalogEntity.java

Rename local variable to follow the Camel style

---

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/task/ManifestFileCleanupTaskHandlerTest.java

This test wrongly assumes that the ForkJoin Pool thread that will execute the async task will be a new one, and that it will inherit the thread locals from its parent, including CallContext. But that is not guaranteed.

Fix ManifestFileCleanupTaskHandlerTest.testCleanupWithRetries

---

.asf.yaml

Currently all three GH PR merge options ("create merge commit", "squash and merge" and "rebase and merge") are enabled. The intention was to only use "squash and merge".

GitHub - only allow "squash and merge" for PRs

---

gradle/libs.versions.toml

Upgrade eclipselink version to 4.0.5 to resolve potential [OptimisticLockException](https://github.com/eclipse-ee4j/eclipselink/pull/2251)

Upgrade eclipselink version to 4.0.5

---

.github/CODEOWNERS
site/content/community/_index.adoc

Also updates `CODEOWNERS` adding @dimas-b and @dennishuo

Add Dmitri + Dennis as new committers

---

dropwizard/service/src/test/java/org/apache/polaris/service/dropwizard/PolarisApplicationIntegrationTest.java

Use an explicit fake and expired token as input to the Iceberg's `AuthSession` to force it to obtain a real token from Polaris at session creation time.
This is a follow-up to #629. Before that PR, the test depended heavily on Iceberg's `AuthSession` code. It still depends on that, but to a lesser extent. Now, the input token is already expired, so the test only needs to validate that a new token was obtained.

Fix testRefreshToken()

---

.gitignore
build.gradle.kts

The `.kotlin/` directory is a temporary directory used internally by Kotlin compilations. The contents of that directory don't matter.

git- and rat-ignore - add `build-logic/.kotlin/`

---

regtests/run.sh

The script contains 2 syntax errors on lines 25 and 94.

Fix regression test run.sh script

---

build-logic/src/main/kotlin/publishing/PublishingHelperPlugin.kt

Publish the sources and javadoc for test-fixtures in addition to the already published jar.

Publish test-fixtures sources + javadoc as well

---

quarkus/service/src/main/java/org/apache/polaris/service/quarkus/config/QuarkusProducers.java

Use Clock.systemUTC()

---

extension/persistence/eclipselink/build.gradle.kts
gradle/libs.versions.toml
quarkus/service/build.gradle.kts

Nit: Remove unneeded bundle

---

gradle/libs.versions.toml
tools/immutables/build.gradle.kts
tools/immutables/src/main/java/org/apache/polaris/immutables/PolarisImmutable.java
tools/immutables/src/main/resources/META-INF/annotations/org.immutables.value.immutable
tools/immutables/src/main/resources/META-INF/extensions/org.immutables.inhibit-classpath

This PR introduces the Immutables library:
https://immutables.github.io/
This library is widely used in Iceberg and many other projects. The ability to define immutable components in an easy way, without struggling with the nitty-gritty details (getters, builders, equals, hashCode, toString, etc.) is a nice productivity boost and improves code correctness by enforcing immutability by default. Unlike Java records, collections in immutable values are immutable as well. Immutable value also have extensive support for builders, which removes a lot of manual duplicated boilerplate code.
This PR only adds the library, it is effectively a re-incarnation of #282.

Add immutables library

---

gradle/libs.versions.toml
quarkus/service/build.gradle.kts

Build: move version-decls from polaris-quarkus-service to libs.versions.toml

---

site/content/_index.adoc

This PR updates the list of supported query engines.

[WebSite] Update query engines list

---

gradle/libs.versions.toml

Nit: remove superfluous dependency declarations

---

build-logic/src/main/kotlin/polaris-quarkus.gradle.kts
quarkus/admin/build.gradle.kts
quarkus/server/build.gradle.kts
quarkus/service/build.gradle.kts

Build/nit: Also move the `dependsOn` to `polaris-quarkus`

---

.github/workflows/gradle.yml

Publish intTest results

---

quarkus/admin/src/main/java/org/apache/polaris/admintool/PolarisAdminTool.java
tools/version/build.gradle.kts
tools/version/src/main/java/org/apache/polaris/version/PolarisVersionProvider.java

Move `PolarisVersionProvider` to `:polaris-version` to make it reusable

---

.github/workflows/gradle.yml

Adds additional steps to verify that the build works against Java 23 and runs some selected tests.

CI: Add rudimentary testing against Java 23

---

regtests/client/python/pyproject.toml

Fix pyproject.toml project and license

---

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisApplicationIntegrationTest.java
quarkus/service/src/test/java/org/apache/polaris/service/quarkus/it/QuarkusApplicationIntegrationTest.java

`testRefreshToken()` is not normative for all Polaris Servers given that external IdPs are going to be supported. Therefore, the test is moved from the "blackbox" tests module to a `quarkus/services` tests, which are local to the Apache Polaris build.

Move `testRefreshToken()` to `QuarkusApplicationIntegrationTest`

---

site/content/in-dev/unreleased/quickstart.md

docs: adapt quickstart.md to Quarkus

---

site/content/in-dev/unreleased/configuration.md

docs: introduce configuration reference page

---

site/content/in-dev/unreleased/configuring-polaris-for-production.md

docs: adapt configuring-polaris-for-production.md to Quarkus

---

site/content/in-dev/unreleased/quickstart.md

This is for https://github.com/apache/polaris/pull/396

Fix doc (#396)

---

regtests/README.md

Note: this assumes #610 is merged as is.

docs: adapt regtests README.md to Quarkus

---

polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java

Fix typo in AwsCredentialsStorageIntegration.java

Fix typo in AwsCredentialsStorageIntegration.java

---

helm/polaris/Chart.yaml

This PR updates the following fields:
- description: added "Apache"
- appVersion: updated to 1.0.0-incubating-SNAPSHOT
- icon: fixed link
- maintainers: added missing committers, sorted alphabetically

Helm chart: update Chart.yaml

---

site/hugo.yaml
site/layouts/shortcodes/redoc-polaris.html

Implements swagger redirection

Site: Navigate the site to swagger redirection

---

service/common/src/test/java/org/apache/polaris/service/catalog/io/FileIOFactoryTest.java
service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java
site/content/in-dev/unreleased/configuring-polaris-for-production.md

nit: rename a few remaining occurrences of "RealmId"

---

service/common/src/main/java/org/apache/polaris/service/catalog/DefaultIcebergCatalogPrefixParser.java
service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogAdapter.java
service/common/src/main/java/org/apache/polaris/service/catalog/IcebergCatalogPrefixParser.java
service/common/src/testFixtures/java/org/apache/polaris/service/TestServices.java

This is an extension point to allow customizing the relationship between realm / catalog and Iceberg REST API prefix.

Add IcebergCatalogPrefixParser

---

.github/renovate.json5

boto3 releases multiple times per week, changing to weekly (similar to awssdk).

Renovate: boto3 weekly schedule

---

site/content/in-dev/unreleased/quickstart.md

Fix quickstart.md add using Docker on UnionTech OS Desktop 20 Pro

Fix:quickstart.md add using Docker on UnionTech OS Desktop 20 Pro

---

regtests/run.sh

This fixed issue reported in https://github.com/apache/polaris/issues/1014. Here is a sample failed log: https://github.com/apache/polaris/actions/runs/13363993954/job/37318262139?pr=1010

Fix broken CI

---

getting-started/spark/notebooks/Dockerfile
integration-tests/src/main/java/org/apache/polaris/service/it/env/PolarisApiEndpoints.java
regtests/run.sh
regtests/run_spark_sql.sh

[1] Bumps spark version to 3.5.4 for consistency throughout. 
[2] Fix a typo in iceberg spelling :)

Update Spark version in Examples

---

site/content/community/meetings/_index.adoc

Add the Polaris Community Meeting record for Feb. 20, 2025.

Add Feb. 20, 2025 community meeting

---

site/content/community/_index.adoc
site/content/community/proposals.adoc

As discussed yesterday during the community meeting, this PR gives visibility to proposals and roadmap.

Publish proposals and roadmap on the website

---

quarkus/server/build.gradle.kts

Two minor improvements:
- Enable colors in the logs
- Disable writing log files (console logging is enough)

nit: improve UX when running Polaris with Gradle

---

build-logic/src/main/kotlin/polaris-java.gradle.kts

build-logic: exclude generated code from errorprone

---

site/content/in-dev/unreleased/command-line-interface.md
site/content/in-dev/unreleased/entities.md

I encountered issues when testing with MinIO, so I switched to using the "file" option for local testing. I noticed that the documentation lacks examples for the "file" option. Now, I'm providing a sample for using the "file" option to help others get started quickly.

Add an example to the command-line-interface.md file.

---

tools/container-spec-helper/build.gradle.kts

Add jandex to `:polaris-container-spec-helper`

---

spec/README.md

Make it consistent with the recent changes.

Update the spec/readme.md

---

quarkus/service/src/test/java/org/apache/polaris/service/quarkus/catalog/BasePolarisCatalogTest.java
service/common/src/main/java/org/apache/polaris/service/catalog/BasePolarisCatalog.java

Main is broken due to two merges happened two fast and there is a conflict that github haven't detect it yet.

Resolve conflicts between two merges.

---

polaris-core/src/main/java/org/apache/polaris/core/persistence/BasePersistence.java

Reading the code for BasePersistence found this highlighted by my IDE

Remove unused param from java doc

---

site/content/community/meetings/_index.adoc

This PR adds 2025-03-06 community meeting record/notes.

Add Apache Polaris Community Meeting 2025-03-06 record/notes

---

site/content/downloads.md

This PR fixes the bullet points indent and cleanup the downloads page.

Cleanup downloads page

---

polaris-core/src/main/java/org/apache/polaris/core/storage/PolarisCredentialProperty.java
polaris-core/src/main/java/org/apache/polaris/core/storage/aws/AwsCredentialsStorageIntegration.java
polaris-core/src/main/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheEntry.java
polaris-core/src/test/java/org/apache/polaris/core/storage/cache/StorageCredentialCacheTest.java
polaris-core/src/test/java/org/apache/polaris/service/storage/aws/AwsCredentialsStorageIntegrationTest.java

This PR adds an additional property when credential vendor is AWS. This Property is necessary in Iceberg [here](https://github.com/apache/iceberg/blob/main/aws/src/main/java/org/apache/iceberg/aws/s3/VendedCredentialsProvider.java#L120).

add AWS_SESSION_TOKEN_EXPIRES_AT_MS

---

site/content/in-dev/0.9.0/_index.md
site/content/in-dev/0.9.0/access-control.md
site/content/in-dev/0.9.0/command-line-interface.md
site/content/in-dev/0.9.0/configuring-polaris-for-production.md
site/content/in-dev/0.9.0/entities.md
site/content/in-dev/0.9.0/metastores.md
site/content/in-dev/0.9.0/overview.md
site/content/in-dev/0.9.0/polaris-management-service.md
site/content/in-dev/0.9.0/quickstart.md
site/content/in-dev/0.9.0/rest-catalog-open-api.md
site/hugo.yaml

Waiting the automatic publication, I'm manually updating website with 0.9.0 documentation.

Publish 0.9.0 documentation

---

regtests/Dockerfile

Remove the extra `RUN` in Dockerfile

Remove extra run in dockerfile

---

polaris

Address [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164), [SC2098](https://github.com/koalaman/shellcheck/wiki/SC2098), [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086)

Simplify `polaris` client script

---

bom/build.gradle.kts

Nit: add misc-types to bom

---

quarkus/admin/src/main/docker/Dockerfile.jvm
quarkus/admin/src/main/java/org/apache/polaris/admintool/PolarisAdminTool.java

Admin tool: fix Dockerfile.jvm

---

.asf.yaml

To avoid constantly CI approval.

Add Yun as a contributor

---

quarkus/admin/distribution/LICENSE
quarkus/admin/distribution/NOTICE
quarkus/server/distribution/LICENSE
quarkus/server/distribution/NOTICE

Align versions in distributions LICENSE and NOTICE related to last renovatebot updates.

Update versions in distribution LICENSE and NOTICE

---

quarkus/admin/distribution/LICENSE
quarkus/admin/distribution/NOTICE
quarkus/server/distribution/LICENSE
quarkus/server/distribution/NOTICE

Update distributions `LICENSE` and `NOTICE` according to the latest dependency updates.

Update LICENSE/NOTICE with latest versions

---

README.md

This updated the README with links to the respective sections in the Apache Polaris website, which will give potential users a better understanding of what Polaris is and how to use it.

Update README with links to new Quickstart experience

---

site/content/_index.adoc

Adds a new button on the Apache Polaris homepage to direct users towards the Getting Started experience.

Add Getting Started Button to the Apache Polaris Website Homepage

---

plugins/spark/v3.5/integration/build.gradle.kts

... do not let Spark leak into Quarkus

Spark-IT: use correct configurations

---

site/content/in-dev/0.9.0/polaris-management-service.md
site/content/in-dev/0.9.0/rest-catalog-open-api.md
site/layouts/shortcodes/redoc-polaris.html

The "Management Spec" and "Catalog Spec" links on the website currently fail to render the correct spec file. This PR fix it

Site: Fix Management and Catalog Spec links

---

plugins/spark/README.md
site/content/in-dev/unreleased/polaris-spark-client.md

1) add a page polaris-spark-client.md under unreleased
2) update README for plugin/spark to be more complete
Tested with local build using 
```
site/bin/create-static-site.sh --local
```

Add polaris spark client webpage under unreleased

---

.asf.yaml
.github/CODEOWNERS

Add new elected committers (Ajantha, Pierre, Prashant, Jonas).

Add new committers

---

site/content/community/_index.adoc

Update website with new committers.

Add new committers on website

---

site/content/community/release-guide.md
site/content/release-guide.md
site/hugo.yaml

I propose to add this release guide.

Add release guide on the website

---

polaris-server.yml
site/static/schemas/policies/system/data-compaction/2025-02-03.json
site/static/schemas/policies/system/metadata-compaction/2025-02-03.json
site/static/schemas/policies/system/orphan-file-removal/2025-02-03.json
site/static/schemas/policies/system/snapshot-expiry/2025-02-03.json

Local site test passed. These static files can show normally.

Site: Publish table maintenance policies

---

NOTICE

@rdblue @justinmclean can you please take a look on this change (following the discussion on the Incubator general mailing list) ?

Following vote/discussion on the Incubator general mailing list, NOTICE now contains part of Nessie NOTICE

---

quarkus/admin/src/main/resources/application.properties

The previous WARNING log levels seems to work, but WARN aligns better with standard Quarkus log levels.
Fixes #1612

nit: fix admin tool log level and comments

---

regtests/run_spark_sql.sh

Switched from `logred` to `echo`

nit: implement logred for run_spark_sql.sh (#1640)

---

quarkus/admin/build.gradle.kts
quarkus/distribution/build.gradle.kts

This PR remove unused adminDocs artifact, more details and discussion are here, https://github.com/apache/polaris/pull/1694#discussion_r2112128574 cc @adutra @jbonofre

Remove unused adminDocs artifact

---

quarkus/admin/build.gradle.kts

Test: silence CDS warning from admin tool tests

---

quarkus/admin/distribution/LICENSE
quarkus/admin/distribution/NOTICE
quarkus/distribution/LICENSE
quarkus/distribution/NOTICE
quarkus/server/distribution/LICENSE
quarkus/server/distribution/NOTICE

I ran my script to update versions in LICENSE and NOTICE files.

Update versions in LICENSE and NOTICE

---

.github/workflows/python-client.yml
client/python/.openapi-generator-ignore
client/python/.pre-commit-config.yaml
client/python/Makefile
client/python/docker-compose.yml
client/python/integration_tests/conftest.py
client/python/integration_tests/test_catalog_apis.py
client/python/integration_tests/test_management_apis.py
client/python/pyproject.toml
client/templates/regenerate.sh

Fixes: https://github.com/apache/polaris/issues/1779
Add some integration tests for python client that covers most of the usage in Quickstart examples, CLI and regtests
- catalog creation
- principal/principal roles/catalog roles creation/assign/grant
- namespace creation/list/drop
- table creation/list/load/drop (with purge)
The PR also configures [precommit](https://pre-commit.com/) and [Ruff](https://github.com/astral-sh/ruff-pre-commit) to auto-format the added test codes

Add more tests to Python Client

---

getting-started/telemetry/README.md
getting-started/telemetry/docker-compose.yml

Fix telemetry quickstart example for 1.0 release

---

README.md

Fix https://github.com/apache/polaris/issues/1861

Fix two wrong links in README.md

---

integration-tests/src/main/java/org/apache/polaris/service/it/test/PolarisRestCatalogIntegrationTest.java

tests were added in 8b5dfa97a8e50a53412d2ded40f2e4db5a40cc42 and afaict supposed to get enabled after ec97c1b7ecdce7a34b1a8bc109bcdfe1d3ce339f

enable ETag integration tests

---

plugins/spark/v3.5/spark/build.gradle.kts

fix: Typo in Spark Client Build File

---

service/common/src/main/java/org/apache/polaris/service/storage/StorageConfiguration.java

Use `DefaultCredentialsProvider.builder().build()` as suggested by AWS SDK javadoc.

chore: Avoid deprecated `DefaultCredentialsProvider.create()`

---

polaris-core/src/main/java/org/apache/polaris/core/entity/table/TableLikeEntity.java

chore: fix class reference in the javadoc of TableLikeEntity

---

persistence/relational-jdbc/src/main/java/org/apache/polaris/persistence/relational/jdbc/JdbcBasePersistenceImpl.java

With serializable isolation level, if either the primary-key or the check-constraint are violated, the lookup of the conflicting entity is not guaranteed to yield a non-null result (transaction start matters). This changes works around this situation w/ serializable isolation.

JDBC: SERIALIZABLE/EntityNotFoundException

---

polaris-core/src/main/java/org/apache/polaris/core/persistence/resolver/Resolver.java

cleans up a minor inconsistency

Prefer diagnostics field in Resolver

---

site/content/in-dev/unreleased/external-idp.md

Minor fixes and enhancements to External IDP documentation

---

site/content/in-dev/unreleased/entities.md

The auto-generated API docs has been removed(#1878), so the API doc links are all broken.
This updates the API doc links to point directly to the open api yaml.

fix(docs): fix entity doc API links.

---

polaris-core/src/main/java/org/apache/polaris/core/persistence/pagination/Page.java

Correct method args (follow-up to #2401)

chore: fix Page javadoc

---

runtime/service/src/main/java/org/apache/polaris/service/events/jsonEventListener/PropertyMapEventListener.java
runtime/service/src/test/java/org/apache/polaris/service/events/jsonEventListener/aws/cloudwatch/AwsCloudWatchEventListenerTest.java

Consecutive merges, where one class was moved in the first PR but was not reflected in the second PR.

Fix failing CI

---

integration-tests/src/main/java/org/apache/polaris/service/it/ext/SparkSessionBuilder.java

Remove unused config from SparkSessionBuilder

---

1.1.0/helm.md

Remove `SNAPSHOT` from 1.1.0 Helm doc

---

CHANGELOG.md

Using `git log -p apache-polaris-1.1.0-incubating..553cb06e5dcfe1019a7f8565af13bc4ebf9e2e5b -- CHANGELOG.md` to find changes missed in the previous CHANGELOG update (#2635)

Re-add CHANGELOG.md entry for #2197

---

polaris-core/src/main/java/org/apache/polaris/core/persistence/pagination/Page.java

Non-functional change for existing code, adds a `Page` factory function.

NoSQL: minor change to polaris-core for paging

---

runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisCatalogsEventServiceDelegator.java
runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisPrincipalRolesEventServiceDelegator.java

Event instrumentation for the following APIs have been added as part of this PR:
* createCatalog
* createPrincipalRole
* createCatalogRole
* addGrantToCatalogRole
* revokeGrantFromCatalogRole

Add events for APIs awaiting API changes

---

site/content/community/_index.adoc

I'm no longer affiliated with Snowflake, so we should update this page accordingly.

Update team entry for  eric-maynard

---

runtime/service/src/main/java/org/apache/polaris/service/admin/PolarisAdminService.java

- remove mutable `resolutionManifest` field in favor of letting the
"authorize" methods return their `PolarisResolutionManifest`
- replace `find` helpers with `get` helpers that have built-in error
handling

Refactor resolutionManifest handling in PolarisAdminService

---

CHANGELOG.md

This just adds details about this PR to the changelog.
https://github.com/apache/polaris/pull/2697

Update Changelog with finer grained authz feature
